//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <CoreData/NSManagedObject.h>

@class NSString, TNDRMoment, TNDRMomentPhotoID;

@interface _TNDRMomentPhoto : NSManagedObject
{
}

+ (id)keyPathsForValuesAffectingValueForKey:(id)arg1;
+ (id)entityInManagedObjectContext:(id)arg1;
+ (id)entityName;
+ (id)insertInManagedObjectContext:(id)arg1;
@property(readonly, nonatomic) TNDRMomentPhotoID *objectID;

// Remaining properties
@property(retain, nonatomic) NSString *large; // @dynamic large;
@property(retain, nonatomic) NSString *medium; // @dynamic medium;
@property(retain, nonatomic) TNDRMoment *moment; // @dynamic moment;
@property(retain, nonatomic) NSString *orig; // @dynamic orig;
@property(retain, nonatomic) NSString *photoID; // @dynamic photoID;
@property(retain, nonatomic) NSString *small; // @dynamic small;
@property(retain, nonatomic) NSString *thumb; // @dynamic thumb;

@end

