//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <CoreData/NSManagedObject.h>

@class NSSet, NSString, TNDRAlbumID, TNDRTrack;

@interface _TNDRAlbum : NSManagedObject
{
}

+ (id)keyPathsForValuesAffectingValueForKey:(id)arg1;
+ (id)entityInManagedObjectContext:(id)arg1;
+ (id)entityName;
+ (id)insertInManagedObjectContext:(id)arg1;
- (id)albumArtSet;
@property(readonly, nonatomic) TNDRAlbumID *objectID;

// Remaining properties
@property(retain, nonatomic) NSSet *albumArt; // @dynamic albumArt;
@property(retain, nonatomic) NSString *id; // @dynamic id;
@property(retain, nonatomic) NSString *name; // @dynamic name;
@property(retain, nonatomic) TNDRTrack *track; // @dynamic track;

@end

