//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

@class TNDRGradientActionButtonFooter, UIImageView, UILabel;

@interface _TtC6Tinder17PrePermissionView : UIView
{
    // Error parsing type: , name: imageDimension
    // Error parsing type: , name: imageView.storage
    // Error parsing type: , name: titleLabel.storage
    // Error parsing type: , name: detailLabel.storage
    // Error parsing type: , name: buttonFooter.storage
}

- (CDUnknownBlockType).cxx_destruct;
- (void)setup;
- (id)initWithCoder:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;
@property(nonatomic, retain) TNDRGradientActionButtonFooter *buttonFooter;
@property(nonatomic, retain) UILabel *detailLabel;
@property(nonatomic, retain) UILabel *titleLabel;
@property(nonatomic, retain) UIImageView *imageView;

@end

