//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

@class FBAdChoicesView, UIImageView, UILabel;

@interface _TtC6Tinder15FANAdHeaderView : UIView
{
    // Error parsing type: , name: titleLabel
    // Error parsing type: , name: sponsoredLabel
    // Error parsing type: , name: sponsoredIcon
    // Error parsing type: , name: adChoicesView
}

- (CDUnknownBlockType).cxx_destruct;
- (id)initWithCoder:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;
- (id)hitTest:(struct CGPoint)arg1 withEvent:(id)arg2;
- (void)awakeFromNib;
@property(nonatomic) __weak FBAdChoicesView *adChoicesView; // @synthesize adChoicesView;
@property(nonatomic) __weak UIImageView *sponsoredIcon; // @synthesize sponsoredIcon;
@property(nonatomic) __weak UILabel *sponsoredLabel; // @synthesize sponsoredLabel;
@property(nonatomic) __weak UILabel *titleLabel; // @synthesize titleLabel;

@end

