//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "_TtC6Tinder23PasswordAndEmailContext.h"

@interface _TtC6Tinder23PasswordAndEmailContext (Tinder1)
- (void)collectEmailViewControllerDidCancel:(id)arg1;
- (void)collectEmailViewController:(id)arg1 didCollectEmail:(id)arg2;
@end

