//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@interface _TtC6Tinder15FastMatchClient : NSObject
{
    // Error parsing type: , name: defaultSession
    // Error parsing type: , name: fastMatchPreviewTask
}

- (CDUnknownBlockType).cxx_destruct;
- (id)init;

@end

