//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <swiftCore/SwiftObject.h>

@interface _TtC6Tinder29DeleteAccountAnalyticsTracker : SwiftObject
{
    // Error parsing type: , name: eventName
    // Error parsing type: , name: lastDifferentEventCode
    // Error parsing type: , name: previousEventCode
    // Error parsing type: , name: previousReasonSelected
    // Error parsing type: , name: previousReasonsShown
    // Error parsing type: , name: previousReasonsOrdering
    // Error parsing type: , name: previousFeedback
    // Error parsing type: , name: previousBugReasonsSelected
    // Error parsing type: , name: previousBugReasonsShown
    // Error parsing type: , name: previousBugReasonsOrdering
    // Error parsing type: , name: previousBugFeedback
    // Error parsing type: , name: previousDislikeReasonsSelected
    // Error parsing type: , name: previousDislikeReasonsShown
    // Error parsing type: , name: previousDislikeReasonsOrdering
    // Error parsing type: , name: previousDislikeFeedback
    // Error parsing type: , name: didInitiateDelete
}

@end

