//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIViewController.h>

@class NSString, TNDREditGenderTableViewFooter, TNDRGradientButton, UIImageView, UITableView, _TtC6Tinder20SearchViewController;

@interface _TtC6Tinder14CustomGenderVC : UIViewController
{
    // Error parsing type: , name: headerID
    // Error parsing type: , name: submitButtonHeight
    // Error parsing type: , name: checkmark
    // Error parsing type: , name: disclosure
    // Error parsing type: , name: tableView.storage
    // Error parsing type: , name: footerView.storage
    // Error parsing type: , name: delegate
    // Error parsing type: , name: customGender
    // Error parsing type: , name: profileVisibilityOn
    // Error parsing type: , name: searchSettingGender
    // Error parsing type: , name: hideNavBarOnDismiss
    // Error parsing type: , name: customGenderSearchDataSource.storage
    // Error parsing type: , name: customGenderSearchVC.storage
    // Error parsing type: , name: submitButton.storage
}

- (CDUnknownBlockType).cxx_destruct;
- (id)initWithCoder:(id)arg1;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;
- (void)setTitle:(id)arg1 for:(id)arg2 fontSize:(double)arg3;
- (void)attributedLabel:(id)arg1 didSelectLinkWithURL:(id)arg2;
- (_Bool)textFieldShouldBeginEditing:(id)arg1;
- (_Bool)textFieldShouldClear:(id)arg1;
- (void)didToggleSwitch:(id)arg1;
- (void)didSelectGenderSearchOptionAt:(id)arg1;
- (id)headerTextForSection:(long long)arg1;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (double)tableView:(id)arg1 heightForFooterInSection:(long long)arg2;
- (id)tableView:(id)arg1 viewForHeaderInSection:(long long)arg2;
- (double)tableView:(id)arg1 heightForHeaderInSection:(long long)arg2;
- (double)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (void)configureSearchSettingCell:(id)arg1 at:(id)arg2;
- (void)configureProfileVisibilityCell:(id)arg1;
- (void)configureCustomGenderCell:(id)arg1;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (long long)numberOfSectionsInTableView:(id)arg1;
- (void)didTapSubmit;
- (void)openGenderSearch;
- (void)viewDidDisappear:(_Bool)arg1;
- (void)viewWillDisappear:(_Bool)arg1;
- (void)viewDidAppear:(_Bool)arg1;
- (void)viewWillAppear:(_Bool)arg1;
- (void)viewDidLoad;
@property(nonatomic, retain) TNDRGradientButton *submitButton;
@property(nonatomic, retain) _TtC6Tinder20SearchViewController *customGenderSearchVC;
@property(nonatomic) _Bool hideNavBarOnDismiss; // @synthesize hideNavBarOnDismiss;
@property(nonatomic) long long searchSettingGender; // @synthesize searchSettingGender;
@property(nonatomic) _Bool profileVisibilityOn; // @synthesize profileVisibilityOn;
@property(nonatomic, copy) NSString *customGender; // @synthesize customGender;
@property(nonatomic, retain) TNDREditGenderTableViewFooter *footerView;
@property(nonatomic, retain) UITableView *tableView;
@property(nonatomic, readonly) UIImageView *disclosure; // @synthesize disclosure;
@property(nonatomic, readonly) UIImageView *checkmark; // @synthesize checkmark;
@property(nonatomic, readonly) double submitButtonHeight; // @synthesize submitButtonHeight;
@property(nonatomic, readonly) NSString *headerID; // @synthesize headerID;

@end

