//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIViewController.h>

@class NSArray;

@interface _TtC6Tinder29PlusConsumablesViewController : UIViewController
{
    // Error parsing type: , name: consumables
    // Error parsing type: , name: consumableViews
}

- (CDUnknownBlockType).cxx_destruct;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;
@property(nonatomic, readonly) double preferredContentHeight;
- (void)configureFor:(id)arg1;
- (void)setup;
- (void)viewDidLoad;
- (void)loadView;
- (id)initWithCoder:(id)arg1;
- (id)initWith:(id)arg1;
@property(nonatomic, copy) NSArray *consumableViews; // @synthesize consumableViews;
@property(nonatomic, readonly) NSArray *consumables; // @synthesize consumables;

@end

