//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "_TtC6Tinder12DFPAdContext.h"

#import "GADBannerViewDelegate-Protocol.h"

@interface _TtC6Tinder12DFPAdContext (Tinder) <GADBannerViewDelegate>
- (void)adView:(id)arg1 didFailToReceiveAdWithError:(id)arg2;
- (void)adViewDidReceiveAd:(id)arg1;
@end

