//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

@class _TtC6Tinder13CardBadgeView;

@interface _TtC6Tinder17GroupCardInfoView : UIView
{
    // Error parsing type: , name: badgeView.storage
    // Error parsing type: , name: group
    // Error parsing type: , name: groupCardViewModel
    // Error parsing type: , name: showBadge
    // Error parsing type: , name: showSuperLikeView
    // Error parsing type: , name: groupOwnerLabel.storage
    // Error parsing type: , name: otherUsersLabel.storage
    // Error parsing type: , name: superLikeStarView.storage
    // Error parsing type: , name: gradientLayer.storage
    // Error parsing type: , name: hideBadgeConstraints.storage
    // Error parsing type: , name: showBadgeConstraints.storage
    // Error parsing type: , name: hideSuperLikeConstraints.storage
    // Error parsing type: , name: showSuperLikeConstraints.storage
}

- (CDUnknownBlockType).cxx_destruct;
- (void)layoutSubviews;
- (void)configureWith:(id)arg1 isSuperLikeAvailable:(_Bool)arg2;
- (id)initWithCoder:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;
@property(nonatomic, retain) _TtC6Tinder13CardBadgeView *badgeView;

@end

