//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <swiftCore/SwiftObject.h>

@interface _TtC6Tinder34FastMatchRecommendationsInteractor : SwiftObject
{
    // Error parsing type: , name: recsAPIClient.storage
    // Error parsing type: , name: currentRequest
    // Error parsing type: , name: imagePrefetcher
    // Error parsing type: , name: nextPage
    // Error parsing type: , name: operationQueue.storage
}

@end

