//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "_TtC6Tinder9FANAdView.h"

@interface _TtC6Tinder9FANAdView (Tinder)
@property(nonatomic, readonly) double itemPadding;
- (id)itemAt:(long long)arg1;
@end

