//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "TNDRExperiment.h"

@class NSArray, NSString;

@interface _TtC6Tinder13FANExperiment : TNDRExperiment
{
    // Error parsing type: , name: fanAdsEnabledVariable
    // Error parsing type: , name: fanPlacementIDVariable
}

- (CDUnknownBlockType).cxx_destruct;
@property(nonatomic, readonly) NSArray *overridableExperimentVariables;
@property(nonatomic, readonly) NSString *placementID;
@property(nonatomic, readonly) _Bool fanAdsEnabled;
@property(nonatomic, readonly) NSString *name;
- (void)setup;
- (id)initWithCoder:(id)arg1;
- (id)init;

@end

