//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

@class CAShapeLayer;

@interface _TtC6Tinder10CutOutView : UIView
{
    // Error parsing type: , name: shapeLayer.storage
    // Error parsing type: , name: drawer
    // Error parsing type: , name: currentProgress
    // Error parsing type: , name: animation
}

- (CDUnknownBlockType).cxx_destruct;
- (id)initWithFrame:(struct CGRect)arg1;
- (struct CGAffineTransform)transformForCenteringWithSize:(struct CGSize)arg1 containerSize:(struct CGSize)arg2;
- (id)hollowPathWithShapeSize:(struct CGSize)arg1 containerSize:(struct CGSize)arg2;
- (void)updateWithProgress:(double)arg1;
- (void)layoutSubviews;
- (id)initWithCoder:(id)arg1;
@property(nonatomic) double currentProgress; // @synthesize currentProgress;
@property(nonatomic, retain) CAShapeLayer *shapeLayer;

@end

