//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "_TtC6TinderP33_1A85D4FD02AC0EBA521F8114F82EF76829PaywallCarouselCollectionView.h"

@interface _TtC6TinderP33_1A85D4FD02AC0EBA521F8114F82EF76829PaywallCarouselCollectionView (Tinder)
- (id)collectionView:(id)arg1 cellForItemAtIndexPath:(id)arg2;
- (long long)collectionView:(id)arg1 numberOfItemsInSection:(long long)arg2;
@end

