//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

@class NSString;

@interface _TtC6Tinder26FastMatchCircularBadgeView : UIView
{
    // Error parsing type: , name: badgeText
    // Error parsing type: , name: label
}

- (CDUnknownBlockType).cxx_destruct;
- (void)layoutSubviews;
- (id)initWithCoder:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;
@property(nonatomic, copy) NSString *badgeText; // @synthesize badgeText;

@end

