//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "_TtC6Tinder35DeleteAccountFeedbackViewController.h"

@interface _TtC6Tinder35DeleteAccountFeedbackViewController (Tinder)
- (void)willMoveToParentViewController:(id)arg1;
- (void)updateViewConstraints;
- (void)viewWillDisappear:(_Bool)arg1;
- (void)viewDidAppear:(_Bool)arg1;
- (void)viewWillAppear:(_Bool)arg1;
- (void)viewDidLoad;
@end

