//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

@class CADisplayLink, NSLayoutConstraint, TNDRGamepadButton, UIButton, UILabel;
@protocol _TtP6Tinder36HomeMerchandisingConsumableViewModel_;

@interface _TtC6Tinder21TinderPlusProductView : UIView
{
    // Error parsing type: , name: viewModel
    // Error parsing type: , name: remainingCount
    // Error parsing type: , name: remainingTimeLabelHeightConstraint
    // Error parsing type: , name: paywallLabelHeightConstraint
    // Error parsing type: , name: productButton.storage
    // Error parsing type: , name: remainingTimeLabel.storage
    // Error parsing type: , name: paywallButton.storage
    // Error parsing type: , name: preferredContentHeight
}

- (CDUnknownBlockType).cxx_destruct;
- (id)initWithFrame:(struct CGRect)arg1;
- (void)setup;
- (id)initWithCoder:(id)arg1;
- (void)updateTimeRemaining;
@property(nonatomic, readonly) struct CGSize intrinsicContentSize;
- (void)configureViews;
@property(nonatomic) double preferredContentHeight; // @synthesize preferredContentHeight;
- (void)configureWith:(id)arg1;
- (void)requestPaywall;
@property(nonatomic, readonly) _Bool requiresConstraintBasedLayout;
- (id)initWith:(id)arg1;
@property(nonatomic, readonly) CADisplayLink *displayLink;
@property(nonatomic, retain) UIButton *paywallButton;
- (void)setConsumableRemaining:(long long)arg1;
- (void)setTimeRemaining:(double)arg1;
@property(nonatomic, retain) UILabel *remainingTimeLabel;
@property(nonatomic, retain) TNDRGamepadButton *productButton;
@property(nonatomic, retain) NSLayoutConstraint *paywallLabelHeightConstraint; // @synthesize paywallLabelHeightConstraint;
@property(nonatomic, retain) NSLayoutConstraint *remainingTimeLabelHeightConstraint; // @synthesize remainingTimeLabelHeightConstraint;
@property(nonatomic) long long remainingCount; // @synthesize remainingCount;
@property(nonatomic, retain) id <_TtP6Tinder36HomeMerchandisingConsumableViewModel_> viewModel; // @synthesize viewModel;
@property(nonatomic, readonly) long long type;

@end

