//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "_TtC6Tinder20GroupCardContentView.h"

@interface _TtC6Tinder20GroupCardContentView (Tinder5)
- (id)transitioningUserID;
- (id)transitionInfoView;
- (id)transitionImageView;
- (void)updateTransitionInfoToProfileAtIndex:(long long)arg1;
- (void)willTransitionToCard;
@end

