//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "_TtC6Tinder19PaywallCarouselView.h"

@interface _TtC6Tinder19PaywallCarouselView (Tinder1)
- (void)handlePageControlTappedWithPageControl:(id)arg1;
- (void)handleAutoscrollTimerFiredWithTimer:(id)arg1;
- (void)startAutoscrollTimerWithLongDelay:(_Bool)arg1;
- (void)stopAutoscrollTimer;
- (void)startAutoscrollTimerWithDelay:(double)arg1;
@end

