//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <swiftCore/SwiftObject.h>

@protocol _TtP6Tinder24HomeMerchandisingPaywall_;

@interface _TtC6Tinder32PlusSuperLikeConsumableViewModel : SwiftObject
{
    // Error parsing type: , name: currentUser
    // Error parsing type: , name: paywallDelegate
    // Error parsing type: , name: type
    // Error parsing type: , name: timeIntervalRemaining
}

@property(nonatomic) double timeIntervalRemaining; // @synthesize timeIntervalRemaining;
@property(nonatomic, readonly) long long remaining;
@property(nonatomic) long long type; // @synthesize type;
@property(nonatomic) __weak id <_TtP6Tinder24HomeMerchandisingPaywall_> paywallDelegate; // @synthesize paywallDelegate;

@end

