//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "_TtC6Tinder27SuperLikeTutorialInteractor.h"

@interface _TtC6Tinder27SuperLikeTutorialInteractor (Tinder)
- (void)superLikeTutorialDidChooseSuperLike:(id)arg1;
- (void)superLikeTutorialDidChooseNotNow:(id)arg1;
@end

