//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "_TtC6Tinder23ProfilePhotoEditContext.h"

@interface _TtC6Tinder23ProfilePhotoEditContext (Tinder)
- (void)endEditingPhotosWith:(CDUnknownBlockType)arg1;
- (void)beginEditingPhotos;
- (void)swapPhotoFromIndex:(long long)arg1 toIndex:(long long)arg2;
- (void)deletePhotoAt:(id)arg1 from:(id)arg2 completion:(CDUnknownBlockType)arg3;
@end

