//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "_TtC6Tinder20OnboardingStepBaseVC.h"

@class TNDRCustomGenderExperiment, TNDRGradientButton, UIButton, _TtC6Tinder14CustomGenderVC;

@interface _TtC6Tinder22OnboardingStepGenderVC : _TtC6Tinder20OnboardingStepBaseVC
{
    // Error parsing type: , name: womanButton.storage
    // Error parsing type: , name: manButton.storage
    // Error parsing type: , name: genderExperiment.storage
    // Error parsing type: , name: moreButton.storage
    // Error parsing type: , name: customGenderVC.storage
}

- (CDUnknownBlockType).cxx_destruct;
- (id)initWithCoder:(id)arg1;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;
- (void)clearCustomGender;
- (void)customGenderVCDidSubmitWithCustomGender:(id)arg1 profileVisibilityOn:(_Bool)arg2 searchSettingGender:(long long)arg3;
- (void)customGenderVCDidDisappear;
- (void)customGenderVCDidAppear;
- (void)moreTapped;
- (void)womanTapped;
- (void)manTapped;
- (void)genderUpdated;
- (id)genderValueFromType:(long long)arg1;
- (void)didTapSubmitWithHasCustomGender:(_Bool)arg1;
- (void)didTapSubmit;
- (_Bool)isComplete;
- (void)viewWillAppear:(_Bool)arg1;
- (void)viewDidLoad;
- (id)setupGenderButton;
@property(nonatomic, retain) _TtC6Tinder14CustomGenderVC *customGenderVC;
@property(nonatomic, retain) UIButton *moreButton;
@property(nonatomic, retain) TNDRCustomGenderExperiment *genderExperiment;
@property(nonatomic, retain) TNDRGradientButton *manButton;
@property(nonatomic, retain) TNDRGradientButton *womanButton;

@end

