//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "_TtC6Tinder10CutOutView.h"

@class UIView;

@interface _TtC6Tinder10CutOutView (Tinder)
- (void)cancelWithDuration:(double)arg1;
- (void)finishWithDuration:(double)arg1;
@property(nonatomic, readonly) UIView *view;
@end

