//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UITableViewCell.h>

@class NSString, UITextView;

@interface _TtC6Tinder27EditProfileItemTextViewCell : UITableViewCell
{
    // Error parsing type: , name: maxCharacters
    // Error parsing type: , name: textToDisplay
    // Error parsing type: , name: placeholder
    // Error parsing type: , name: textViewDidBeginEditing
    // Error parsing type: , name: textViewDidChange
    // Error parsing type: , name: textViewDidEndEditing
    // Error parsing type: , name: textViewDidChangeSelection
    // Error parsing type: , name: textView.storage
    // Error parsing type: , name: charsLeft.storage
    // Error parsing type: , name: heightConstraint.storage
}

- (CDUnknownBlockType).cxx_destruct;
- (void)updatePlaceholder;
- (void)updateRemainingChars;
- (void)showWithCharsLeft:(_Bool)arg1;
- (void)prepareForReuse;
- (void)configure;
- (id)initWithCoder:(id)arg1;
- (id)initWithStyle:(long long)arg1 reuseIdentifier:(id)arg2;
@property(nonatomic, retain) UITextView *textView;
@property(nonatomic, copy) CDUnknownBlockType textViewDidChangeSelection; // @synthesize textViewDidChangeSelection;
@property(nonatomic, copy) CDUnknownBlockType textViewDidEndEditing; // @synthesize textViewDidEndEditing;
@property(nonatomic, copy) CDUnknownBlockType textViewDidChange; // @synthesize textViewDidChange;
@property(nonatomic, copy) CDUnknownBlockType textViewDidBeginEditing; // @synthesize textViewDidBeginEditing;
@property(nonatomic, copy) NSString *placeholder; // @synthesize placeholder;
@property(nonatomic, copy) NSString *textToDisplay; // @synthesize textToDisplay;
@property(nonatomic) long long maxCharacters; // @synthesize maxCharacters;

@end

