//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIVisualEffectView.h>

@class NSLayoutConstraint, UIView;

@interface _TtC6Tinder11PageControl : UIVisualEffectView
{
    // Error parsing type: , name: currentPage
    // Error parsing type: , name: numberOfPages
    // Error parsing type: , name: grayView
    // Error parsing type: , name: indicatorView
    // Error parsing type: , name: indicatorViewLeadingConstraint.storage
    // Error parsing type: , name: indicatorViewWidthConstraint.storage
}

- (CDUnknownBlockType).cxx_destruct;
- (id)initWithEffect:(id)arg1;
- (void)previous;
- (void)next;
- (void)updateWithNumberOfPages:(long long)arg1;
- (void)updateWithCurrentPage:(long long)arg1;
- (void)layoutSubviews;
- (id)initWithCoder:(id)arg1;
- (id)initWithNumberOfPages:(long long)arg1 currentPage:(long long)arg2;
@property(nonatomic, retain) NSLayoutConstraint *indicatorViewWidthConstraint;
@property(nonatomic, retain) NSLayoutConstraint *indicatorViewLeadingConstraint;
@property(nonatomic, readonly) UIView *indicatorView; // @synthesize indicatorView;
@property(nonatomic, readonly) UIView *grayView; // @synthesize grayView;
@property(nonatomic) long long currentPage; // @synthesize currentPage;

@end

