//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UICollectionView.h>

@class NSArray, NSDictionary, NSLayoutConstraint, NSString;

@interface _TtC6TinderP33_1A85D4FD02AC0EBA521F8114F82EF76829PaywallCarouselCollectionView : UICollectionView
{
    // Error parsing type: , name: paginator
    // Error parsing type: , name: heightConstraint
    // Error parsing type: , name: firstCellHeaderTopConstraint
    // Error parsing type: , name: needsExtraBottomPadding
    // Error parsing type: , name: items
    // Error parsing type: , name: viewCache
    // Error parsing type: , name: reuseIdentifier
}

- (CDUnknownBlockType).cxx_destruct;
- (void)layoutSubviews;
- (void)adjustHeightConstraint;
- (void)stopTimerIfNeeded;
- (id)initWithCoder:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1 collectionViewLayout:(id)arg2;
@property(nonatomic, readonly) NSString *reuseIdentifier; // @synthesize reuseIdentifier;
@property(nonatomic, copy) NSDictionary *viewCache; // @synthesize viewCache;
@property(nonatomic) struct UIEdgeInsets contentInset;
@property(nonatomic, copy) NSArray *items; // @synthesize items;
@property(nonatomic) _Bool needsExtraBottomPadding; // @synthesize needsExtraBottomPadding;
@property(nonatomic, retain) NSLayoutConstraint *firstCellHeaderTopConstraint; // @synthesize firstCellHeaderTopConstraint;
@property(nonatomic, retain) NSLayoutConstraint *heightConstraint; // @synthesize heightConstraint;

@end

