//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "TNDRDialogViewController.h"

@class TNDRAnalyticsTracker;
@protocol TNDRActionDialogViewControllerDelegate;

@interface _TtC6Tinder32PhotoRemovedDialogViewController : TNDRDialogViewController
{
    // Error parsing type: , name: actionDelegate
    // Error parsing type: , name: analyticsTracker
}

+ (id)viewControllerNavigationKey;
- (CDUnknownBlockType).cxx_destruct;
- (id)initWithCoder:(id)arg1;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;
- (void)reportAnalytics;
- (double)preferredDialogViewControllerContainerWidth;
- (void)didPressActionWithButton:(id)arg1;
- (void)setupFooter;
- (void)setupHeader;
- (void)viewDidAppear:(_Bool)arg1;
- (void)viewDidLoad;
@property(nonatomic, readonly) TNDRAnalyticsTracker *analyticsTracker; // @synthesize analyticsTracker;
@property(nonatomic) __weak id <TNDRActionDialogViewControllerDelegate> actionDelegate; // @synthesize actionDelegate;

@end

