//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "_TtC6Tinder6Button.h"

@interface _TtC6Tinder19FANAdCarouselButton : _TtC6Tinder6Button
{
}

- (id)initWithCoder:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;
- (void)bounceBackWithDuration:(double)arg1 springDamping:(double)arg2 springVelocity:(double)arg3 repeats:(_Bool)arg4;
- (void)shortBounceBack;
- (void)longBounceBack;
- (void)reset;
- (void)shrink;
- (void)bounce;
- (void)dealloc;
- (void)awakeFromNib;

@end

