//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIViewController.h>

@class NSArray, NSString;

@interface _TtC6Tinder27EnterPasswordViewController : UIViewController
{
    // Error parsing type: , name: delegate
    // Error parsing type: , name: maxChars
    // Error parsing type: , name: genericDots
    // Error parsing type: , name: serverHasPassword
    // Error parsing type: , name: hasEditedPassword
    // Error parsing type: , name: hasEnteredValidPassword
    // Error parsing type: , name: isPasswordSimple
    // Error parsing type: , name: isPasswordValid
    // Error parsing type: , name: placeholder
    // Error parsing type: , name: validationTimer
    // Error parsing type: , name: passwordField.storage
    // Error parsing type: , name: infoDivider.storage
    // Error parsing type: , name: invalidChars
}

- (CDUnknownBlockType).cxx_destruct;
- (id)initWithCoder:(id)arg1;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;
- (_Bool)textFieldShouldReturn:(id)arg1;
- (_Bool)textField:(id)arg1 shouldChangeCharactersInRange:(struct _NSRange)arg2 replacementString:(id)arg3;
- (void)textFieldDidBeginEditing:(id)arg1;
- (void)textFieldDidChange:(id)arg1;
- (void)validatePasswordField;
- (void)stopEditing;
- (void)startEditing;
- (void)updateUIWithNetworkingError:(id)arg1;
- (void)updateUIWithAuthError:(id)arg1;
- (void)updateUIWithServerHasPassword:(_Bool)arg1;
- (void)updateUIWithPassword:(id)arg1;
- (void)clearErrorUI;
- (void)viewDidLoad;
@property(nonatomic, copy) NSArray *invalidChars; // @synthesize invalidChars;
@property(nonatomic, copy) NSString *placeholder; // @synthesize placeholder;
@property(nonatomic) _Bool isPasswordValid; // @synthesize isPasswordValid;
@property(nonatomic) _Bool isPasswordSimple; // @synthesize isPasswordSimple;
@property(nonatomic, readonly) NSString *text;
@property(nonatomic) _Bool hasEnteredValidPassword; // @synthesize hasEnteredValidPassword;
@property(nonatomic) _Bool hasEditedPassword; // @synthesize hasEditedPassword;
@property(nonatomic) _Bool serverHasPassword; // @synthesize serverHasPassword;
@property(nonatomic, readonly) NSString *genericDots; // @synthesize genericDots;
@property(nonatomic, readonly) long long maxChars; // @synthesize maxChars;

@end

