//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "_TtC6Tinder16KeyboardObserver.h"

@interface _TtC6Tinder16KeyboardObserver (Tinder)
- (void)willChangeFrameNotificationWithNotification:(id)arg1;
- (void)didHideNotificationWithNotification:(id)arg1;
- (void)willHideNotificationWithNotification:(id)arg1;
- (void)didShowNotificationWithNotification:(id)arg1;
- (void)willShowNotificationWithNotification:(id)arg1;
@end

