//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "TNDRDialogViewController.h"

@class _TtC6Tinder18CancelDialogFooter, _TtC6Tinder18ReportDialogHeader;

@interface _TtC6Tinder27ReasonsDialogViewController : TNDRDialogViewController
{
    // Error parsing type: , name: viewModel
    // Error parsing type: , name: reportReasons.storage
    // Error parsing type: , name: dialogType
    // Error parsing type: , name: dialogHeaderView.storage
    // Error parsing type: , name: dialogFooterView.storage
}

- (CDUnknownBlockType).cxx_destruct;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;
- (void)setupTableView;
- (void)viewDidLoad;
- (id)initWithCoder:(id)arg1;
@property(nonatomic, retain) _TtC6Tinder18CancelDialogFooter *dialogFooterView;
@property(nonatomic, retain) _TtC6Tinder18ReportDialogHeader *dialogHeaderView;

@end

