//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <swiftCore/SwiftObject.h>

@interface _TtC6Tinder20DisplayLinkAnimation : SwiftObject
{
    // Error parsing type: , name: duration
    // Error parsing type: , name: transpiredTime
    // Error parsing type: , name: finalProgress
    // Error parsing type: , name: initialProgress
    // Error parsing type: , name: animationCurve
    // Error parsing type: , name: delegate
    // Error parsing type: , name: displayLink.storage
    // Error parsing type: , name: inProgress
}

- (void)refresh;

@end

