//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <swiftCore/SwiftObject.h>

@interface _TtC6Tinder24SwipeInterruptionContext : SwiftObject
{
    // Error parsing type: , name: userSwipeContext.storage
    // Error parsing type: , name: groupSwipeContext.storage
    // Error parsing type: , name: adSwipeContext.storage
    // Error parsing type: , name: gamepadContext
}

@end

