//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "_TtC6Tinder33OverridableBoolExperimentVariable.h"

@class NSDictionary, NSObject, NSString;

@interface _TtC6Tinder21SwipeToProfileEnabled : _TtC6Tinder33OverridableBoolExperimentVariable
{
}

- (id)init;
@property(nonatomic, readonly) NSDictionary *mappingOfTitlesToPotentialValues;
@property(nonatomic, readonly) NSObject *nonOverriddenValue;
@property(nonatomic, readonly) NSString *name;

@end

