//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIViewController.h>

@protocol TNDRReportAnalyticsClient, TNDRViewControllerAnimatedTransitioning;

@interface _TtC6Tinder28UserReportedV2ViewController : UIViewController
{
    // Error parsing type: , name: reportedV2AnimationController
    // Error parsing type: , name: reportedDelegate
    // Error parsing type: , name: analyticsClient
    // Error parsing type: , name: reporteeImageURL
    // Error parsing type: , name: reporteeImageView
    // Error parsing type: , name: backgroundView
    // Error parsing type: , name: detailLabel1
    // Error parsing type: , name: detailLabel2
    // Error parsing type: , name: reportedStampView
}

- (CDUnknownBlockType).cxx_destruct;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;
- (void)loadMatchProfileImage;
- (void)animateStampView;
- (void)viewDidAppear:(_Bool)arg1;
- (void)setupConstraints;
- (void)viewDidLoad;
- (id)initWithCoder:(id)arg1;
- (id)initWithReporteeImageURL:(id)arg1 analyticsClient:(id)arg2;
@property(nonatomic) __weak id <TNDRReportAnalyticsClient> analyticsClient; // @synthesize analyticsClient;
@property(nonatomic, retain) id <TNDRViewControllerAnimatedTransitioning> reportedV2AnimationController; // @synthesize reportedV2AnimationController;

@end

