//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <swiftCore/SwiftObject.h>

@interface _TtC6Tinder26FastMatchRatingsInteractor : SwiftObject
{
    // Error parsing type: , name: dataService.storage
    // Error parsing type: , name: analyticsService.storage
    // Error parsing type: , name: notificationCenter.storage
    // Error parsing type: , name: newMatchPresenter
}

@end

