//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

@class NSDate, NSDictionary, NSString, UIImage, UIImageView, UILabel;

@interface _TtC6Tinder24SelectSettingsHeaderView : UIView
{
    // Error parsing type: , name: profilePhoto
    // Error parsing type: , name: firstName
    // Error parsing type: , name: memberSince
    // Error parsing type: , name: avatarImageView.storage
    // Error parsing type: , name: selectBadge.storage
    // Error parsing type: , name: nameLabel.storage
    // Error parsing type: , name: memberSinceLabel.storage
    // Error parsing type: , name: nameAttributes.storage
    // Error parsing type: , name: memberSinceAttributes.storage
}

+ (_Bool)requiresConstraintBasedLayout;
- (CDUnknownBlockType).cxx_destruct;
- (id)initWithFrame:(struct CGRect)arg1;
- (void)setupConstraints;
- (void)setupSubviews;
@property(nonatomic, copy) NSDictionary *memberSinceAttributes;
@property(nonatomic, copy) NSDictionary *nameAttributes;
@property(nonatomic, retain) UILabel *memberSinceLabel;
@property(nonatomic, retain) UILabel *nameLabel;
@property(nonatomic, retain) UIImageView *selectBadge;
@property(nonatomic, retain) UIImageView *avatarImageView;
- (id)initWithCoder:(id)arg1;
- (id)initWithProfilePhoto:(id)arg1 firstName:(id)arg2 memberSince:(id)arg3;
@property(nonatomic, copy) NSDate *memberSince; // @synthesize memberSince;
@property(nonatomic, readonly) NSString *firstName; // @synthesize firstName;
@property(nonatomic, readonly) UIImage *profilePhoto; // @synthesize profilePhoto;

@end

