//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "_TtC6Tinder29GroupProfilePreviewInteractor.h"

#import "TNDRGroupProfileViewControllerDelegate-Protocol.h"

@interface _TtC6Tinder29GroupProfilePreviewInteractor (Tinder1) <TNDRGroupProfileViewControllerDelegate>
- (void)groupProfileRequestsDismissal:(id)arg1;
- (void)groupProfileViewController:(id)arg1 didSelectProfileAtIndex:(unsigned long long)arg2;
@end

