//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class TNDRURLManager, UIViewController;

@interface _TtC6Tinder37AddProfilePhotoFromFacebookInteractor : NSObject
{
    // Error parsing type: , name: urlManager
    // Error parsing type: , name: completion
    // Error parsing type: , name: viewController
    // Error parsing type: , name: facebookImagePicker.storage
}

- (CDUnknownBlockType).cxx_destruct;
- (id)init;
- (void)didRequestToAddPhotoWithIsMainPhoto:(_Bool)arg1 from:(id)arg2 completion:(CDUnknownBlockType)arg3;
@property(nonatomic, retain) UIViewController *viewController; // @synthesize viewController;
@property(nonatomic, copy) CDUnknownBlockType completion; // @synthesize completion;
@property(nonatomic, readonly) TNDRURLManager *urlManager; // @synthesize urlManager;

@end

