//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

@class UILabel;

@interface _TtC6Tinder29FemaleMessageStandardItemView : UIView
{
    // Error parsing type: , name: emojiLabel
    // Error parsing type: , name: titleLabel
    // Error parsing type: , name: subtitleLabel
}

- (CDUnknownBlockType).cxx_destruct;
- (void)configureWithEmoji:(id)arg1 title:(id)arg2 subtitle:(id)arg3;
- (void)setupAutolayout;
- (id)initWithCoder:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;
@property(nonatomic, readonly) UILabel *subtitleLabel; // @synthesize subtitleLabel;
@property(nonatomic, readonly) UILabel *titleLabel; // @synthesize titleLabel;
@property(nonatomic, readonly) UILabel *emojiLabel; // @synthesize emojiLabel;

@end

