//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UICollectionViewCell.h>

@class UIActivityIndicatorView, UIImageView;

@interface _TtC6Tinder27GIFSearchCollectionViewCell : UICollectionViewCell
{
    // Error parsing type: , name: currentState
    // Error parsing type: , name: contentImageView.storage
    // Error parsing type: , name: spinner.storage
}

- (CDUnknownBlockType).cxx_destruct;
- (void)layoutSubviews;
- (void)prepareForReuse;
@property(nonatomic, retain) UIActivityIndicatorView *spinner;
@property(nonatomic, retain) UIImageView *contentImageView;
- (id)initWithCoder:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;

@end

