//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <swiftCore/SwiftObject.h>

@interface _TtC6Tinder35MessageStandardsUserInputInteractor : SwiftObject
{
    // Error parsing type: , name: currentUser
    // Error parsing type: , name: analyticsTracker
}

@end

