//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIButton.h>

@interface _TtC6Tinder21AnimatableArrowButton : UIButton
{
    // Error parsing type: , name: arrowState
    // Error parsing type: , name: intrinsicSize
    // Error parsing type: , name: arrowDimension
    // Error parsing type: , name: arrowSize
    // Error parsing type: , name: gradientLayer
    // Error parsing type: , name: iconShapeLayer
}

- (CDUnknownBlockType).cxx_destruct;
- (id)initWithFrame:(struct CGRect)arg1;
- (void)handleState;
- (void)layoutSubviews;
- (id)initWithCoder:(id)arg1;
- (id)initWithSize:(struct CGSize)arg1;

@end

