//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIViewController.h>

@class NSArray, NSString, UIActivityIndicatorView, UICollectionView, UIView;

@interface _TtC6Tinder23GIFSearchViewController : UIViewController
{
    // Error parsing type: , name: delegate
    // Error parsing type: , name: context
    // Error parsing type: , name: currentMode
    // Error parsing type: , name: currentQueryString
    // Error parsing type: , name: currentState
    // Error parsing type: , name: collectionView.storage
    // Error parsing type: , name: emptyView.storage
    // Error parsing type: , name: loadingView.storage
}

- (CDUnknownBlockType).cxx_destruct;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;
- (void)showGIFsForQueryString:(id)arg1;
- (void)viewDidLoad;
- (id)initWithCoder:(id)arg1;
@property(nonatomic, retain) UIActivityIndicatorView *loadingView;
@property(nonatomic, retain) UIView *emptyView;
@property(nonatomic, retain) UICollectionView *collectionView;
@property(nonatomic, readonly) NSArray *panGestures;
@property(nonatomic, copy) NSString *currentQueryString; // @synthesize currentQueryString;

@end

