//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class TNDRAnalyticsTracker, TNDRCurrentUser, TNDRInstagramLoginWebViewController;

@interface _TtC6Tinder24InstagramLoginInteractor : NSObject
{
    // Error parsing type: , name: currentUser
    // Error parsing type: , name: analyticsTracker
    // Error parsing type: , name: instagramLoginVC.storage
    // Error parsing type: , name: completion
}

- (CDUnknownBlockType).cxx_destruct;
- (id)init;
- (void)dismissInstagramLoginVC;
- (void)didRequestToConnectInstagramFrom:(id)arg1 with:(CDUnknownBlockType)arg2;
- (id)initWith:(id)arg1;
@property(nonatomic, copy) CDUnknownBlockType completion; // @synthesize completion;
@property(nonatomic, retain) TNDRInstagramLoginWebViewController *instagramLoginVC;
@property(nonatomic, readonly) TNDRAnalyticsTracker *analyticsTracker; // @synthesize analyticsTracker;
@property(nonatomic, readonly) TNDRCurrentUser *currentUser; // @synthesize currentUser;

@end

