//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSNotificationCenter, NSUserDefaults, TNDRAnalyticsTracker, TNDRAppDelegate, TNDRAppRater, TNDRCoreDataService, TNDRCurrentUser, TNDRDataManager, TNDREnvironmentHelper, TNDRExperimentCoordinator, TNDRLeanplumTracker, TNDRLeanplumUserAttributeTracker, TNDRLocationManager, TNDRMainPerformanceTracker, TNDRNotificationWindow, TNDRPaywallManager, TNDRProductsManager, TNDRSKProductsRequester, TNDRURLManager, UIApplication, UIViewController, _TtC6Tinder15LeanplumService, _TtC6Tinder19ReachabilityContext, _TtC6Tinder22PushPermissionsService, _TtC6Tinder9Analytics, _TtC6Tinder9AppsFlyer;

@interface _TtC6Tinder10AppContext : NSObject
{
    // Error parsing type: , name: rootViewConroller
    // Error parsing type: , name: currentUser.storage
    // Error parsing type: , name: dataManager.storage
    // Error parsing type: , name: dataService.storage
    // Error parsing type: , name: urlManager.storage
    // Error parsing type: , name: analyticsTracker.storage
    // Error parsing type: , name: newAnalyticsTracker.storage
    // Error parsing type: , name: pushPermissionsService.storage
    // Error parsing type: , name: environmentHelper.storage
    // Error parsing type: , name: performanceTracker.storage
    // Error parsing type: , name: appsFlyer.storage
    // Error parsing type: , name: leanplumService.storage
    // Error parsing type: , name: leanplumTracker.storage
    // Error parsing type: , name: leanplumUserAttributeTracker.storage
    // Error parsing type: , name: imageManager.storage
    // Error parsing type: , name: locationManager.storage
    // Error parsing type: , name: appRater.storage
    // Error parsing type: , name: notificationWindow.storage
    // Error parsing type: , name: experimentCoordinator.storage
    // Error parsing type: , name: productsManager.storage
    // Error parsing type: , name: paywallManager.storage
    // Error parsing type: , name: productRequester.storage
    // Error parsing type: , name: application.storage
    // Error parsing type: , name: appDelegate.storage
    // Error parsing type: , name: userDefaults.storage
    // Error parsing type: , name: notificationCenter.storage
    // Error parsing type: , name: reachabilityContext.storage
}

+ (id)shared;
- (CDUnknownBlockType).cxx_destruct;
- (void)reachabilityContextDidChangeStatus:(id)arg1;
- (void)dealloc;
- (void)updateWithRootViewController:(id)arg1;
- (id)init;
@property(nonatomic, retain) _TtC6Tinder19ReachabilityContext *reachabilityContext;
@property(nonatomic, retain) NSNotificationCenter *notificationCenter;
@property(nonatomic, retain) NSUserDefaults *userDefaults;
@property(nonatomic, retain) TNDRAppDelegate *appDelegate;
@property(nonatomic, retain) UIApplication *application;
@property(nonatomic, retain) TNDRSKProductsRequester *productRequester;
@property(nonatomic, retain) TNDRPaywallManager *paywallManager;
@property(nonatomic, retain) TNDRProductsManager *productsManager;
@property(nonatomic, retain) TNDRExperimentCoordinator *experimentCoordinator;
@property(nonatomic, retain) TNDRNotificationWindow *notificationWindow;
@property(nonatomic, retain) TNDRAppRater *appRater;
@property(nonatomic, retain) TNDRLocationManager *locationManager;
@property(nonatomic, retain) TNDRLeanplumUserAttributeTracker *leanplumUserAttributeTracker;
@property(nonatomic, retain) TNDRLeanplumTracker *leanplumTracker;
@property(nonatomic, retain) _TtC6Tinder15LeanplumService *leanplumService;
@property(nonatomic, retain) _TtC6Tinder9AppsFlyer *appsFlyer;
@property(nonatomic, retain) TNDRMainPerformanceTracker *performanceTracker;
@property(nonatomic, retain) TNDREnvironmentHelper *environmentHelper;
@property(nonatomic, retain) _TtC6Tinder22PushPermissionsService *pushPermissionsService;
@property(nonatomic, retain) _TtC6Tinder9Analytics *newAnalyticsTracker;
@property(nonatomic, retain) TNDRAnalyticsTracker *analyticsTracker;
@property(nonatomic, retain) TNDRURLManager *urlManager;
@property(nonatomic, retain) TNDRCoreDataService *dataService;
@property(nonatomic, retain) TNDRDataManager *dataManager;
@property(nonatomic, retain) TNDRCurrentUser *currentUser;
@property(nonatomic, retain) UIViewController *rootViewConroller; // @synthesize rootViewConroller;

@end

