//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "_TtC6Tinder18ChatViewController.h"

@interface _TtC6Tinder18ChatViewController (Tinder15)
- (void)handleLeaveGroupTapped;
- (void)handleMuteTapped;
- (void)handleCancelTapped;
- (void)handleReportTapped;
- (void)handleUnmatchTapped;
@end

