//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "_TtC6Tinder28ProfilePhotoDeleteInteractor.h"

@interface _TtC6Tinder28ProfilePhotoDeleteInteractor (Tinder)
- (void)actionSheetBackgroundTapped:(id)arg1;
- (void)actionSheet:(id)arg1 triggeredButtonWithID:(long long)arg2;
@end

