//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

@class NSArray;

@interface _TtC6Tinder10ArrowsView : UIView
{
    // Error parsing type: , name: numberOfArrows
    // Error parsing type: , name: arrows.storage
}

- (CDUnknownBlockType).cxx_destruct;
- (void)setupAutolayout;
- (id)initWithCoder:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;
@property(nonatomic, copy) NSArray *arrows;
@property(nonatomic, readonly) long long numberOfArrows; // @synthesize numberOfArrows;

@end

