//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

@class UICollectionView, UIVisualEffectView, _TtC6Tinder29FastMatchCollectionViewLayout;

@interface _TtC6Tinder13FastMatchView : UIView
{
    // Error parsing type: , name: blurView
    // Error parsing type: , name: collectionViewLayout.storage
    // Error parsing type: , name: collectionView.storage
    // Error parsing type: , name: maximumNumberOfVisibleCells
}

+ (id)cellReuseIdentifier;
- (CDUnknownBlockType).cxx_destruct;
- (void)setup;
- (id)initWithCoder:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;
@property(nonatomic) struct CGRect bounds;
@property(nonatomic) long long maximumNumberOfVisibleCells; // @synthesize maximumNumberOfVisibleCells;
@property(nonatomic, retain) UICollectionView *collectionView;
@property(nonatomic, retain) _TtC6Tinder29FastMatchCollectionViewLayout *collectionViewLayout;
@property(nonatomic, readonly) UIVisualEffectView *blurView; // @synthesize blurView;

@end

