//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

@class NSLayoutConstraint;

@interface _TtC6Tinder15MatchBadgesView : UIView
{
    // Error parsing type: , name: mainBadgeWidthConstraint
    // Error parsing type: , name: mainBadgeView
    // Error parsing type: , name: celebrityBadgeView
    // Error parsing type: , name: muteBadgeView
}

- (CDUnknownBlockType).cxx_destruct;
- (void)configureBadgesForMatch:(id)arg1 isSuperLikeAvailable:(_Bool)arg2 isSuperLikeMatch:(_Bool)arg3 isBoostMatch:(_Bool)arg4 isFastMatch:(_Bool)arg5;
- (void)resetBadgesView;
- (void)setupConstraints;
- (id)initWithCoder:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;
@property(nonatomic, readonly) _Bool hasFastMatchBadge;
@property(nonatomic, readonly) _Bool hasSuperLikeBadge;
@property(nonatomic, readonly) _Bool hasBoostBadge;
@property(nonatomic, retain) NSLayoutConstraint *mainBadgeWidthConstraint; // @synthesize mainBadgeWidthConstraint;

@end

