//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "TNDRExperimentVariable.h"

@class NSObject, NSString;

@interface _TtC6TinderP33_08E7A5886C76D66C48A68E5502BBAB7832MessageStandardsMaleLoadingTitle : TNDRExperimentVariable
{
    // Error parsing type: , name: key
    // Error parsing type: , name: translatableOption1
    // Error parsing type: , name: translatableOption2
    // Error parsing type: , name: translatableOption3
    // Error parsing type: , name: translatableOption4
}

- (CDUnknownBlockType).cxx_destruct;
- (id)init;
@property(nonatomic, readonly) NSObject *nonOverriddenValue;
@property(nonatomic, readonly) _Bool isOverridable;
@property(nonatomic, readonly) NSString *name;
@property(nonatomic, readonly) long long key; // @synthesize key;

@end

