//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIViewController.h>

@class TNDRActionSheet, TNDRGradientButton, UIImageView, UILabel, _TtC6Tinder12GradientView;

@interface _TtC6Tinder11PhotoPicker : UIViewController
{
    // Error parsing type: , name: delegate
    // Error parsing type: , name: gradientView
    // Error parsing type: , name: addView.storage
    // Error parsing type: , name: addLabel.storage
    // Error parsing type: , name: photoView.storage
    // Error parsing type: , name: photoReplaceButtonWidth
    // Error parsing type: , name: photoButton.storage
    // Error parsing type: , name: pickActionSheet.storage
}

- (CDUnknownBlockType).cxx_destruct;
- (id)initWithCoder:(id)arg1;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;
- (void)pickPhotoWithSourceType:(long long)arg1;
- (void)pickFromGallery;
- (void)takePhoto;
- (void)imagePickerControllerDidCancel:(id)arg1;
- (void)imagePickerController:(id)arg1 didFinishPickingMediaWithInfo:(id)arg2;
- (void)actionSheet:(id)arg1 triggeredButtonWithID:(long long)arg2;
- (void)addTapped;
- (void)viewDidLoad;
- (void)updatePhotoView;
- (void)updateWithPhoto:(id)arg1;
@property(nonatomic, retain) TNDRActionSheet *pickActionSheet;
@property(nonatomic, retain) TNDRGradientButton *photoButton;
@property(nonatomic, readonly) double photoReplaceButtonWidth; // @synthesize photoReplaceButtonWidth;
@property(nonatomic, retain) UIImageView *photoView;
@property(nonatomic, retain) UILabel *addLabel;
@property(nonatomic, retain) UIImageView *addView;
@property(nonatomic, readonly) _TtC6Tinder12GradientView *gradientView; // @synthesize gradientView;

@end

