//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UICollectionViewFlowLayout.h>

@interface _TtC6Tinder14ChatFlowLayout : UICollectionViewFlowLayout
{
    // Error parsing type: , name: largeCornerRadius
    // Error parsing type: , name: smallCornerRadius
    // Error parsing type: , name: maskPaths
    // Error parsing type: , name: delegate
    // Error parsing type: , name: dataVM
    // Error parsing type: , name: verticalInterItemSpacing
    // Error parsing type: , name: topGradientColor
    // Error parsing type: , name: bottomGradientColor
}

+ (Class)layoutAttributesClass;
- (CDUnknownBlockType).cxx_destruct;
- (id)initWithCoder:(id)arg1;
- (id)init;
- (void)invalidateLayoutWithContext:(id)arg1;
- (_Bool)shouldInvalidateLayoutForBoundsChange:(struct CGRect)arg1;
- (id)layoutAttributesForElementsInRect:(struct CGRect)arg1;
@property(nonatomic, readonly) struct CGSize collectionViewContentSize;

@end

