//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

@class UIButton;

@interface _TtC6Tinder24PhotoRemovedDialogFooter : UIView
{
    // Error parsing type: , name: actionButton
}

+ (_Bool)requiresConstraintBasedLayout;
+ (_Bool)isCompactScreen;
- (CDUnknownBlockType).cxx_destruct;
- (id)initWithCoder:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;
@property(nonatomic, readonly) UIButton *actionButton; // @synthesize actionButton;

@end

