//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIButton.h>

@class UIColor;

@interface _TtC6Tinder6Button : UIButton
{
    // Error parsing type: , name: cornerRadius
    // Error parsing type: , name: borderWidth
    // Error parsing type: , name: borderColor
    // Error parsing type: , name: shadowOpacity
    // Error parsing type: , name: shadowRadius
    // Error parsing type: , name: shadowColor
    // Error parsing type: , name: shadowOffset
}

- (CDUnknownBlockType).cxx_destruct;
- (id)initWithCoder:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;
@property(nonatomic) struct CGSize shadowOffset; // @synthesize shadowOffset;
@property(nonatomic, retain) UIColor *shadowColor; // @synthesize shadowColor;
@property(nonatomic) double shadowRadius; // @synthesize shadowRadius;
@property(nonatomic) float shadowOpacity; // @synthesize shadowOpacity;
@property(nonatomic, retain) UIColor *borderColor; // @synthesize borderColor;
@property(nonatomic) double borderWidth; // @synthesize borderWidth;
@property(nonatomic) double cornerRadius; // @synthesize cornerRadius;

@end

