//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

@class NSDictionary, NSString, UIButton, UILabel;

@interface _TtC6Tinder20NominationButtonView : UIView
{
    // Error parsing type: , name: buttonHeight
    // Error parsing type: , name: nominationsRemaining
    // Error parsing type: , name: nominationFormat
    // Error parsing type: , name: delegate
    // Error parsing type: , name: inviteAttributes.storage
    // Error parsing type: , name: nominationAttributes.storage
    // Error parsing type: , name: inviteButton.storage
    // Error parsing type: , name: nominationLabel.storage
}

- (CDUnknownBlockType).cxx_destruct;
- (id)initWithFrame:(struct CGRect)arg1;
- (void)fadeOut;
- (void)fadeIn;
- (void)didTapInviteButton;
- (void)configureNominationLabel;
- (void)setupConstraints;
- (id)initWithCoder:(id)arg1;
@property(nonatomic, retain) UILabel *nominationLabel;
@property(nonatomic, retain) UIButton *inviteButton;
@property(nonatomic, copy) NSDictionary *nominationAttributes;
@property(nonatomic, copy) NSDictionary *inviteAttributes;
@property(nonatomic, readonly) NSString *nominationFormat; // @synthesize nominationFormat;
@property(nonatomic) long long nominationsRemaining; // @synthesize nominationsRemaining;
@property(nonatomic, readonly) double buttonHeight; // @synthesize buttonHeight;

@end

