//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

@interface _TtC6Tinder11ChatBoxView : UIView
{
    // Error parsing type: , name: topLineView
    // Error parsing type: , name: accessoryView
    // Error parsing type: , name: inputBoxView
    // Error parsing type: , name: collapsedVerticalConstraints.storage
    // Error parsing type: , name: expandedVerticalConstraints.storage
    // Error parsing type: , name: views.storage
    // Error parsing type: , name: delegate
    // Error parsing type: , name: initialInputState
    // Error parsing type: , name: initialSearchingState
    // Error parsing type: , name: inputState
    // Error parsing type: , name: searchingState
    // Error parsing type: , name: isSearching
}

- (CDUnknownBlockType).cxx_destruct;
- (id)initWithFrame:(struct CGRect)arg1;
- (void)resetToInitialState;
- (id)initWithCoder:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1 accessoryView:(id)arg2;

@end

