//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSUserDefaults, TNDRAnalyticsTracker;

@interface _TtC6Tinder15LeanplumService : NSObject
{
    // Error parsing type: , name: userDefaults.storage
    // Error parsing type: , name: analyticsTracker.storage
    // Error parsing type: , name: variables
}

+ (id)shared;
+ (id)dateSinceTrackAllVariantsKey;
+ (id)cachedVariantsKey;
- (CDUnknownBlockType).cxx_destruct;
- (void)readVariables;
- (id)stringForKey:(long long)arg1;
- (long long)integerForKey:(long long)arg1;
- (_Bool)boolForKey:(long long)arg1;
- (void)setUserID:(id)arg1;
- (void)start;
- (id)init;
@property(nonatomic, retain) TNDRAnalyticsTracker *analyticsTracker;
@property(nonatomic, retain) NSUserDefaults *userDefaults;

@end

