//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "_TtC6Tinder16HomeUserInfoView.h"

@interface _TtC6Tinder16HomeUserInfoView (Tinder1)
- (void)animateInSelectIfNeeded;
- (void)completeDismissFromProfile;
- (void)prepareForDismissFromProfile;
@end

