//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class TNDRHTTPClient;

@interface _TtC6Tinder21LikeMessageInteractor : NSObject
{
    // Error parsing type: , name: appContext.storage
}

- (CDUnknownBlockType).cxx_destruct;
- (id)init;
- (void)handleLikeButtonTappedWithMessageID:(id)arg1 didLike:(_Bool)arg2 messageIndex:(long long)arg3;
@property(nonatomic, readonly) TNDRHTTPClient *httpClient;

@end

