//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

@class UIImageView, UILabel;

@interface _TtC6Tinder24PhotoRemovedDialogHeader : UIView
{
    // Error parsing type: , name: contentView
    // Error parsing type: , name: photoRemovedIconImageView
    // Error parsing type: , name: titleLabel
    // Error parsing type: , name: detailLabel
}

+ (_Bool)requiresConstraintBasedLayout;
+ (_Bool)isCompactScreen;
- (CDUnknownBlockType).cxx_destruct;
- (id)initWithCoder:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;
@property(nonatomic, readonly) UILabel *detailLabel; // @synthesize detailLabel;
@property(nonatomic, readonly) UILabel *titleLabel; // @synthesize titleLabel;
@property(nonatomic, readonly) UIImageView *photoRemovedIconImageView; // @synthesize photoRemovedIconImageView;
@property(nonatomic, readonly) UIView *contentView; // @synthesize contentView;

@end

