//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class UIViewController;

@interface _TtC6Tinder29GroupProfilePreviewInteractor : NSObject
{
    // Error parsing type: , name: interactionViewController
    // Error parsing type: , name: urlManager
    // Error parsing type: , name: cardView
    // Error parsing type: , name: profileAnimationController.storage
}

- (CDUnknownBlockType).cxx_destruct;
- (id)init;
@property(nonatomic) __weak UIViewController *interactionViewController; // @synthesize interactionViewController;

@end

