//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class TNDRGoogleDFPExperiment, _TtC6Tinder13FANExperiment;

@interface _TtC6Tinder12FANAdContext : NSObject
{
    // Error parsing type: , name: googleDFPExperiment.storage
    // Error parsing type: , name: fanExperiment.storage
    // Error parsing type: , name: analytics.storage
    // Error parsing type: , name: fetchCompletion
    // Error parsing type: , name: pendingNativeAd
    // Error parsing type: , name: currentAd
    // Error parsing type: , name: browseTimer
}

- (CDUnknownBlockType).cxx_destruct;
- (id)init;
@property(nonatomic, readonly) _Bool enabled;
@property(nonatomic, retain) _TtC6Tinder13FANExperiment *fanExperiment;
@property(nonatomic, retain) TNDRGoogleDFPExperiment *googleDFPExperiment;

@end

