//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "_TtC6Tinder12AdInteractor.h"

#import "TNDRAdWebViewControllerDelegate-Protocol.h"

@interface _TtC6Tinder12AdInteractor (Tinder1) <TNDRAdWebViewControllerDelegate>
- (void)adWebViewControllerDidDisappear:(id)arg1;
@end

