//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <swiftCore/SwiftObject.h>

@class NSString;

@interface _TtC6Tinder11ChatContext : SwiftObject
{
    // Error parsing type: , name: appContext
    // Error parsing type: , name: viewModel
    // Error parsing type: , name: noMessageDataProvider
    // Error parsing type: , name: muteMatchInteractor
    // Error parsing type: , name: likeMessageInteractor
    // Error parsing type: , name: markChatAsViewedInteractor
    // Error parsing type: , name: sendMessageInteractor.storage
    // Error parsing type: , name: sendGifInteractor.storage
    // Error parsing type: , name: chatAnalyticsClient.storage
    // Error parsing type: , name: reportUserInGroupMatchIndex
    // Error parsing type: , name: matchID
    // Error parsing type: , name: currentUserID
}

@property(nonatomic, readonly) NSString *matchID; // @synthesize matchID;

@end

