//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "_TtC6Tinder20MessageStandardsView.h"

@class NSArray, UILabel, UIView, _TtC6Tinder10SliderView, _TtC6Tinder27MaleMessageStandardItemView;

@interface _TtC6Tinder23MaleMessageStandardView : _TtC6Tinder20MessageStandardsView
{
    // Error parsing type: , name: headerLabel
    // Error parsing type: , name: subtitleLabel
    // Error parsing type: , name: itemView1
    // Error parsing type: , name: itemView2
    // Error parsing type: , name: itemView3
    // Error parsing type: , name: separatorView1
    // Error parsing type: , name: separatorView2
    // Error parsing type: , name: sliderView
    // Error parsing type: , name: isAnimating
}

- (CDUnknownBlockType).cxx_destruct;
- (void)transitionAnimationWithPresenting:(_Bool)arg1;
- (void)hideViews;
- (void)layoutSubviews;
- (void)setupAutolayout;
- (id)initWithCoder:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;
@property(nonatomic) _Bool isAnimating; // @synthesize isAnimating;
@property(nonatomic, readonly) _TtC6Tinder10SliderView *sliderView; // @synthesize sliderView;
@property(nonatomic, readonly) UIView *separatorView2; // @synthesize separatorView2;
@property(nonatomic, readonly) UIView *separatorView1; // @synthesize separatorView1;
@property(nonatomic, readonly) NSArray *itemViews;
@property(nonatomic, readonly) _TtC6Tinder27MaleMessageStandardItemView *itemView3; // @synthesize itemView3;
@property(nonatomic, readonly) _TtC6Tinder27MaleMessageStandardItemView *itemView2; // @synthesize itemView2;
@property(nonatomic, readonly) _TtC6Tinder27MaleMessageStandardItemView *itemView1; // @synthesize itemView1;
@property(nonatomic, readonly) UILabel *subtitleLabel; // @synthesize subtitleLabel;
@property(nonatomic, readonly) UILabel *headerLabel; // @synthesize headerLabel;

@end

