//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "TNDRTitleDialogHeader.h"

@class UIView;

@interface _TtC6Tinder18ReportDialogHeader : TNDRTitleDialogHeader
{
    // Error parsing type: , name: separatorLine
}

+ (_Bool)isCompactScreen;
- (CDUnknownBlockType).cxx_destruct;
- (id)initWithTitleText:(id)arg1 detailText:(id)arg2 view:(id)arg3 desiredViewHeight:(double)arg4 titleBelowImage:(_Bool)arg5;
- (id)initWithTitleText:(id)arg1 detailText:(id)arg2 image:(id)arg3 desiredImageWidth:(double)arg4 titleBelowImage:(_Bool)arg5;
- (id)initWithTitleText:(id)arg1 detailText:(id)arg2 image:(id)arg3 marketingText:(id)arg4 marketingImage:(id)arg5;
- (id)initWithTitleText:(id)arg1 detailText:(id)arg2 image:(id)arg3 titleBelowImage:(_Bool)arg4;
- (id)initWithTitleText:(id)arg1 detailText:(id)arg2 image:(id)arg3;
- (void)setupAutolayout;
- (id)initWithTitleText:(id)arg1 detailText:(id)arg2;
@property(nonatomic, readonly) UIView *separatorLine; // @synthesize separatorLine;

@end

