//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "_TtC6Tinder12DFPAdContext.h"

#import "GADAppEventDelegate-Protocol.h"

@interface _TtC6Tinder12DFPAdContext (Tinder1) <GADAppEventDelegate>
- (void)adView:(id)arg1 didReceiveAppEvent:(id)arg2 withInfo:(id)arg3;
@end

