//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

@class NSString, UIImage;

@protocol _TtP6Tinder19PushPermissionsView_
- (void)configureWith:(NSString *)arg1 detailText:(NSString *)arg2 actionText:(NSString *)arg3 cancelText:(NSString *)arg4 image:(UIImage *)arg5;
@end

