//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

@protocol _TtP6Tinder24HomeMerchandisingPaywall_;

@protocol _TtP6Tinder36HomeMerchandisingConsumableViewModel_
@property(nonatomic, readonly) id <_TtP6Tinder24HomeMerchandisingPaywall_> paywallDelegate;
@property(nonatomic, readonly) double timeIntervalRemaining;
@property(nonatomic, readonly) long long remaining;
@property(nonatomic, readonly) long long type;
@end

