//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "NSObject-Protocol.h"

@class AKFConfirmationCodeViewController, NSString;

@protocol AKFConfirmationCodeViewControllerDelegate <NSObject>
- (void)confirmationCodeViewControllerDidCancel:(AKFConfirmationCodeViewController *)arg1;
- (void)confirmationCodeViewControllerDidRetry:(AKFConfirmationCodeViewController *)arg1;
- (void)confirmationCodeViewController:(AKFConfirmationCodeViewController *)arg1 didCompleteWithConfirmationCode:(NSString *)arg2;
@end

