//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "AKFContentViewController.h"

@class AKFButton, AKFPhoneNumber, NSDate, NSTimer, UITextView;
@protocol AKFPhoneResendCodeViewControllerDelegate;

@interface AKFPhoneResendCodeViewController : AKFContentViewController
{
    AKFButton *_resendSMSButton;
    AKFButton *_sendToFacebookButton;
    UITextView *_instructionView;
    UITextView *_resendSMSCheckView;
    AKFButton *_editPhoneNumberButton;
    NSTimer *_resendButtonTimer;
    _Bool _enableSendToFacebook;
    id <AKFPhoneResendCodeViewControllerDelegate> _delegate;
    NSDate *_lastPhoneRequestStartDate;
    AKFPhoneNumber *_lastPhoneNumber;
    double _minResendInterval;
}

@property(nonatomic) _Bool enableSendToFacebook; // @synthesize enableSendToFacebook=_enableSendToFacebook;
@property(nonatomic) double minResendInterval; // @synthesize minResendInterval=_minResendInterval;
@property(copy, nonatomic) AKFPhoneNumber *lastPhoneNumber; // @synthesize lastPhoneNumber=_lastPhoneNumber;
@property(copy, nonatomic) NSDate *lastPhoneRequestStartDate; // @synthesize lastPhoneRequestStartDate=_lastPhoneRequestStartDate;
@property(nonatomic) __weak id <AKFPhoneResendCodeViewControllerDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)_editPhoneNumber:(id)arg1;
- (void)_sendToFacebook:(id)arg1;
- (void)_resendSMS:(id)arg1;
- (void)_checkResendSMSButton;
- (void)applyTheme:(id)arg1;
- (void)addViewConstraints;
- (void)viewWillDisappear:(_Bool)arg1;
- (void)viewWillAppear:(_Bool)arg1;
- (void)viewDidLoad;
- (unsigned long long)loginFlowState;
- (id)appEventViewName;

@end

