//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "AKFConfiguring-Protocol.h"
#import "AKFUIManaging-Protocol.h"
#import "NSObject-Protocol.h"

@protocol AKFViewControllerDelegate;

@protocol AKFViewController <AKFUIManaging, NSObject, AKFConfiguring>
@property(nonatomic, readonly) unsigned long long loginType;
@property(nonatomic) __weak id <AKFViewControllerDelegate> delegate;
@end

