//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "FBAdImage.h"

@interface FBInstreamAdChoicesIcon : FBAdImage
{
}

- (id)initWithURL:(id)arg1 width:(long long)arg2 height:(long long)arg3;
- (id)init;

@end

