//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

@class NSError, NSObject;
@protocol OS_dispatch_queue;

@protocol FNFPlayerDisplayEngineDelegate
- (void)layerUpdatedWithError:(NSError *)arg1;
- (NSObject<OS_dispatch_queue> *)queueForLayerUpdates;
@end

