//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIButton.h>

@interface JLBBouncyButton : UIButton
{
}

- (void)reset:(id)arg1;
- (void)bounceBack:(id)arg1;
- (void)shrink:(id)arg1;
- (void)setupAnimationActions;
- (id)initWithFrame:(struct CGRect)arg1;

@end

