//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@interface LogSetup : NSObject
{
}

+ (void)setup;
+ (void)setUserID:(id)arg1;
+ (id)userID;
+ (void)setLogFilePath:(id)arg1;
+ (id)logFilePath;
- (CDUnknownBlockType).cxx_destruct;
- (id)init;

@end

