//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSArray.h>

@interface NSArray (Tinder)
- (id)tndr_filterWithBlock:(CDUnknownBlockType)arg1;
- (id)tndr_map:(CDUnknownBlockType)arg1;
- (long long)tndr_findFirstIndexWithBlock:(CDUnknownBlockType)arg1;
- (id)tndr_findFirstWithBlock:(CDUnknownBlockType)arg1;
- (id)tndr_safeArray;
- (id)stripNulls;
@end

