//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSAttributedString.h>

@interface NSAttributedString (TNDRAttributedString)
+ (id)tinderAttributesForUnderageDetailLink;
+ (id)tinderAttributesForUnderageDetailText;
+ (id)tinderAttributedStringForRateLimitWarningDialogHeaderDetailText:(id)arg1;
+ (id)tinderAttributesForRateLimitWarningDialogHeaderDetailText;
+ (id)tinderAttributedStringForRateLimitWarningDialogHeaderTitle:(id)arg1;
+ (id)tinderAttributesForRateLimitWarningDialogHeaderTitle;
+ (id)tinderAttributesForUnmatchDialogHeaderDetailText;
+ (id)tinderAttributesForUnmatchDialogHeaderTitle;
+ (id)tinderAttributedStringForReportingDialogHeaderDetailText:(id)arg1;
+ (id)tinderAttributesForReportingDialogHeaderDetailText;
+ (id)tinderAttributesForSuperLikeDialogHeaderDetailText;
+ (id)tinderAttributesForSuperLikeDialogHeaderTimeRemainingText;
+ (id)tinderAttributedStringForReportingDialogHeaderTitle:(id)arg1;
+ (id)tinderAttributesForSuperLikeDialogHeaderTitle;
+ (id)tinderAttributesForReportingDialogHeaderTitle;
+ (id)tinderAttributedStringForDialogFilledCustomTextFooterTitle:(id)arg1;
+ (id)tinderAttributesForDialogFilledCustomTextFooterTitle;
+ (id)tinderAttributedStringForDialogHeaderDetailText:(id)arg1;
+ (id)tinderAttributedStringForSuperLikeDialogHeaderTitle:(id)arg1;
+ (id)tinderAttributedStringForSuperLikeDialogTimeRemainingText:(id)arg1;
+ (id)tinderAttributedStringForSuperLikeDialogDetailText:(id)arg1;
+ (id)tinderAttributesForDialogHeaderDetailText;
+ (id)tinderAttributedStringForDialogHeaderTitle:(id)arg1;
+ (id)tinderAttributesForDialogHeaderTitle;
@end

