//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSDate.h>

@interface NSDate (Tinder)
+ (id)dateWithYearsAgoSinceNow:(long long)arg1;
+ (id)dateInCurrentTimeZone:(id)arg1;
+ (long long)currentAgeFromDate:(id)arg1;
- (id)obfuscatedBirthday;
- (id)toGlobalTime;
- (id)toLocalTime;
@end

