//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <CFNetwork/NSHTTPURLResponse.h>

@interface NSHTTPURLResponse (GADHeaderParser)
- (id)gad_dateFromHttpDateString:(id)arg1;
- (id)gad_expirationDate;
@end

