//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSLayoutConstraint.h>

@interface NSLayoutConstraint (Tinder)
+ (id)constraintsWithFormats:(id)arg1 views:(id)arg2 metrics:(id)arg3 options:(unsigned long long)arg4;
- (id)withPriority:(float)arg1;
- (id)required;
- (void)require;
@end

