//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSNotificationCenter.h>

@interface NSNotificationCenter (Tinder)
- (void)tndr_queueNotificationOnMain:(id)arg1 object:(id)arg2;
- (void)tndr_queueNotificationOnMain:(id)arg1;
- (void)tndr_queueNotificationOnMain:(id)arg1 object:(id)arg2 userInfo:(id)arg3;
- (void)tndr_postNotificationOnMain:(id)arg1 object:(id)arg2;
- (void)tndr_postNotificationOnMain:(id)arg1;
- (void)tndr_postNotificationOnMain:(id)arg1 object:(id)arg2 userInfo:(id)arg3;
@end

