//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSNull.h>

@interface NSNull (JSON)
- (id)tndr_encodeSpecialCharactersForSparks;
- (struct _NSRange)rangeOfCharacterFromSet:(id)arg1;
- (unsigned long long)length;
@end

