//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@interface NSObject (TNDRJSON)
- (id)tndr_castToDate;
- (id)tndr_castToNumber;
- (id)tndr_castToString;
- (id)tndr_castToArray;
- (id)tndr_castToDictionary;
@end

