//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSOperationQueue.h>

@interface NSOperationQueue (Tinder)
- (void)addAsyncOperationWithTargetQueue:(id)arg1 block:(CDUnknownBlockType)arg2;
- (void)addOperationWithTargetQueue:(id)arg1 block:(CDUnknownBlockType)arg2;
- (void)addAsyncOperationWithBlock:(CDUnknownBlockType)arg1;
@end

