//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSPredicate.h>

@interface NSPredicate (Tinder)
+ (id)tndr_StringForMatchesIDIn:(id)arg1;
+ (id)tndr_StringForUnviewedMatchesWithOrWithoutMessagesForGender:(int)arg1;
+ (id)tndr_StringForUnviewedMatchesWithMessages;
+ (id)tndr_StringForMatchesWithMessages;
+ (id)tndr_StringForUnviewedNewMatches;
+ (id)tndr_StringForNewMatches;
+ (id)tndr_listIDEqualTo:(id)arg1;
+ (id)tndr_currentGroups;
+ (id)tndr_messageIDIn:(id)arg1;
+ (id)tndr_popularLocations;
+ (id)tndr_cityNameBeginsWith:(id)arg1;
+ (id)tndr_filterNewMatchesSearchText:(id)arg1;
+ (id)tndr_filterMatchesMessagesSearchText:(id)arg1;
+ (id)tndr_locationLat:(id)arg1 Lon:(id)arg2;
+ (id)tndr_momentLikeMessages;
+ (id)tndr_nonnullAttribute:(id)arg1;
+ (id)tndr_messagesWithText:(id)arg1;
+ (id)tndr_messagesForMatchID:(id)arg1;
+ (id)tndr_messagesNotFromUserID:(id)arg1;
+ (id)tndr_messagesFromUserID:(id)arg1;
+ (id)tndr_messagesCreated:(id)arg1 text:(id)arg2 matchID:(id)arg3;
+ (id)tndr_usersEmptyID;
+ (id)tndr_usersEmptyFirstName;
+ (id)tndr_unviewedMessages;
+ (id)tndr_matchesForUserID:(id)arg1;
+ (id)tndr_matchIDMatchesMatchID:(id)arg1;
+ (id)tndr_matchesUnviewedMessages;
+ (id)tndr_watchMatches;
+ (id)tndr_allMatches;
+ (id)tndr_usersForUserID:(id)arg1;
+ (id)tndr_trimOrphanedRecommendationsPredicate;
+ (id)tndr_trimUnneededGroupsPredicate;
+ (id)tndr_trimUnneededUsersPredicate;
+ (id)tndr_orphanedPhotosPredicate;
+ (id)tndr_failedChoices;
+ (id)tndr_rewindableGroups;
+ (id)tndr_rewindableUsers;
+ (id)tndr_groupsToCountForStack;
+ (id)tndr_usersToCountForStack;
+ (id)tndr_groupsForGroupCardManager;
+ (id)tndr_usersForUserCardManager;
@end

