//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <PINCache/PINCache.h>

@interface PINCache (Tinder)
- (_Bool)tndr_isObjectInCacheForKey:(id)arg1;
- (void)tndr_cleanDisk;
@end

