//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "SPTCacheData-Protocol.h"

@class NSData, NSString, NSURL;

@interface SPTCacheData : NSObject <SPTCacheData>
{
    NSURL *URI;
    NSString *itemID;
    unsigned long long offset;
    unsigned long long totalSize;
    NSData *data;
}

@property(retain, nonatomic) NSData *data; // @synthesize data;
@property(nonatomic) unsigned long long totalSize; // @synthesize totalSize;
@property(nonatomic) unsigned long long offset; // @synthesize offset;
@property(retain, nonatomic) NSString *itemID; // @synthesize itemID;
@property(retain, nonatomic) NSURL *URI; // @synthesize URI;
- (void).cxx_destruct;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

