//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "SPTJSONObject-Protocol.h"

@class NSString;

@interface SPTJSONObjectBase : NSObject <SPTJSONObject>
{
    id _decodedJSONObject;
}

@property(copy, nonatomic) id decodedJSONObject; // @synthesize decodedJSONObject=_decodedJSONObject;
- (void).cxx_destruct;
- (id)initWithDecodedJSONObject:(id)arg1 error:(id *)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

