//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "SPTTrackProvider-Protocol.h"

@class NSArray, NSString, NSURL;

@interface SPTListPage : NSObject <SPTTrackProvider>
{
    _Bool _hasPartialChildren;
    unsigned long long _totalListLength;
    NSURL *_nextPageURL;
    NSURL *_previousPageURL;
    NSArray *_items;
    NSString *_rootObjectKey;
    struct _NSRange _range;
}

+ (id)listPageFromData:(id)arg1 withResponse:(id)arg2 error:(id *)arg3;
+ (id)listPageFromDecodedJSON:(id)arg1 expectingPartialChildren:(_Bool)arg2 rootObjectKey:(id)arg3 error:(id *)arg4;
+ (id)listPageFromData:(id)arg1 withResponse:(id)arg2 expectingPartialChildren:(_Bool)arg3 rootObjectKey:(id)arg4 error:(id *)arg5;
@property(copy, nonatomic) NSString *rootObjectKey; // @synthesize rootObjectKey=_rootObjectKey;
@property(nonatomic) _Bool hasPartialChildren; // @synthesize hasPartialChildren=_hasPartialChildren;
@property(copy, nonatomic) NSArray *items; // @synthesize items=_items;
@property(copy, nonatomic) NSURL *previousPageURL; // @synthesize previousPageURL=_previousPageURL;
@property(copy, nonatomic) NSURL *nextPageURL; // @synthesize nextPageURL=_nextPageURL;
@property(nonatomic) unsigned long long totalListLength; // @synthesize totalListLength=_totalListLength;
@property(nonatomic) struct _NSRange range; // @synthesize range=_range;
- (void).cxx_destruct;
- (id)playableUri;
- (id)tracksForPlayback;
- (void)requestPageAtURL:(id)arg1 accessToken:(id)arg2 callback:(CDUnknownBlockType)arg3;
- (id)createRequestForPreviousPageWithAccessToken:(id)arg1 error:(id *)arg2;
- (id)createRequestForNextPageWithAccessToken:(id)arg1 error:(id *)arg2;
- (void)requestPageAtURL:(id)arg1 session:(id)arg2 callback:(CDUnknownBlockType)arg3;
- (void)requestPreviousPageWithAccessToken:(id)arg1 callback:(CDUnknownBlockType)arg2;
- (void)requestNextPageWithAccessToken:(id)arg1 callback:(CDUnknownBlockType)arg2;
- (void)requestPreviousPageWithSession:(id)arg1 callback:(CDUnknownBlockType)arg2;
- (void)requestNextPageWithSession:(id)arg1 callback:(CDUnknownBlockType)arg2;
- (id)pageByAppendingPage:(id)arg1;
@property(readonly, nonatomic) _Bool isComplete;
@property(readonly, nonatomic) _Bool hasPreviousPage;
@property(readonly, nonatomic) _Bool hasNextPage;
@property(readonly, copy) NSString *description;
- (id)initWithDecodedJSONObject:(id)arg1 expectingPartialChildren:(_Bool)arg2 rootObjectKey:(id)arg3;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

