//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "SPTPartialPlaylist.h"

#import "SPTJSONObject-Protocol.h"

@class NSString, SPTListPage;

@interface SPTPlaylistSnapshot : SPTPartialPlaylist <SPTJSONObject>
{
    SPTListPage *_firstTrackPage;
    NSString *_snapshotId;
    long long _followerCount;
    NSString *_descriptionText;
}

+ (void)requestStarredListForUser:(id)arg1 withAccessToken:(id)arg2 callback:(CDUnknownBlockType)arg3;
+ (void)requestStarredListForUserWithSession:(id)arg1 callback:(CDUnknownBlockType)arg2;
+ (id)createRequestForRemovingTracksWithPositions:(id)arg1 fromPlaylist:(id)arg2 withAccessToken:(id)arg3 snapshot:(id)arg4 error:(id *)arg5;
+ (id)createRequestForRemovingTracks:(id)arg1 fromPlaylist:(id)arg2 withAccessToken:(id)arg3 snapshot:(id)arg4 error:(id *)arg5;
+ (id)createRequestForSettingTracks:(id)arg1 inPlaylist:(id)arg2 withAccessToken:(id)arg3 error:(id *)arg4;
+ (id)createRequestForChangingDetails:(id)arg1 inPlaylist:(id)arg2 withAccessToken:(id)arg3 error:(id *)arg4;
+ (id)createRequestForAddingTracks:(id)arg1 toPlaylist:(id)arg2 withAccessToken:(id)arg3 error:(id *)arg4;
+ (id)createRequestForAddingTracks:(id)arg1 atPosition:(int)arg2 toPlaylist:(id)arg3 withAccessToken:(id)arg4 error:(id *)arg5;
+ (_Bool)isStarredURI:(id)arg1;
+ (_Bool)isPlaylistURI:(id)arg1;
+ (void)playlistsWithURIs:(id)arg1 session:(id)arg2 callback:(CDUnknownBlockType)arg3;
+ (void)playlistsWithURIs:(id)arg1 accessToken:(id)arg2 callback:(CDUnknownBlockType)arg3;
+ (void)playlistWithURI:(id)arg1 session:(id)arg2 callback:(CDUnknownBlockType)arg3;
+ (void)playlistWithURI:(id)arg1 accessToken:(id)arg2 callback:(CDUnknownBlockType)arg3;
+ (id)createRequestForPlaylistWithURI:(id)arg1 accessToken:(id)arg2 error:(id *)arg3;
+ (id)playlistSnapshotFromDecodedJSON:(id)arg1 error:(id *)arg2;
+ (id)playlistSnapshotFromData:(id)arg1 withResponse:(id)arg2 error:(id *)arg3;
+ (void)load;
@property(copy, nonatomic) NSString *descriptionText; // @synthesize descriptionText=_descriptionText;
@property(nonatomic) long long followerCount; // @synthesize followerCount=_followerCount;
@property(copy, nonatomic) NSString *snapshotId; // @synthesize snapshotId=_snapshotId;
@property(retain, nonatomic) SPTListPage *firstTrackPage; // @synthesize firstTrackPage=_firstTrackPage;
- (void).cxx_destruct;
- (void)removeTracksWithPositionsFromPlaylist:(id)arg1 withSession:(id)arg2 callback:(CDUnknownBlockType)arg3;
- (void)removeTracksWithPositionsFromPlaylist:(id)arg1 withAccessToken:(id)arg2 callback:(CDUnknownBlockType)arg3;
- (void)removeTracksFromPlaylist:(id)arg1 withAccessToken:(id)arg2 callback:(CDUnknownBlockType)arg3;
- (void)removeTracksFromPlaylist:(id)arg1 withSession:(id)arg2 callback:(CDUnknownBlockType)arg3;
- (void)replaceTracksInPlaylist:(id)arg1 withSession:(id)arg2 callback:(CDUnknownBlockType)arg3;
- (void)replaceTracksInPlaylist:(id)arg1 withAccesstoken:(id)arg2 callback:(CDUnknownBlockType)arg3;
- (void)replaceTracksInPlaylist:(id)arg1 withAccessToken:(id)arg2 callback:(CDUnknownBlockType)arg3;
- (void)changePlaylistDetails:(id)arg1 withSession:(id)arg2 callback:(CDUnknownBlockType)arg3;
- (void)changePlaylistDetails:(id)arg1 withAccessToken:(id)arg2 callback:(CDUnknownBlockType)arg3;
- (void)addTracksWithPositionToPlaylist:(id)arg1 withPosition:(int)arg2 withAccessToken:(id)arg3 callback:(CDUnknownBlockType)arg4;
- (void)addTracksWithPositionToPlaylist:(id)arg1 withPosition:(int)arg2 withSession:(id)arg3 callback:(CDUnknownBlockType)arg4;
- (void)addTracksWithPositionToPlaylist:(id)arg1 withPosition:(int)arg2 session:(id)arg3 callback:(CDUnknownBlockType)arg4;
- (void)addTracksWithPositionToPlaylist:(id)arg1 withPosition:(int)arg2 accessToken:(id)arg3 callback:(CDUnknownBlockType)arg4;
- (void)addTracksToPlaylist:(id)arg1 withAccessToken:(id)arg2 callback:(CDUnknownBlockType)arg3;
- (void)addTracksToPlaylist:(id)arg1 withSession:(id)arg2 callback:(CDUnknownBlockType)arg3;
- (id)tracksForPlayback;
- (id)initWithDecodedJSONObject:(id)arg1 error:(id *)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy, nonatomic) id decodedJSONObject;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

