//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "TNDRReportAnalyticsClient-Protocol.h"

@protocol TNDRReportGroupAnalyticsClient <TNDRReportAnalyticsClient>
- (void)sendSelectGroupMemberReportMemberTappedAnalyticsEventWithPosition:(long long)arg1;
- (void)sendSelectGroupMemberReportBackgroundTappedAnalyticsEvent;
- (void)sendSelectGroupMemberReportCancelTappedAnalyticsEvent;
@end

