//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSArray, NSNotificationCenter, TNDRAnalyticsTracker, TNDRCoreDataService, TNDRCurrentUser, TNDRGamepadView, TNDRTutorialToolTip, UIView;
@protocol TNDRGamepadContextDelegate, TNDRGamepadViewDelegate;

@interface TNDRGamepadContext : NSObject
{
    // Error parsing type: , name: dataService.storage
    // Error parsing type: , name: currentUser.storage
    // Error parsing type: , name: shouldAnimateBoostButton
    // Error parsing type: , name: hasUpdatedGamepadAtLeastOnce
    // Error parsing type: , name: buttonContainer
    // Error parsing type: , name: type
    // Error parsing type: , name: parentView
    // Error parsing type: , name: siblingView
    // Error parsing type: , name: gamepadDelegate
    // Error parsing type: , name: contextDelegate
    // Error parsing type: , name: notificationCenter
    // Error parsing type: , name: analyticsTracker
    // Error parsing type: , name: tooltip
}

- (CDUnknownBlockType).cxx_destruct;
- (id)init;
- (id)initWithGamepadType:(unsigned long long)arg1 insideView:(id)arg2 placeAboveView:(id)arg3 gamepadDelegate:(id)arg4 contextDelegate:(id)arg5;
@property(nonatomic) _Bool pseudoEnableRewindButton;
@property(nonatomic) _Bool superLikeButtonEnabled;
@property(nonatomic) _Bool rewindButtonEnabled;
@property(nonatomic) _Bool passButtonEnabled;
@property(nonatomic) _Bool likeButtonEnabled;
@property(nonatomic, retain) TNDRTutorialToolTip *tooltip; // @synthesize tooltip;
@property(nonatomic, readonly) TNDRAnalyticsTracker *analyticsTracker; // @synthesize analyticsTracker;
@property(nonatomic, readonly) NSNotificationCenter *notificationCenter; // @synthesize notificationCenter;
@property(nonatomic) __weak id <TNDRGamepadContextDelegate> contextDelegate; // @synthesize contextDelegate;
@property(nonatomic) __weak id <TNDRGamepadViewDelegate> gamepadDelegate; // @synthesize gamepadDelegate;
@property(nonatomic, retain) UIView *siblingView; // @synthesize siblingView;
@property(nonatomic, retain) UIView *parentView; // @synthesize parentView;
@property(nonatomic) unsigned long long type; // @synthesize type;
@property(nonatomic, retain) TNDRGamepadView *buttonContainer; // @synthesize buttonContainer;
@property(nonatomic) _Bool hasUpdatedGamepadAtLeastOnce; // @synthesize hasUpdatedGamepadAtLeastOnce;
@property(nonatomic, readonly) NSArray *groupMembers;
@property(nonatomic, retain) TNDRCurrentUser *currentUser;
@property(nonatomic, retain) TNDRCoreDataService *dataService;
- (void)enableBoostButtonAnimation;
- (void)handleTransitionToBoostGamepadComplete:(id)arg1;
- (void)handleTransitionToIntermediateBoostGamepad:(id)arg1;
- (id)boostBoltIcon;
- (void)setupTooltipWithDefaultPropertiesWithTooltip:(id)arg1;
- (_Bool)unableToShowBoostTooltip;
- (_Bool)showBoostStartTooltip;
- (_Bool)showBoostTooltip;

@end

