//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIViewController.h>

#import "TNDRRegionCodePickerDelegate-Protocol.h"
#import "UITextFieldDelegate-Protocol.h"

@class NSString, TNDRAnalyticsTracker, TNDRNumericTextField, TNDRPhoneNumberValidator, TNDRRegionCodePickerController, UIBarButtonItem, UIButton, UILabel;
@protocol TNDRSMSValidationEnterPhoneNumberViewControllerDelegate;

@interface TNDRSMSValidationEnterPhoneNumberViewController : UIViewController <UITextFieldDelegate, TNDRRegionCodePickerDelegate>
{
    id <TNDRSMSValidationEnterPhoneNumberViewControllerDelegate> _delegate;
    UILabel *_titleLabel;
    UILabel *_detailLabel;
    TNDRNumericTextField *_countryCodeField;
    TNDRNumericTextField *_phoneNumberTextField;
    UIButton *_requestCodeButton;
    TNDRRegionCodePickerController *_regionCodePickerController;
    NSString *_regionCode;
    TNDRPhoneNumberValidator *_phoneNumberValidator;
    UIBarButtonItem *_backBarButtonItem;
}

@property(retain, nonatomic) UIBarButtonItem *backBarButtonItem; // @synthesize backBarButtonItem=_backBarButtonItem;
@property(retain, nonatomic) TNDRPhoneNumberValidator *phoneNumberValidator; // @synthesize phoneNumberValidator=_phoneNumberValidator;
@property(copy, nonatomic) NSString *regionCode; // @synthesize regionCode=_regionCode;
@property(retain, nonatomic) TNDRRegionCodePickerController *regionCodePickerController; // @synthesize regionCodePickerController=_regionCodePickerController;
@property(retain, nonatomic) UIButton *requestCodeButton; // @synthesize requestCodeButton=_requestCodeButton;
@property(retain, nonatomic) TNDRNumericTextField *phoneNumberTextField; // @synthesize phoneNumberTextField=_phoneNumberTextField;
@property(retain, nonatomic) TNDRNumericTextField *countryCodeField; // @synthesize countryCodeField=_countryCodeField;
@property(retain, nonatomic) UILabel *detailLabel; // @synthesize detailLabel=_detailLabel;
@property(retain, nonatomic) UILabel *titleLabel; // @synthesize titleLabel=_titleLabel;
@property(nonatomic) __weak id <TNDRSMSValidationEnterPhoneNumberViewControllerDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (_Bool)textFieldShouldReturn:(id)arg1;
- (_Bool)textField:(id)arg1 shouldChangeCharactersInRange:(struct _NSRange)arg2 replacementString:(id)arg3;
- (void)textFieldDidBeginEditing:(id)arg1;
- (void)updateCurrentLocale;
- (void)didChooseRegion:(id)arg1 andRegionCode:(id)arg2;
- (void)didTapBackBarButtonItem:(id)arg1;
- (void)didTapRequestCodeButton:(id)arg1;
- (void)updateValidationUI;
- (void)viewWillDisappear:(_Bool)arg1;
- (void)viewDidAppear:(_Bool)arg1;
- (void)viewWillAppear:(_Bool)arg1;
- (void)setupConstraints;
- (void)addSubviews;
- (void)viewDidLoad;
@property(readonly, copy, nonatomic) NSString *phoneNumber;
- (double)inputFontSize;
@property(readonly, nonatomic) _Bool isShortScreen;
@property(readonly, nonatomic) TNDRAnalyticsTracker *analyticsTracker;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

