//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "TNDRExperiment.h"

@class NSString, TNDRGoogleDFPExperimentVariableAdSwipeIntervalCount, TNDRGoogleDFPExperimentVariableAdUnitIDString, TNDRGoogleDFPExperimentVariableFeatureEnabled;

@interface TNDRGoogleDFPExperiment : TNDRExperiment
{
    TNDRGoogleDFPExperimentVariableFeatureEnabled *_googleDFPFeatureEnabled;
    TNDRGoogleDFPExperimentVariableAdSwipeIntervalCount *_googleDFPAdSwipeIntervalCount;
    TNDRGoogleDFPExperimentVariableAdUnitIDString *_googleDFPAdUnitIDString;
}

@property(retain, nonatomic) TNDRGoogleDFPExperimentVariableAdUnitIDString *googleDFPAdUnitIDString; // @synthesize googleDFPAdUnitIDString=_googleDFPAdUnitIDString;
@property(retain, nonatomic) TNDRGoogleDFPExperimentVariableAdSwipeIntervalCount *googleDFPAdSwipeIntervalCount; // @synthesize googleDFPAdSwipeIntervalCount=_googleDFPAdSwipeIntervalCount;
@property(retain, nonatomic) TNDRGoogleDFPExperimentVariableFeatureEnabled *googleDFPFeatureEnabled; // @synthesize googleDFPFeatureEnabled=_googleDFPFeatureEnabled;
- (void).cxx_destruct;
- (id)allExperimentVariables;
- (id)name;
@property(readonly, nonatomic) NSString *adUnitIDString;
@property(readonly, nonatomic) long long adSwipeIntervalCount;
@property(readonly, nonatomic) _Bool isGoogleDFPEnabled;

@end

