//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "TNDRExperiment.h"

@class TNDRProfileV2ExperimentVariable;

@interface TNDRProfileV2Experiment : TNDRExperiment
{
    TNDRProfileV2ExperimentVariable *_profileV2Enabled;
}

@property(retain, nonatomic) TNDRProfileV2ExperimentVariable *profileV2Enabled; // @synthesize profileV2Enabled=_profileV2Enabled;
- (void).cxx_destruct;
- (id)allExperimentVariables;
- (id)name;
@property(readonly, nonatomic) _Bool isProfileV2Enabled;

@end

