//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSArray, TNDRCurrentUser, TNDRProductsManager;

@interface TNDRPurchaseLogger : NSObject
{
    // Error parsing type: , name: events.storage
    // Error parsing type: , name: reachability.storage
    // Error parsing type: , name: timer
    // Error parsing type: , name: isNewPurchaseFlow
    // Error parsing type: , name: startDateProvider.storage
    // Error parsing type: , name: environmentHelper
    // Error parsing type: , name: productsRequester
    // Error parsing type: , name: currentUser.storage
    // Error parsing type: , name: productsManager.storage
    // Error parsing type: , name: spkTracker
    // Error parsing type: , name: analyticsTracker
    // Error parsing type: , name: experimentCoordinator
    // Error parsing type: , name: sendFrequency
    // Error parsing type: , name: archiveFrequency
    // Error parsing type: , name: maxBatchSize
    // Error parsing type: , name: serialQueue
    // Error parsing type: , name: taskID
}

+ (id)testingArchiveFilename;
+ (id)defaultArchiveFilename;
+ (id)shared;
+ (id)restoreErrorDomain;
- (CDUnknownBlockType).cxx_destruct;
- (void)dealloc;
- (id)init;
@property(nonatomic, retain) TNDRProductsManager *productsManager;
@property(nonatomic, retain) TNDRCurrentUser *currentUser;
@property(nonatomic, readonly) NSArray *currentEvents;

@end

