//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

@class TNDRActionSheet;

@protocol TNDRActionSheetDelegate
- (void)actionSheet:(TNDRActionSheet *)arg1 triggeredButtonWithID:(long long)arg2;

@optional
- (void)actionSheetBackgroundTapped:(TNDRActionSheet *)arg1;
@end

