//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@interface TNDRUITestSetup : NSObject
{
}

+ (_Bool)isGoingOutUITest;
+ (_Bool)isDisableEducationAlert;
+ (_Bool)isTestingOnboarding;
+ (_Bool)isTestingAuth;
+ (_Bool)isUITesting;
+ (id)UUIDForUITests;
+ (id)sharedSetup;
- (void)avoidLikePassAlerts;
- (void)setup;
- (id)init;

@end

