//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

@class CAShapeLayer, UIActivityIndicatorView, UIImage, UIImageView;

@interface TNDRPausePlayView : UIView
{
    unsigned long long _state;
    double _percentage;
    CAShapeLayer *_circleLayerOutline;
    CAShapeLayer *_circleLayer;
    UIImageView *_imageView;
    UIImage *_playImage;
    UIImage *_stopImage;
    UIActivityIndicatorView *_activityIndicatorView;
}

@property(retain, nonatomic) UIActivityIndicatorView *activityIndicatorView; // @synthesize activityIndicatorView=_activityIndicatorView;
@property(retain, nonatomic) UIImage *stopImage; // @synthesize stopImage=_stopImage;
@property(retain, nonatomic) UIImage *playImage; // @synthesize playImage=_playImage;
@property(retain, nonatomic) UIImageView *imageView; // @synthesize imageView=_imageView;
@property(retain, nonatomic) CAShapeLayer *circleLayer; // @synthesize circleLayer=_circleLayer;
@property(retain, nonatomic) CAShapeLayer *circleLayerOutline; // @synthesize circleLayerOutline=_circleLayerOutline;
@property(nonatomic) double percentage; // @synthesize percentage=_percentage;
@property(nonatomic) unsigned long long state; // @synthesize state=_state;
- (void).cxx_destruct;
- (void)setState:(unsigned long long)arg1 animated:(_Bool)arg2;
- (void)layoutImageFrame;
- (void)layoutSubviews;
- (id)initWithFrame:(struct CGRect)arg1;

@end

