//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@interface TNDRGoingOutStatusAttributes : NSObject
{
}

+ (id)text;
+ (id)tag;
+ (id)sourceID;
+ (id)source;
+ (id)serviceID;
+ (id)longitude;
+ (id)locationName;
+ (id)locationID;
+ (id)latitude;
+ (id)expirationDate;
+ (id)emoji;
+ (id)creationDate;

@end

