//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIViewController.h>

#import "TNDRPassportMapSearchViewControllerDelegate-Protocol.h"
#import "TNDRPassportPaywallDelegate-Protocol.h"
#import "TNDRURLNavigableProtocol-Protocol.h"

@class CLLocation, MKPlacemark, NSString, NSURLSessionDataTask, TNDRPassportStackContainerView;
@protocol UIViewControllerAnimatedTransitioning;

@interface TNDRPassportMapStackContainerViewController : UIViewController <TNDRPassportMapSearchViewControllerDelegate, TNDRPassportPaywallDelegate, TNDRURLNavigableProtocol>
{
    TNDRPassportStackContainerView *_containerView;
    CLLocation *_selectedLocation;
    MKPlacemark *_selectedPlacemark;
    NSURLSessionDataTask *_queuedTravelDataTask;
}

+ (id)viewControllerNavigationKey;
@property(retain, nonatomic) NSURLSessionDataTask *queuedTravelDataTask; // @synthesize queuedTravelDataTask=_queuedTravelDataTask;
@property(retain, nonatomic) MKPlacemark *selectedPlacemark; // @synthesize selectedPlacemark=_selectedPlacemark;
@property(retain, nonatomic) CLLocation *selectedLocation; // @synthesize selectedLocation=_selectedLocation;
@property(retain, nonatomic) TNDRPassportStackContainerView *containerView; // @synthesize containerView=_containerView;
- (void).cxx_destruct;
- (void)didSelectLocationToTravelTo:(id)arg1 placemark:(id)arg2 predeterminedTitle:(id)arg3 predeterminedDescription:(id)arg4 completion:(CDUnknownBlockType)arg5;
- (void)didSelectToStopTravelingCompletion:(CDUnknownBlockType)arg1;
- (void)didSelectToCloseMapView;
- (void)willEndSearching;
- (void)didStartSearching;
- (void)viewDidLoad;

// Remaining properties
@property(readonly, nonatomic) id <UIViewControllerAnimatedTransitioning> animationController;
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

