//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@interface TNDRMatchAnalyticsClient : NSObject
{
    // Error parsing type: , name: delegate
    // Error parsing type: , name: analyticsTracker
}

- (CDUnknownBlockType).cxx_destruct;
- (id)init;
- (id)initWithDelegate:(id)arg1 analyticsTracker:(id)arg2;

@end

