//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSArray, NSString, TNDRCurrentUser, TNDRCustomGenderExperiment, TNDREditGenderViewModel;

@interface TNDRGenderSearchViewModel : NSObject
{
    NSArray *_genders;
    TNDREditGenderViewModel *_editGenderViewModel;
}

@property(retain, nonatomic) TNDREditGenderViewModel *editGenderViewModel; // @synthesize editGenderViewModel=_editGenderViewModel;
@property(retain, nonatomic) NSArray *genders; // @synthesize genders=_genders;
- (void).cxx_destruct;
- (void)updateCustomGender:(id)arg1 completion:(CDUnknownBlockType)arg2;
- (id)gendersMatchingText:(id)arg1;
- (_Bool)isValidGender:(id)arg1;
@property(readonly, copy, nonatomic) NSString *customGenderForCurrentUser;
@property(readonly, nonatomic) TNDRCustomGenderExperiment *genderExperiment;
@property(readonly, nonatomic) TNDRCurrentUser *currentUser;

@end

