//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

@class TNDRMatchesGoingOutExperiment, UILabel;

@interface TNDRGoingOutBannerTinderView : UIView
{
    _Bool _expanded;
    _Bool _animating;
    UILabel *_textLabel;
    UILabel *_statusLabel;
    UIView *_borderView;
    UIView *_labelsContainer;
    UILabel *_label1;
    UILabel *_label2;
    UILabel *_label3;
}

@property(retain, nonatomic) UILabel *label3; // @synthesize label3=_label3;
@property(retain, nonatomic) UILabel *label2; // @synthesize label2=_label2;
@property(retain, nonatomic) UILabel *label1; // @synthesize label1=_label1;
@property(retain, nonatomic) UIView *labelsContainer; // @synthesize labelsContainer=_labelsContainer;
@property(retain, nonatomic) UIView *borderView; // @synthesize borderView=_borderView;
@property(nonatomic, getter=isAnimating) _Bool animating; // @synthesize animating=_animating;
@property(retain, nonatomic) UILabel *statusLabel; // @synthesize statusLabel=_statusLabel;
@property(retain, nonatomic) UILabel *textLabel; // @synthesize textLabel=_textLabel;
@property(nonatomic, getter=isExpanded) _Bool expanded; // @synthesize expanded=_expanded;
- (void).cxx_destruct;
- (id)formattedTimeTextFromTime:(double)arg1;
- (double)totalLabelWidthWithoutTruncation;
- (double)maxAvailableHorizontalSpaceForText;
- (double)textWidth;
- (void)computeAndSetFramesForContainerLabelsExpanded:(_Bool)arg1;
- (void)setText:(id)arg1;
- (void)setExpanded:(_Bool)arg1 animated:(_Bool)arg2;
- (struct CGSize)sizeThatFits:(struct CGSize)arg1;
- (void)collapsedLayout;
- (void)expandedLayout;
- (void)layoutSubviews;
@property(readonly, nonatomic) TNDRMatchesGoingOutExperiment *matchesGoingOutExperiment;
- (id)initWithStatusEmoji:(id)arg1 statusText:(id)arg2 locationText:(id)arg3 timeText:(id)arg4;
- (id)initWithStatusEmoji:(id)arg1 statusText:(id)arg2 locationText:(id)arg3 timeLeft:(double)arg4;
- (id)initWithStatusText:(id)arg1 infoText:(id)arg2;

@end

