//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "NSObject-Protocol.h"

@class TNDRMatchCell;

@protocol TNDRMatchCellRowActionGestureDelegate <NSObject>
- (void)cell:(TNDRMatchCell *)arg1 didChangeRowActionStateToExpanded:(_Bool)arg2;
- (_Bool)cellShouldStartRowActionGesture:(TNDRMatchCell *)arg1;
- (void)cell:(TNDRMatchCell *)arg1 didTapOnRowActionWithType:(long long)arg2;
- (void)cellDidFinishRowActionGesture:(TNDRMatchCell *)arg1;
- (void)cellDidStartRowActionGesture:(TNDRMatchCell *)arg1;
@end

