//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "TNDRDialogViewController.h"

@class NSString;

@interface TNDRAlertDialog : TNDRDialogViewController
{
    // Error parsing type: , name: dialogTitle
    // Error parsing type: , name: message
    // Error parsing type: , name: confirmTitle
    // Error parsing type: , name: confirmBlock
    // Error parsing type: , name: cancelTitle
    // Error parsing type: , name: cancelBlock
}

- (CDUnknownBlockType).cxx_destruct;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;
- (id)animationControllerForDismissedController:(id)arg1;
- (id)animationControllerForPresentedController:(id)arg1 presentingController:(id)arg2 sourceController:(id)arg3;
- (void)didTapCancel;
- (void)didTapConfirm;
- (void)setupFooter;
- (void)setupHeader;
- (void)viewDidLoad;
- (id)initWithCoder:(id)arg1;
- (id)initWithTitle:(id)arg1 message:(id)arg2 confirmTitle:(id)arg3 confirmBlock:(CDUnknownBlockType)arg4 cancelTitle:(id)arg5 cancelBlock:(CDUnknownBlockType)arg6;
@property(nonatomic, copy) CDUnknownBlockType cancelBlock; // @synthesize cancelBlock;
@property(nonatomic, readonly) NSString *cancelTitle; // @synthesize cancelTitle;
@property(nonatomic, copy) CDUnknownBlockType confirmBlock; // @synthesize confirmBlock;
@property(nonatomic, readonly) NSString *confirmTitle; // @synthesize confirmTitle;
@property(nonatomic, readonly) NSString *message; // @synthesize message;
@property(nonatomic, readonly) NSString *dialogTitle; // @synthesize dialogTitle;

@end

