//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UICollectionViewCell.h>

@class TNDRCommonConnectionData, TNDRNetworkImageView, UILabel;

@interface TNDRCommonConnectionCell : UICollectionViewCell
{
    TNDRCommonConnectionData *_connectionData;
    TNDRNetworkImageView *_avatarImageView;
    UILabel *_degreeLabel;
    UILabel *_nameLabel;
}

+ (id)reuseIdentifier;
@property(retain, nonatomic) UILabel *nameLabel; // @synthesize nameLabel=_nameLabel;
@property(retain, nonatomic) UILabel *degreeLabel; // @synthesize degreeLabel=_degreeLabel;
@property(retain, nonatomic) TNDRNetworkImageView *avatarImageView; // @synthesize avatarImageView=_avatarImageView;
@property(retain, nonatomic) TNDRCommonConnectionData *connectionData; // @synthesize connectionData=_connectionData;
- (void).cxx_destruct;
- (void)prepareForReuse;
- (id)attributesForSuperscript;
- (id)attributesForNumeric;
- (id)degreeColor;
- (id)degreeAttributedText;
- (void)updateUserAvatar;
- (void)updateLabels;
- (void)setupConstraints;
- (void)setupWithFrame:(struct CGRect)arg1;
- (id)initWithFrame:(struct CGRect)arg1;

@end

