//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "TNDRDialogViewControllerDelegate-Protocol.h"
#import "TNDRInstagramLoginWebViewControllerDelegate-Protocol.h"
#import "UIViewControllerTransitioningDelegate-Protocol.h"

@class NSDictionary, NSSet, NSString, NSURL, TNDRAccountUnderReviewViewController, TNDRAccountUnderWarningDialogViewController, TNDRBoostPaywallViewController, TNDRCurrentUser, TNDRFastMatchPaywallViewController, TNDRInstagramLoginWebViewController, TNDRPlusPaywallViewController, TNDRSuperLikePaywallV2ViewController, TNDRWebURLViewController, UIViewController;
@protocol TNDRURLNavigableProtocol;

@interface TNDRURLManager : NSObject <UIViewControllerTransitioningDelegate, TNDRDialogViewControllerDelegate, TNDRInstagramLoginWebViewControllerDelegate>
{
    _Bool _avoidPushFromBase;
    _Bool _currentlyNavigating;
    NSURL *_currentURL;
    TNDRAccountUnderReviewViewController *_accountUnderReviewViewController;
    TNDRAccountUnderWarningDialogViewController *_accountReportedWarningDialogViewController;
    TNDRInstagramLoginWebViewController *_instagramWebLogin;
    NSURL *_baseURL;
    NSDictionary *_viewControllerKeys;
    NSSet *_viewControllerBaseKeys;
    NSSet *_viewControllersToNotNavigateAwayFrom;
    NSDictionary *_viewControllerOptions;
    NSSet *_viewControllersPresentedByBase;
    UIViewController<TNDRURLNavigableProtocol> *_baseSlidingViewController;
    UIViewController *_destinationViewController;
    UIViewController<TNDRURLNavigableProtocol> *_transitionToViewController;
    TNDRPlusPaywallViewController *_paywallViewController;
    TNDRSuperLikePaywallV2ViewController *_superLikePaywallVC;
    TNDRBoostPaywallViewController *_boostPaywallViewController;
    TNDRFastMatchPaywallViewController *_fastMatchPaywallViewController;
    TNDRWebURLViewController *_webURLViewController;
    unsigned long long _instagramAccountAnalyticsFrom;
    TNDRCurrentUser *_currentUser;
}

+ (id)sharedManager;
+ (void)setSharedInstance:(id)arg1;
@property(retain, nonatomic) TNDRCurrentUser *currentUser; // @synthesize currentUser=_currentUser;
@property(nonatomic, getter=isCurrentlyNavigating) _Bool currentlyNavigating; // @synthesize currentlyNavigating=_currentlyNavigating;
@property(nonatomic, getter=shouldAvoidPushFromBase) _Bool avoidPushFromBase; // @synthesize avoidPushFromBase=_avoidPushFromBase;
@property(nonatomic) unsigned long long instagramAccountAnalyticsFrom; // @synthesize instagramAccountAnalyticsFrom=_instagramAccountAnalyticsFrom;
@property(retain, nonatomic) TNDRWebURLViewController *webURLViewController; // @synthesize webURLViewController=_webURLViewController;
@property(nonatomic) __weak TNDRFastMatchPaywallViewController *fastMatchPaywallViewController; // @synthesize fastMatchPaywallViewController=_fastMatchPaywallViewController;
@property(nonatomic) __weak TNDRBoostPaywallViewController *boostPaywallViewController; // @synthesize boostPaywallViewController=_boostPaywallViewController;
@property(nonatomic) __weak TNDRSuperLikePaywallV2ViewController *superLikePaywallVC; // @synthesize superLikePaywallVC=_superLikePaywallVC;
@property(nonatomic) __weak TNDRPlusPaywallViewController *paywallViewController; // @synthesize paywallViewController=_paywallViewController;
@property(nonatomic) __weak UIViewController<TNDRURLNavigableProtocol> *transitionToViewController; // @synthesize transitionToViewController=_transitionToViewController;
@property(nonatomic) __weak UIViewController *destinationViewController; // @synthesize destinationViewController=_destinationViewController;
@property(retain, nonatomic) UIViewController<TNDRURLNavigableProtocol> *baseSlidingViewController; // @synthesize baseSlidingViewController=_baseSlidingViewController;
@property(retain, nonatomic) NSSet *viewControllersPresentedByBase; // @synthesize viewControllersPresentedByBase=_viewControllersPresentedByBase;
@property(retain, nonatomic) NSDictionary *viewControllerOptions; // @synthesize viewControllerOptions=_viewControllerOptions;
@property(retain, nonatomic) NSSet *viewControllersToNotNavigateAwayFrom; // @synthesize viewControllersToNotNavigateAwayFrom=_viewControllersToNotNavigateAwayFrom;
@property(retain, nonatomic) NSSet *viewControllerBaseKeys; // @synthesize viewControllerBaseKeys=_viewControllerBaseKeys;
@property(retain, nonatomic) NSDictionary *viewControllerKeys; // @synthesize viewControllerKeys=_viewControllerKeys;
@property(retain, nonatomic) NSURL *baseURL; // @synthesize baseURL=_baseURL;
@property(readonly, nonatomic) TNDRInstagramLoginWebViewController *instagramWebLogin; // @synthesize instagramWebLogin=_instagramWebLogin;
@property(readonly, nonatomic) TNDRAccountUnderWarningDialogViewController *accountReportedWarningDialogViewController; // @synthesize accountReportedWarningDialogViewController=_accountReportedWarningDialogViewController;
@property(readonly, nonatomic) TNDRAccountUnderReviewViewController *accountUnderReviewViewController; // @synthesize accountUnderReviewViewController=_accountUnderReviewViewController;
@property(retain, nonatomic) NSURL *currentURL; // @synthesize currentURL=_currentURL;
- (void).cxx_destruct;
- (void)dialogViewControllerRequestsDismissal:(id)arg1 completion:(CDUnknownBlockType)arg2;
- (id)animationControllerForDismissedController:(id)arg1;
- (id)animationControllerForPresentedController:(id)arg1 presentingController:(id)arg2 sourceController:(id)arg3;
- (void)dismissInstagramLoginView;
- (void)didCancelInstagramLogin;
- (void)didCompleteLoginWithAccessCode:(id)arg1;
- (void)didFailLoginWithMessage:(id)arg1;
- (void)requestUserName;
- (void)showInstagramWebLogin;
- (void)requestInstagramLogin:(unsigned long long)arg1;
- (void)handleAccountWarningBannedNotificationWithCompletion:(CDUnknownBlockType)arg1;
- (void)handleAccountWarningType:(long long)arg1 completion:(CDUnknownBlockType)arg2;
- (void)notifyUserWithAccountChanges:(unsigned long long)arg1;
- (void)blockNavigationWithWarningType:(long long)arg1 completion:(CDUnknownBlockType)arg2;
- (void)clearNavigationBlock:(CDUnknownBlockType)arg1;
- (_Bool)accountBannedWarningInURLString:(id)arg1;
- (_Bool)accountReportingWarningInURLString:(id)arg1;
@property(readonly, nonatomic, getter=isPresentingAccountBannedWarning) _Bool presentingAccountBannedWarning;
- (_Bool)isPresentingAccountReportedWarning;
- (void)navigateToPaywallType:(unsigned long long)arg1 shownFrom:(unsigned long long)arg2 feature:(long long)arg3 delegate:(id)arg4 parameters:(id)arg5 completion:(CDUnknownBlockType)arg6;
- (void)navigateToPaywallType:(unsigned long long)arg1 shownFrom:(unsigned long long)arg2 incentives:(id)arg3 incentivesOrdering:(id)arg4 feature:(long long)arg5 delegate:(id)arg6 parameters:(id)arg7 completion:(CDUnknownBlockType)arg8;
- (id)mergeDictionary:(id)arg1 withValuesFromOtherDictionary:(id)arg2;
- (long long)lastIndexOfURL;
- (id)viewControllerOptionsForKey:(id)arg1;
- (void)removeOptionsForLastPresentedViewController:(id)arg1;
- (void)putURLQueryOptions:(id)arg1 forKey:(id)arg2;
- (void)removeViewControllerForKey:(id)arg1;
@property(readonly, nonatomic) UIViewController<TNDRURLNavigableProtocol> *currentlyVisibleViewController;
- (id)viewControllerForKey:(id)arg1;
- (void)addViewController:(id)arg1 forKey:(id)arg2;
- (void)didNavigateFromViewController:(id)arg1 toViewController:(id)arg2;
- (void)willNavigateFromViewController:(id)arg1 toViewController:(id)arg2;
- (_Bool)shouldNotNavigateAwayFromCurrentViewController;
- (_Bool)shouldNavigateToBase:(id)arg1;
- (id)queryDictionaryFromString:(id)arg1;
- (_Bool)validateURLString:(id)arg1;
- (id)componentsOfURLString:(id)arg1;
- (id)parseURLComponentsFromStringByStrippingQuery:(id)arg1;
- (id)retrieveNavigationInfoFrom:(id)arg1 to:(id)arg2;
- (void)addToCurrentURLPresentedViewController:(id)arg1;
- (id)removeLastPresentedViewControllerFromCurrentURL;
- (void)addViewControllerKeyToBaseSet:(id)arg1;
- (id)appendToCurrentURL:(id)arg1;
- (void)verifyViewControllerValidity:(id)arg1 andVCKey:(id)arg2;
- (_Bool)areViewControllerOptions:(id)arg1 equalToOptions:(id)arg2;
- (_Bool)hasNavigatedToDescendantOfViewControllerKey:(id)arg1 withOptions:(id)arg2 relative:(_Bool)arg3 completion:(CDUnknownBlockType)arg4;
- (_Bool)checkIfCanPerformRequestedNavigations;
- (void)_navigateBackToBaseAnimated:(_Bool)arg1 internal:(_Bool)arg2 completion:(CDUnknownBlockType)arg3;
- (void)detectAndHandleTransitionToSpecialDialogViewController:(id)arg1 nextViewControllerKey:(id)arg2 optionsDict:(id)arg3 animated:(_Bool)arg4 completion:(CDUnknownBlockType)arg5;
- (_Bool)detectAndHandleSafariViewControllerPresentation:(id)arg1;
- (void)performAppNavigationForComponents:(id)arg1 query:(id)arg2 optionsDict:(id)arg3 animated:(_Bool)arg4 completion:(CDUnknownBlockType)arg5;
- (void)performAppDismissalThisManyTimes:(long long)arg1 animated:(_Bool)arg2 actuallyDismiss:(_Bool)arg3 completion:(CDUnknownBlockType)arg4;
- (void)performAppDismissalThisManyTimes:(long long)arg1 animated:(_Bool)arg2 completion:(CDUnknownBlockType)arg3;
- (void)performAppNavigationFrom:(id)arg1 to:(id)arg2 withOptions:(id)arg3 animated:(_Bool)arg4 completion:(CDUnknownBlockType)arg5;
- (void)registerViewControllerKeyToPreventNavigationFrom:(id)arg1;
- (void)registerViewControllerKeyToBePresentedByBase:(id)arg1;
- (void)registerViewController:(id)arg1 withKey:(id)arg2 isSlidingViewBase:(_Bool)arg3;
- (void)registerViewController:(id)arg1 withKey:(id)arg2;
- (void)performOutOfBandTransition:(long long)arg1 fromViewController:(id)arg2 toViewController:(id)arg3 relative:(_Bool)arg4;
- (void)didTransitionFromViewController:(id)arg1 toViewController:(id)arg2 relative:(_Bool)arg3 outOfBand:(long long)arg4;
- (void)didNavigateBack;
- (void)navigateBackToBaseAnimated:(_Bool)arg1 completion:(CDUnknownBlockType)arg2;
- (void)navigateBackAnimated:(_Bool)arg1 completion:(CDUnknownBlockType)arg2;
- (void)navigateToURL:(id)arg1 optionsDict:(id)arg2 animated:(_Bool)arg3 relativeToCurrentPath:(_Bool)arg4 completion:(CDUnknownBlockType)arg5;
- (void)navigateToURL:(id)arg1 animated:(_Bool)arg2 relativeToCurrentPath:(_Bool)arg3 completion:(CDUnknownBlockType)arg4;
- (void)pushAndNavigateToNavigationController:(id)arg1 withRootViewController:(id)arg2 animated:(_Bool)arg3 completion:(CDUnknownBlockType)arg4;
- (void)pushAndNavigateToViewController:(id)arg1 options:(id)arg2 animated:(_Bool)arg3 completion:(CDUnknownBlockType)arg4;
- (void)pushAndNavigateToViewController:(id)arg1 animated:(_Bool)arg2 completion:(CDUnknownBlockType)arg3;
- (void)setup;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

