//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSArray, TNDRAlertDialog, TNDRAuthToken, TNDRExperimentCoordinator, TNDRHTTPClient, UIButton, UINavigationController, UIViewController, _TtC6Tinder29OnboardingStepCreationErrorVC;
@protocol TNDROnboardingCoordinatorDelegate;

@interface TNDROnboardingCoordinator : NSObject
{
    // Error parsing type: , name: httpClient
    // Error parsing type: , name: experimentCoordinator
    // Error parsing type: , name: delegate
    // Error parsing type: , name: isInProgress
    // Error parsing type: , name: token
    // Error parsing type: , name: onboardingInfo
    // Error parsing type: , name: fields
    // Error parsing type: , name: isUserUnderage
    // Error parsing type: , name: baseVC
    // Error parsing type: , name: errorVC
    // Error parsing type: , name: stepNavigationController
    // Error parsing type: , name: stepCancelButton.storage
    // Error parsing type: , name: confirmCancelAlert.storage
    // Error parsing type: , name: stepVCs.storage
}

- (CDUnknownBlockType).cxx_destruct;
- (id)init;
- (void)presentRootStepVC:(id)arg1;
- (void)setupStepVC:(id)arg1 idx:(long long)arg2;
- (id)navigateToNextStepFrom:(id)arg1 animated:(_Bool)arg2;
- (void)navigateToFirstIncompleteStepFrom:(id)arg1;
- (void)startOnboardingWithToken:(id)arg1 baseVC:(id)arg2;
@property(nonatomic, copy) NSArray *stepVCs;
- (long long)priorityOf:(id)arg1;
@property(nonatomic, retain) TNDRAlertDialog *confirmCancelAlert;
@property(nonatomic, retain) UIButton *stepCancelButton;
@property(nonatomic, retain) UINavigationController *stepNavigationController; // @synthesize stepNavigationController;
@property(nonatomic, retain) _TtC6Tinder29OnboardingStepCreationErrorVC *errorVC; // @synthesize errorVC;
@property(nonatomic) __weak UIViewController *baseVC; // @synthesize baseVC;
@property(nonatomic) _Bool isUserUnderage; // @synthesize isUserUnderage;
@property(nonatomic, retain) TNDRAuthToken *token; // @synthesize token;
@property(nonatomic) _Bool isInProgress; // @synthesize isInProgress;
@property(nonatomic) __weak id <TNDROnboardingCoordinatorDelegate> delegate; // @synthesize delegate;
@property(nonatomic, readonly) TNDRExperimentCoordinator *experimentCoordinator; // @synthesize experimentCoordinator;
@property(nonatomic, readonly) TNDRHTTPClient *httpClient; // @synthesize httpClient;

@end

