//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIViewController.h>

#import "TNDRSpotifyServiceDelegate-Protocol.h"
#import "TNDRThemeSongViewDelegate-Protocol.h"

@class NSNotificationCenter, NSString, TNDRCoreDataService, TNDRCurrentUser, TNDRNotificationWindow, TNDRSpotifyAnalyticsTracker, TNDRSpotifyAuthenticator, TNDRSpotifyService, TNDRThemeSongView, TNDRTrack, TNDRUser;
@protocol TNDRThemeSongViewControllerDelegate;

@interface TNDRThemeSongViewController : UIViewController <TNDRSpotifyServiceDelegate, TNDRThemeSongViewDelegate>
{
    _Bool _isMatch;
    id <TNDRThemeSongViewControllerDelegate> _delegate;
    TNDRThemeSongView *_songView;
    TNDRTrack *_themeTrack;
    TNDRUser *_user;
    TNDRSpotifyService *_spotifyService;
}

@property(retain, nonatomic) TNDRSpotifyService *spotifyService; // @synthesize spotifyService=_spotifyService;
@property(nonatomic) _Bool isMatch; // @synthesize isMatch=_isMatch;
@property(retain, nonatomic) TNDRUser *user; // @synthesize user=_user;
@property(retain, nonatomic) TNDRTrack *themeTrack; // @synthesize themeTrack=_themeTrack;
@property(retain, nonatomic) TNDRThemeSongView *songView; // @synthesize songView=_songView;
@property(nonatomic) __weak id <TNDRThemeSongViewControllerDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)handleThemeSongChange:(id)arg1;
- (void)removeNotifications;
- (void)registerForNotifcations;
- (void)themeSongViewDidSelectStopPlaying:(id)arg1;
- (void)themeSongViewDidSelectStartPlaying:(id)arg1;
- (void)themeSongViewDidSelectOpenInSpotify:(id)arg1;
- (void)spotifyService:(id)arg1 didStopTrackPreviewURL:(id)arg2;
- (void)spotifyService:(id)arg1 didUpdateProgress:(double)arg2;
- (void)spotifyService:(id)arg1 didFailToPlayTrackPreviewURL:(id)arg2;
- (void)spotifyService:(id)arg1 didStartPlayTrackPreviewURL:(id)arg2;
- (void)updateControllerWithTrack:(id)arg1;
- (void)viewDidLoad;
@property(readonly, nonatomic) TNDRThemeSongView *themeSongView;
- (void)loadView;
@property(readonly, nonatomic) TNDRNotificationWindow *notificationWindow;
@property(readonly, nonatomic) NSNotificationCenter *notificationCenter;
- (id)initWithTrack:(id)arg1;
@property(readonly, nonatomic) TNDRCurrentUser *currentUser;
@property(readonly, nonatomic) TNDRSpotifyAuthenticator *spotifyAuthenticator;
@property(readonly, nonatomic) TNDRSpotifyAnalyticsTracker *spotifyAnalyticsTracker;
@property(readonly, nonatomic) TNDRCoreDataService *dataService;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

