//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@interface TNDRCreateGroupAlertCompletionContainer : NSObject
{
    // Error parsing type: , name: completionHandler
}

- (CDUnknownBlockType).cxx_destruct;
- (id)init;
- (id)initWithCompletionHandler:(CDUnknownBlockType)arg1;
@property(nonatomic, readonly) CDUnknownBlockType completionHandler; // @synthesize completionHandler;

@end

