//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSArray;

@interface TNDRFacebookPermissions : NSObject
{
    NSArray *_allPermissions;
}

+ (id)suggestedPermissions;
+ (id)requiredPermissions;
+ (id)typeStringsFromPermissions:(id)arg1;
+ (id)suggestedPermissionTypeStrings;
+ (id)requiredPermissionTypeStrings;
@property(copy, nonatomic) NSArray *allPermissions; // @synthesize allPermissions=_allPermissions;
- (void).cxx_destruct;
@property(readonly, nonatomic) _Bool hasSuggestedPermissions;
@property(readonly, nonatomic) NSArray *deniedRequiredPermissions;
@property(readonly, nonatomic) _Bool hasRequiredPermissions;
- (_Bool)hasGrantedPermissions:(id)arg1;
- (id)permissionWithType:(unsigned long long)arg1;
- (id)initWithTypeStrings:(id)arg1 andStatus:(unsigned long long)arg2;
- (id)initWithDictionary:(id)arg1;
- (id)initWithPermissions:(id)arg1;
@property(readonly, copy, nonatomic) NSArray *grantedPermissions;

@end

