//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "_TtP15CoreDataService18TransactionMonitor_-Protocol.h"

@interface TNDRBackgroundTask : NSObject <_TtP15CoreDataService18TransactionMonitor_>
{
}

- (id)init;
- (void)end:(long long)arg1;
- (long long)beginWithName:(id)arg1 expirationHandler:(CDUnknownBlockType)arg2;
- (long long)beginWithName:(id)arg1;

@end

