//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "TNDRCardStackViewController.h"

@interface TNDRCardStackViewController (Tinder)
- (id)contentViewForCardAt:(long long)arg1 cardStack:(id)arg2;
- (long long)numberOfCardsIn:(id)arg1;
@end

