//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "NSObject-Protocol.h"

@class UILabel, UIView;

@protocol TNDRDialogHeader <NSObject>
@property(nonatomic) _Bool hideSeparatorLine;
@property(readonly, nonatomic) UILabel *detailTextLabel;
@property(readonly, nonatomic) UILabel *titleTextLabel;
@property(readonly, nonatomic) UIView *contentView;
@end

