//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "TNDRAppRaterWindowDelegate-Protocol.h"

@class NSArray, NSDate, NSString, TNDRAppRaterWindow;
@protocol AppRaterDelegateProtocol;

@interface TNDRAppRater : NSObject <TNDRAppRaterWindowDelegate>
{
    _Bool _onlyPromptIfLatestVersion;
    _Bool _previewMode;
    _Bool _shouldPromptForCrashing;
    id <AppRaterDelegateProtocol> _delegate;
    unsigned long long _appStoreGenreID;
    NSString *_appStoreCountry;
    NSString *_applicationName;
    NSString *_applicationVersion;
    NSString *_applicationBundleID;
    TNDRAppRaterWindow *_tinderAppRaterWindow;
    long long _showCause;
}

+ (id)sharedInstance;
@property(nonatomic) long long showCause; // @synthesize showCause=_showCause;
@property(retain, nonatomic) TNDRAppRaterWindow *tinderAppRaterWindow; // @synthesize tinderAppRaterWindow=_tinderAppRaterWindow;
@property(copy, nonatomic) NSString *applicationBundleID; // @synthesize applicationBundleID=_applicationBundleID;
@property(copy, nonatomic) NSString *applicationVersion; // @synthesize applicationVersion=_applicationVersion;
@property(copy, nonatomic) NSString *applicationName; // @synthesize applicationName=_applicationName;
@property(copy, nonatomic) NSString *appStoreCountry; // @synthesize appStoreCountry=_appStoreCountry;
@property(nonatomic) unsigned long long appStoreGenreID; // @synthesize appStoreGenreID=_appStoreGenreID;
@property(nonatomic) _Bool shouldPromptForCrashing; // @synthesize shouldPromptForCrashing=_shouldPromptForCrashing;
@property(nonatomic) _Bool previewMode; // @synthesize previewMode=_previewMode;
@property(nonatomic) __weak id <AppRaterDelegateProtocol> delegate; // @synthesize delegate=_delegate;
@property(nonatomic) _Bool onlyPromptIfLatestVersion; // @synthesize onlyPromptIfLatestVersion=_onlyPromptIfLatestVersion;
- (void).cxx_destruct;
- (void)putDefaultsValue:(id)arg1 forKey:(id)arg2;
- (id)defaultsValueForKey:(id)arg1;
- (void)resetAppRaterState;
- (void)updateFirstLoginTimeForRatingTo:(id)arg1;
- (void)checkAndUpdateAppRaterStateForVersioning;
- (_Bool)isAllowedToPromptForRating;
- (_Bool)canPromptForRatingCrash;
- (_Bool)deviceHasConnectivity;
- (void)sendFeedback:(id)arg1 withStarRating:(long long)arg2 isRetry:(_Bool)arg3;
- (void)openAppStorePageForReviewing;
- (void)openFeedbackDialog;
- (void)appRaterWindowRequestsSendingFeedbackText:(id)arg1 andStarRating:(long long)arg2;
- (long long)appRaterWindowRequestingCachedStarRating;
- (void)appRaterWindowSelectedStarRating:(long long)arg1;
- (void)appRaterWindowRequestedToClearCurrentRating;
- (void)appRaterWindowDidReviewPositively:(_Bool)arg1;
- (void)appRaterWindowDidRequestToReviewApp;
- (_Bool)versionIsGreaterOrEqualThanVersionOnAppStore;
- (_Bool)versionIsEqualToVersionOnAppStore;
- (void)setCurrentAppStoreVersionOnMainThread:(id)arg1;
- (void)setAppStoreIDOnMainThread:(id)arg1;
- (void)postAppStoreCheckPromptForRating;
- (void)connectionSucceeded;
- (void)connectionError:(id)arg1;
- (void)checkAppStoreForAbilityToRate:(CDUnknownBlockType)arg1;
- (void)promptForRatingAfterAppStoreCheckForced:(_Bool)arg1;
- (void)promptForRatingAfterAppStoreCheck;
- (void)appInitializedCheckForPreviousFeedbackFailure;
- (void)appInitializedCheckCrashesAndRateIfNeeded;
- (void)resetMetrics;
- (void)showRatingPromptToUserForced;
- (void)showRatingPromptToUserIfPossibleWithCause:(long long)arg1;
- (void)applicationCompletedLaunching;
- (void)addCrashTimestamp:(id)arg1;
@property(nonatomic) double minTimeBetweenCrashesForRatingPrompt;
@property(nonatomic) long long appStoreID;
@property(nonatomic) long long currentPromptedRatingType;
@property(retain, nonatomic) NSDate *dateToInitiallyCompareTo;
@property(nonatomic) long long numberOfDaysBeforeRatingPromptPossible;
@property(retain, nonatomic) NSString *appStoreAppVersion;
@property(nonatomic, getter=hasCheckedCrashesOnInitialization) _Bool checkedCrashesOnInitialization;
@property(readonly, nonatomic) NSArray *crashesDateList;
- (void)setupDefaultsForTinder;
- (void)setup;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

