//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSArray, NSDictionary;

@interface TNDRReportReasonsViewModel : NSObject
{
    NSArray *_reportingReasons;
    NSDictionary *_reportingReasonsImageNames;
    NSDictionary *_reportingReasonsStrings;
}

+ (id)analyticsReportKeyForReason:(unsigned long long)arg1;
@property(retain, nonatomic) NSDictionary *reportingReasonsStrings; // @synthesize reportingReasonsStrings=_reportingReasonsStrings;
@property(retain, nonatomic) NSDictionary *reportingReasonsImageNames; // @synthesize reportingReasonsImageNames=_reportingReasonsImageNames;
@property(readonly, nonatomic) NSArray *reportingReasons; // @synthesize reportingReasons=_reportingReasons;
- (void).cxx_destruct;
- (id)localizedStringsForReportReasons:(id)arg1;
- (id)localizedStringForReportingReason:(unsigned long long)arg1;
- (id)imageForReportingReason:(unsigned long long)arg1;
- (id)localizedStringForIndexPath:(id)arg1;
- (id)imageForIndexPath:(id)arg1;
- (void)requestReportReasonsWithCompletion:(CDUnknownBlockType)arg1;
- (id)init;

@end

