//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

@class NSDictionary, UIButton, UILabel;

@interface TNDRIntroToSpotifyDialogFooter : UIView
{
    UIButton *_actionButton;
    UIButton *_cancelButton;
    UILabel *_footerTitleLabel;
    UILabel *_footerDetailLabel;
}

+ (_Bool)requiresConstraintBasedLayout;
@property(retain, nonatomic) UILabel *footerDetailLabel; // @synthesize footerDetailLabel=_footerDetailLabel;
@property(retain, nonatomic) UILabel *footerTitleLabel; // @synthesize footerTitleLabel=_footerTitleLabel;
@property(retain, nonatomic) UIButton *cancelButton; // @synthesize cancelButton=_cancelButton;
@property(retain, nonatomic) UIButton *actionButton; // @synthesize actionButton=_actionButton;
- (void).cxx_destruct;
- (struct CGSize)intrinsicContentSize;
- (void)layoutSubviews;
@property(readonly, copy, nonatomic) NSDictionary *viewsForAL;
@property(readonly, copy, nonatomic) NSDictionary *metricsForAL;
- (void)setupConstraints;
- (void)setup;
- (id)initWithFrame:(struct CGRect)arg1;

@end

