//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@interface TNDRMessageStandardsContext : NSObject
{
    // Error parsing type: , name: completion
    // Error parsing type: , name: messageStandardsVC
    // Error parsing type: , name: currentUser
    // Error parsing type: , name: experiment
    // Error parsing type: , name: messageStandardsPresenter
    // Error parsing type: , name: analyticsTracker
    // Error parsing type: , name: presentableGender
}

- (CDUnknownBlockType).cxx_destruct;
- (id)init;
- (_Bool)presentIfNecessaryWithCompletion:(CDUnknownBlockType)arg1;
- (id)initWithPresentableGender:(long long)arg1 presenter:(id)arg2 currentUser:(id)arg3 experiment:(id)arg4 analyticsTracker:(id)arg5;

@end

