//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

@class TNDRPausePlayView, UIActivityIndicatorView, UIImageView, UITapGestureRecognizer;

@interface TNDRCircularTrackPlayerView : UIView
{
    unsigned long long _state;
    double _percentage;
    CDUnknownBlockType _updatedState;
    UIImageView *_trackImageView;
    TNDRPausePlayView *_playPauseView;
    UITapGestureRecognizer *_tapGesture;
    UIActivityIndicatorView *_activityIndicator;
    unsigned long long _transition;
}

@property(nonatomic) unsigned long long transition; // @synthesize transition=_transition;
@property(retain, nonatomic) UIActivityIndicatorView *activityIndicator; // @synthesize activityIndicator=_activityIndicator;
@property(retain, nonatomic) UITapGestureRecognizer *tapGesture; // @synthesize tapGesture=_tapGesture;
@property(retain, nonatomic) TNDRPausePlayView *playPauseView; // @synthesize playPauseView=_playPauseView;
@property(retain, nonatomic) UIImageView *trackImageView; // @synthesize trackImageView=_trackImageView;
@property(copy, nonatomic) CDUnknownBlockType updatedState; // @synthesize updatedState=_updatedState;
@property(nonatomic) double percentage; // @synthesize percentage=_percentage;
@property(nonatomic) unsigned long long state; // @synthesize state=_state;
- (void).cxx_destruct;
- (id)playImage;
- (id)pauseImage;
- (id)cornerRadiusAnimationFrom:(double)arg1 toValue:(double)arg2;
- (id)windUpSpinningAnimation;
- (id)infiniteSpinningAnimation;
- (void)stopSpinningTrack;
- (void)startSpinningTrack;
- (void)setPlayerImageWithURL:(id)arg1;
- (void)handleTap:(id)arg1;
- (void)setPlayCirclePercentage:(double)arg1;
- (void)transitionToLoadingState:(_Bool)arg1;
- (void)transitionToPlayStateAnimated:(_Bool)arg1;
- (void)transitionToStopStateAnimated:(_Bool)arg1;
- (void)setState:(unsigned long long)arg1 animated:(_Bool)arg2;
- (void)layoutSubviews;
- (struct CGSize)sizeThatFits:(struct CGSize)arg1;
- (void)setupActivityIndicator;
- (id)initWithFrame:(struct CGRect)arg1;

@end

