//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "TNDRExperimentDelegate-Protocol.h"

@class NSArray, NSNotificationCenter, NSString, TNDRAuthExperiment, TNDRBoostOptimizationExperiment, TNDRCustomGenderExperiment, TNDRGoogleDFPExperiment, TNDRMatchesGoingOutExperiment, TNDRMessageStandardsExperiment, TNDRPerformanceTrackerExperiment, TNDRPhotoOptimizerExperiment, TNDRProfileV2Experiment, TNDRPushNotificationExperiment, TNDRRecsV2Experiment, TNDRReportingV2Experiment, _TtC6Tinder13FANExperiment, _TtC6Tinder15LeanplumService, _TtC6Tinder16ChatV2Experiment, _TtC6Tinder18RecsViewExperiment, _TtC6Tinder20ExitSurveyExperiment;

@interface TNDRExperimentCoordinator : NSObject <TNDRExperimentDelegate>
{
    NSArray *_allExperiments;
    TNDRAuthExperiment *_authExperiment;
    TNDRMatchesGoingOutExperiment *_goingOutExperiment;
    TNDRCustomGenderExperiment *_customGenderExperiment;
    TNDRBoostOptimizationExperiment *_boostOptimizationExperiment;
    TNDRGoogleDFPExperiment *_googleDFPExperiment;
    _TtC6Tinder13FANExperiment *_fanExperiment;
    _TtC6Tinder20ExitSurveyExperiment *_exitSurveyExperiment;
    TNDRPhotoOptimizerExperiment *_photoOptimizerExperiment;
    TNDRPerformanceTrackerExperiment *_performanceTrackerExperiment;
    TNDRPushNotificationExperiment *_pushNotificationExperiment;
    TNDRReportingV2Experiment *_reportingV2Experiment;
    TNDRRecsV2Experiment *_recsV2Experiment;
    TNDRProfileV2Experiment *_profileV2Experiment;
    TNDRMessageStandardsExperiment *_messageStandardsExperiment;
    _TtC6Tinder18RecsViewExperiment *_recsExperiment;
    _TtC6Tinder16ChatV2Experiment *_chatV2Experiment;
    _TtC6Tinder15LeanplumService *_leanplumService;
}

+ (id)sharedExperimentCoordinator;
@property(retain, nonatomic) _TtC6Tinder15LeanplumService *leanplumService; // @synthesize leanplumService=_leanplumService;
@property(retain, nonatomic) _TtC6Tinder16ChatV2Experiment *chatV2Experiment; // @synthesize chatV2Experiment=_chatV2Experiment;
@property(retain, nonatomic) _TtC6Tinder18RecsViewExperiment *recsExperiment; // @synthesize recsExperiment=_recsExperiment;
@property(retain, nonatomic) TNDRMessageStandardsExperiment *messageStandardsExperiment; // @synthesize messageStandardsExperiment=_messageStandardsExperiment;
@property(retain, nonatomic) TNDRProfileV2Experiment *profileV2Experiment; // @synthesize profileV2Experiment=_profileV2Experiment;
@property(retain, nonatomic) TNDRRecsV2Experiment *recsV2Experiment; // @synthesize recsV2Experiment=_recsV2Experiment;
@property(retain, nonatomic) TNDRReportingV2Experiment *reportingV2Experiment; // @synthesize reportingV2Experiment=_reportingV2Experiment;
@property(retain, nonatomic) TNDRPushNotificationExperiment *pushNotificationExperiment; // @synthesize pushNotificationExperiment=_pushNotificationExperiment;
@property(retain, nonatomic) TNDRPerformanceTrackerExperiment *performanceTrackerExperiment; // @synthesize performanceTrackerExperiment=_performanceTrackerExperiment;
@property(retain, nonatomic) TNDRPhotoOptimizerExperiment *photoOptimizerExperiment; // @synthesize photoOptimizerExperiment=_photoOptimizerExperiment;
@property(retain, nonatomic) _TtC6Tinder20ExitSurveyExperiment *exitSurveyExperiment; // @synthesize exitSurveyExperiment=_exitSurveyExperiment;
@property(retain, nonatomic) _TtC6Tinder13FANExperiment *fanExperiment; // @synthesize fanExperiment=_fanExperiment;
@property(retain, nonatomic) TNDRGoogleDFPExperiment *googleDFPExperiment; // @synthesize googleDFPExperiment=_googleDFPExperiment;
@property(retain, nonatomic) TNDRBoostOptimizationExperiment *boostOptimizationExperiment; // @synthesize boostOptimizationExperiment=_boostOptimizationExperiment;
@property(retain, nonatomic) TNDRCustomGenderExperiment *customGenderExperiment; // @synthesize customGenderExperiment=_customGenderExperiment;
@property(retain, nonatomic) TNDRMatchesGoingOutExperiment *goingOutExperiment; // @synthesize goingOutExperiment=_goingOutExperiment;
@property(retain, nonatomic) TNDRAuthExperiment *authExperiment; // @synthesize authExperiment=_authExperiment;
@property(copy, nonatomic) NSArray *allExperiments; // @synthesize allExperiments=_allExperiments;
- (void).cxx_destruct;
- (void)experimentDidUpdate:(id)arg1;
- (void)saveAllExperiments;
- (void)didReceiveCurrentUserDidClearInformationNotification:(id)arg1;
- (void)dealloc;
- (void)registerForNotifications;
- (void)start;
- (void)clearAllOverrides;
- (void)initializeExperiments;
@property(readonly, nonatomic) NSNotificationCenter *notificationCenter;
@property(readonly, copy, nonatomic) NSArray *overridableExperiments;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

