//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "TNDRCardStackViewController.h"

@interface TNDRCardStackViewController (Tinder3)
- (void)showWebLinkRecommendation:(id)arg1 in:(id)arg2;
- (void)notifyRecommendationsUnavailable;
- (id)lastVisibleRecommendation;
- (id)nextRecommendation;
- (id)previousRecommendation;
- (id)currentRecommendation;
- (long long)remainingCardCount;
@end

