//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "TNDRExperiment.h"

@class TNDRReportingV2ExperimentVariableChatActionIconType, TNDRReportingV2ExperimentVariableFeatureEnabled, TNDRReportingV2ExperimentVariableOtherTextRequired, TNDRReportingV2ExperimentVariableSwipeListModalDisabled;

@interface TNDRReportingV2Experiment : TNDRExperiment
{
    TNDRReportingV2ExperimentVariableFeatureEnabled *_reportingV2FeatureEnabled;
    TNDRReportingV2ExperimentVariableChatActionIconType *_reportingV2ChatActionIconType;
    TNDRReportingV2ExperimentVariableOtherTextRequired *_reportingV2OtherTextRequired;
    TNDRReportingV2ExperimentVariableSwipeListModalDisabled *_reportingV2SwipeListModalDisabled;
}

@property(retain, nonatomic) TNDRReportingV2ExperimentVariableSwipeListModalDisabled *reportingV2SwipeListModalDisabled; // @synthesize reportingV2SwipeListModalDisabled=_reportingV2SwipeListModalDisabled;
@property(retain, nonatomic) TNDRReportingV2ExperimentVariableOtherTextRequired *reportingV2OtherTextRequired; // @synthesize reportingV2OtherTextRequired=_reportingV2OtherTextRequired;
@property(retain, nonatomic) TNDRReportingV2ExperimentVariableChatActionIconType *reportingV2ChatActionIconType; // @synthesize reportingV2ChatActionIconType=_reportingV2ChatActionIconType;
@property(retain, nonatomic) TNDRReportingV2ExperimentVariableFeatureEnabled *reportingV2FeatureEnabled; // @synthesize reportingV2FeatureEnabled=_reportingV2FeatureEnabled;
- (void).cxx_destruct;
- (id)allExperimentVariables;
- (id)name;
@property(readonly, nonatomic) _Bool isSwipeMatchListModalDisabled;
@property(readonly, nonatomic) _Bool isReportOtherReasonTextRequired;
@property(readonly, nonatomic) long long reportingChatActionIconType;
@property(readonly, nonatomic) _Bool isReportingV2Enabled;

@end

