//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "TNDRNotification.h"

@class NSURL;

@interface TNDRGroupMessageNotification : TNDRNotification
{
    NSURL *_avatarURL;
}

@property(copy, nonatomic) NSURL *avatarURL; // @synthesize avatarURL=_avatarURL;
- (void).cxx_destruct;

@end

