//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "TNDRGamepadContext.h"

@interface TNDRGamepadContext (Tinder2)
- (void)updateGamepadForStackType:(long long)arg1 withBoostActive:(_Bool)arg2 hasUserBeenShownBoostWhatsNew:(_Bool)arg3 completion:(CDUnknownBlockType)arg4;
@end

