//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "TNDRBoostDialogBaseViewController.h"

@class TNDRCurrentUser;
@protocol TNDRStartBoostProtocol;

@interface TNDRBoostSummaryViewController : TNDRBoostDialogBaseViewController
{
    _Bool _isTinderPlusSubscriber;
    id <TNDRStartBoostProtocol> _boostDelegate;
    double _multiplier;
    long long _boostDuration;
    TNDRCurrentUser *_currentUser;
}

+ (id)viewControllerNavigationKey;
+ (_Bool)showsGradientBackground;
@property(retain, nonatomic) TNDRCurrentUser *currentUser; // @synthesize currentUser=_currentUser;
@property(readonly, nonatomic) _Bool isTinderPlusSubscriber; // @synthesize isTinderPlusSubscriber=_isTinderPlusSubscriber;
@property(readonly, nonatomic) long long boostDuration; // @synthesize boostDuration=_boostDuration;
@property(readonly, nonatomic) double multiplier; // @synthesize multiplier=_multiplier;
@property(nonatomic) __weak id <TNDRStartBoostProtocol> boostDelegate; // @synthesize boostDelegate=_boostDelegate;
- (void).cxx_destruct;
- (void)getTinderPlus:(id)arg1;
- (void)startBoost;
- (void)dismiss:(id)arg1;
- (void)setupFooterView;
- (void)viewDidAppear:(_Bool)arg1;
- (void)viewDidLoad;
- (id)initWithMultiplier:(double)arg1 boostDuration:(long long)arg2 isTinderPlusSubscriber:(_Bool)arg3;

@end

