//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

@class NSDictionary, UIButton, UILabel, UITextField;

@interface TNDRVanNuysDialogFooter : UIView
{
    _Bool _calculateContentSize;
    UIButton *_dontShowAgainButton;
    UIButton *_confirmationButton;
    UIButton *_optionButton;
    UIButton *_cancelButton;
    UITextField *_textEntryField;
    unsigned long long _options;
    double _preferredContentWidth;
    UIButton *_otherButton;
    UILabel *_filledCustomButtonLabel;
    NSDictionary *_buttons;
    UIView *_topSeparator;
    UIView *_textEntryFieldLine;
}

+ (_Bool)requiresConstraintBasedLayout;
+ (id)footerOfWidth:(double)arg1 options:(unsigned long long)arg2;
@property(nonatomic) _Bool calculateContentSize; // @synthesize calculateContentSize=_calculateContentSize;
@property(retain, nonatomic) UIView *textEntryFieldLine; // @synthesize textEntryFieldLine=_textEntryFieldLine;
@property(retain, nonatomic) UIView *topSeparator; // @synthesize topSeparator=_topSeparator;
@property(retain, nonatomic) NSDictionary *buttons; // @synthesize buttons=_buttons;
@property(retain, nonatomic) UILabel *filledCustomButtonLabel; // @synthesize filledCustomButtonLabel=_filledCustomButtonLabel;
@property(retain, nonatomic) UIButton *otherButton; // @synthesize otherButton=_otherButton;
@property(nonatomic) double preferredContentWidth; // @synthesize preferredContentWidth=_preferredContentWidth;
@property(nonatomic) unsigned long long options; // @synthesize options=_options;
@property(retain, nonatomic) UITextField *textEntryField; // @synthesize textEntryField=_textEntryField;
@property(retain, nonatomic) UIButton *cancelButton; // @synthesize cancelButton=_cancelButton;
@property(readonly, nonatomic) UIButton *optionButton; // @synthesize optionButton=_optionButton;
@property(retain, nonatomic) UIButton *confirmationButton; // @synthesize confirmationButton=_confirmationButton;
@property(retain, nonatomic) UIButton *dontShowAgainButton; // @synthesize dontShowAgainButton=_dontShowAgainButton;
- (void).cxx_destruct;
- (void)scaleToDefault:(id)arg1;
- (void)scaleAnimation:(id)arg1;
- (void)scaleToSmall:(id)arg1;
- (void)applyAnimationsToButton:(id)arg1;
- (void)_removeSubviews;
- (void)_autolayoutSubviews;
- (void)updateConstraints;
- (void)deactivateConstraintsForView:(id)arg1;
- (double)heightOfFooterView:(id)arg1;
- (struct CGSize)intrinsicContentSize;
- (void)handleDontShowAgainButtonTap:(id)arg1;
- (void)_setupSubviews;
- (void)setFilledCustomButtonText:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1 options:(unsigned long long)arg2;

@end

