//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIViewController.h>

#import "TNDRGoingOutLocationModelDelegate-Protocol.h"
#import "TNDRNotificationWindowDelegate-Protocol.h"
#import "TNDRURLNavigableProtocol-Protocol.h"
#import "UISearchBarDelegate-Protocol.h"
#import "UISearchControllerDelegate-Protocol.h"
#import "UISearchResultsUpdating-Protocol.h"
#import "UITableViewDelegate-Protocol.h"

@class NSDictionary, NSSet, NSString, NSTimer, TNDRAnalyticsTracker, TNDRGoingOutLocationSearchViewModel, TNDRNotificationWindow, TNDRURLManager, UIActivityIndicatorView, UILabel, UISearchController, UITableView, UIView;
@protocol TNDRGoingOutLocationSearchDelegate, UIViewControllerAnimatedTransitioning;

@interface TNDRGoingOutLocationSearchViewController : UIViewController <UISearchBarDelegate, UISearchControllerDelegate, UISearchResultsUpdating, UITableViewDelegate, TNDRGoingOutLocationModelDelegate, TNDRNotificationWindowDelegate, TNDRURLNavigableProtocol>
{
    id <TNDRGoingOutLocationSearchDelegate> _delegate;
    TNDRGoingOutLocationSearchViewModel *_searchViewModel;
    UITableView *_tableView;
    UISearchController *_searchController;
    NSTimer *_searchTriggerTimer;
    UIView *_loadingView;
    UILabel *_loadingLabel;
    UIActivityIndicatorView *_spinner;
    NSSet *_viewedLocations;
}

+ (id)viewControllerNavigationKey;
@property(copy, nonatomic) NSSet *viewedLocations; // @synthesize viewedLocations=_viewedLocations;
@property(retain, nonatomic) UIActivityIndicatorView *spinner; // @synthesize spinner=_spinner;
@property(retain, nonatomic) UILabel *loadingLabel; // @synthesize loadingLabel=_loadingLabel;
@property(retain, nonatomic) UIView *loadingView; // @synthesize loadingView=_loadingView;
@property(retain, nonatomic) NSTimer *searchTriggerTimer; // @synthesize searchTriggerTimer=_searchTriggerTimer;
@property(retain, nonatomic) UISearchController *searchController; // @synthesize searchController=_searchController;
@property(retain, nonatomic) UITableView *tableView; // @synthesize tableView=_tableView;
@property(retain, nonatomic) TNDRGoingOutLocationSearchViewModel *searchViewModel; // @synthesize searchViewModel=_searchViewModel;
@property(nonatomic) __weak id <TNDRGoingOutLocationSearchDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)showNetworkFailureNotificationWindow;
- (void)didFailRefreshingLocationData;
- (void)didRefreshLocationData;
- (id)updateViewedLocationWithIndex:(long long)arg1;
- (void)tableView:(id)arg1 willDisplayCell:(id)arg2 forRowAtIndexPath:(id)arg3;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (double)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (void)scrollViewDidScroll:(id)arg1;
- (void)searchBarSearchButtonClicked:(id)arg1;
- (void)searchBarCancelButtonClicked:(id)arg1;
- (void)updateSearchResultsForSearchController:(id)arg1;
- (void)didPresentSearchController:(id)arg1;
- (void)currentUserPlacemarkDidUpdate:(id)arg1;
@property(readonly, copy, nonatomic) NSDictionary *viewsForAL;
@property(readonly, copy, nonatomic) NSDictionary *metricsForAL;
- (double)statusBarHeight;
- (void)setupLoadingConstraints;
- (void)setupConstraints;
- (void)setup;
@property(readonly, nonatomic) TNDRURLManager *urlManager;
- (long long)minutesTimeLeftUntilStatusChange;
- (long long)minutesSinceCreation;
- (id)userGoingOutStatus;
@property(readonly, nonatomic) TNDRAnalyticsTracker *analyticsTracker;
@property(readonly, nonatomic) TNDRNotificationWindow *notificationWindow;
- (void)viewWillAppear:(_Bool)arg1;
- (void)viewDidLoad;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;

// Remaining properties
@property(readonly, nonatomic) id <UIViewControllerAnimatedTransitioning> animationController;
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

