//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "TNDRAccessToken-Protocol.h"

@class NSDate, NSString;
@protocol AKFAccessToken;

@interface TNDRAccountKitAccessToken : NSObject <TNDRAccessToken>
{
    id <AKFAccessToken> _accountKitToken;
}

+ (void)attemptRefreshOfCurrentAccessTokenFromAccountKit:(id)arg1 completion:(CDUnknownBlockType)arg2;
+ (id)retrieveCurrentAccessTokenFromAccountKit:(id)arg1;
@property(retain, nonatomic) id <AKFAccessToken> accountKitToken; // @synthesize accountKitToken=_accountKitToken;
- (void).cxx_destruct;
@property(readonly, nonatomic) long long type;
- (id)initWithToken:(id)arg1;
@property(readonly, nonatomic) _Bool hasExpired;
@property(readonly, nonatomic) NSDate *lastRefresh;
@property(readonly, copy, nonatomic) NSString *token;
@property(readonly, copy, nonatomic) NSString *applicationID;
@property(readonly, copy, nonatomic) NSString *accountID;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

