//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

@class NSTimer, TNDRTutorialPressHeaderView, TNDRTutorialPressViewCircle;

@interface TNDRTutorialPressView : UIView
{
    _Bool _animationInProgress;
    _Bool _presented;
    _Bool _animating;
    TNDRTutorialPressViewCircle *_circleView;
    NSTimer *_timer;
    UIView *_container;
    TNDRTutorialPressHeaderView *_headerView;
    UIView *_dropShadowForHeaderView;
    struct CGPoint _circleCenterInContainer;
}

@property(nonatomic, getter=isAnimating) _Bool animating; // @synthesize animating=_animating;
@property(nonatomic, getter=isPresented) _Bool presented; // @synthesize presented=_presented;
@property(nonatomic, getter=isAnimationInProgress) _Bool animationInProgress; // @synthesize animationInProgress=_animationInProgress;
@property(nonatomic) struct CGPoint circleCenterInContainer; // @synthesize circleCenterInContainer=_circleCenterInContainer;
@property(retain, nonatomic) UIView *dropShadowForHeaderView; // @synthesize dropShadowForHeaderView=_dropShadowForHeaderView;
@property(retain, nonatomic) TNDRTutorialPressHeaderView *headerView; // @synthesize headerView=_headerView;
@property(retain, nonatomic) UIView *container; // @synthesize container=_container;
@property(retain, nonatomic) NSTimer *timer; // @synthesize timer=_timer;
@property(retain, nonatomic) TNDRTutorialPressViewCircle *circleView; // @synthesize circleView=_circleView;
- (void).cxx_destruct;
- (void)dealloc;
- (id)hitTest:(struct CGPoint)arg1 withEvent:(id)arg2;
- (void)animateOutCircle;
- (void)dismiss;
- (void)present;
- (void)layoutSubviews;
- (void)registerNotifications;
- (id)initWithText:(id)arg1 circleCenterInContainer:(struct CGPoint)arg2 container:(id)arg3;

@end

