//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSDictionary, NSString;

@interface TNDRCommonConnectionData : NSObject
{
    long long _degree;
    NSString *_degreeString;
    NSString *_connectionID;
    NSString *_name;
    NSDictionary *_imagesBySize;
}

@property(retain, nonatomic) NSDictionary *imagesBySize; // @synthesize imagesBySize=_imagesBySize;
@property(retain, nonatomic) NSString *name; // @synthesize name=_name;
@property(retain, nonatomic) NSString *connectionID; // @synthesize connectionID=_connectionID;
@property(retain, nonatomic) NSString *degreeString; // @synthesize degreeString=_degreeString;
@property(nonatomic) long long degree; // @synthesize degree=_degree;
- (void).cxx_destruct;
- (id)stringForSize:(long long)arg1;
- (id)avatarURLForSize:(long long)arg1;
- (void)parseJSONValues:(id)arg1;
- (id)initWithCommonConnectionJSON:(id)arg1;

@end

