//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSAttributedString, NSNumber, NSString, NSURL, UIColor, UIFont, UIView, UIViewController;

@interface TNDRAllSettingsItem : NSObject
{
    _Bool _maxIsRange;
    NSString *_itemTitle;
    NSString *_detailText;
    NSAttributedString *_attributedDetailText;
    UIView *_accessoryView;
    NSString *_identifierText;
    UIFont *_titleFont;
    UIFont *_detailFont;
    UIColor *_titleColor;
    UIColor *_detailColor;
    UIColor *_accessoryColor;
    long long _itemType;
    UIViewController *_viewController;
    Class _viewControllerClass;
    NSURL *_urlToOpen;
    long long _tag;
    NSString *_accessibilityIdentifier;
    CDUnknownBlockType _actionBlock;
    CDUnknownBlockType _trackingBlock;
    NSNumber *_minimumValue;
    NSNumber *_maximumValue;
    NSNumber *_minimumSpan;
    NSNumber *_startValue;
    NSNumber *_endValue;
    NSNumber *_startValueSave;
    NSNumber *_endValueSave;
    NSNumber *_maxRangeValue;
}

+ (id)defaultSettingsItem;
@property(retain, nonatomic) NSNumber *maxRangeValue; // @synthesize maxRangeValue=_maxRangeValue;
@property(nonatomic) _Bool maxIsRange; // @synthesize maxIsRange=_maxIsRange;
@property(retain, nonatomic) NSNumber *endValueSave; // @synthesize endValueSave=_endValueSave;
@property(retain, nonatomic) NSNumber *startValueSave; // @synthesize startValueSave=_startValueSave;
@property(retain, nonatomic) NSNumber *endValue; // @synthesize endValue=_endValue;
@property(retain, nonatomic) NSNumber *startValue; // @synthesize startValue=_startValue;
@property(retain, nonatomic) NSNumber *minimumSpan; // @synthesize minimumSpan=_minimumSpan;
@property(retain, nonatomic) NSNumber *maximumValue; // @synthesize maximumValue=_maximumValue;
@property(retain, nonatomic) NSNumber *minimumValue; // @synthesize minimumValue=_minimumValue;
@property(copy, nonatomic) CDUnknownBlockType trackingBlock; // @synthesize trackingBlock=_trackingBlock;
@property(copy, nonatomic) CDUnknownBlockType actionBlock; // @synthesize actionBlock=_actionBlock;
@property(retain, nonatomic) NSString *accessibilityIdentifier; // @synthesize accessibilityIdentifier=_accessibilityIdentifier;
@property(nonatomic) long long tag; // @synthesize tag=_tag;
@property(retain, nonatomic) NSURL *urlToOpen; // @synthesize urlToOpen=_urlToOpen;
@property(retain, nonatomic) Class viewControllerClass; // @synthesize viewControllerClass=_viewControllerClass;
@property(retain, nonatomic) UIViewController *viewController; // @synthesize viewController=_viewController;
@property(nonatomic) long long itemType; // @synthesize itemType=_itemType;
@property(retain, nonatomic) UIColor *accessoryColor; // @synthesize accessoryColor=_accessoryColor;
@property(retain, nonatomic) UIColor *detailColor; // @synthesize detailColor=_detailColor;
@property(retain, nonatomic) UIColor *titleColor; // @synthesize titleColor=_titleColor;
@property(retain, nonatomic) UIFont *detailFont; // @synthesize detailFont=_detailFont;
@property(retain, nonatomic) UIFont *titleFont; // @synthesize titleFont=_titleFont;
@property(retain, nonatomic) NSString *identifierText; // @synthesize identifierText=_identifierText;
@property(retain, nonatomic) UIView *accessoryView; // @synthesize accessoryView=_accessoryView;
@property(retain, nonatomic) NSAttributedString *attributedDetailText; // @synthesize attributedDetailText=_attributedDetailText;
@property(retain, nonatomic) NSString *detailText; // @synthesize detailText=_detailText;
@property(retain, nonatomic) NSString *itemTitle; // @synthesize itemTitle=_itemTitle;
- (void).cxx_destruct;

@end

