//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "TNDRHTTPSessionManager.h"

@protocol TNDRPerformanceTrackerProtocol;

@interface TNDRHTTPMediaClient : TNDRHTTPSessionManager
{
}

- (id)postJPEGImageToMediaServer:(id)arg1 clientPhotoId:(id)arg2 isMainPhoto:(_Bool)arg3 completion:(CDUnknownBlockType)arg4;
- (void)attemptPhotoUpload:(id)arg1 clientPhotoId:(id)arg2 isMainPhoto:(_Bool)arg3 completion:(CDUnknownBlockType)arg4;
- (void)uploadPhoto:(id)arg1 clientPhotoId:(id)arg2 isMainPhoto:(_Bool)arg3 completion:(CDUnknownBlockType)arg4;
- (void)setup;
- (id)initWithBaseURL:(id)arg1;
- (void)updateWithAPIToken:(id)arg1;
@property(readonly, nonatomic) id <TNDRPerformanceTrackerProtocol> performanceTracker;

@end

