//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIViewController.h>

#import "TNDRURLNavigableProtocol-Protocol.h"
#import "UICollectionViewDataSource-Protocol.h"
#import "UICollectionViewDelegate-Protocol.h"
#import "UIViewControllerTransitioningDelegate-Protocol.h"

@class NSArray, NSString, TNDRGIFPreviewViewerAnimationController, UICollectionView, UIImageView, UIPanGestureRecognizer, UITapGestureRecognizer, UIView;
@protocol TNDRGIFGalleryViewControllerDelegate;

@interface TNDRGIFGalleryViewController : UIViewController <UICollectionViewDataSource, UICollectionViewDelegate, TNDRURLNavigableProtocol, UIViewControllerTransitioningDelegate>
{
    TNDRGIFPreviewViewerAnimationController *_animationController;
    UICollectionView *_gifCollectionView;
    NSArray *_gifMesssages;
    id <TNDRGIFGalleryViewControllerDelegate> _delegate;
    long long _rowToShow;
    UIView *_cellBeingPanned;
    UIPanGestureRecognizer *_panGesture;
    UITapGestureRecognizer *_tapGesture;
    UIView *_dropDownShadowView;
    UIImageView *_gifAttributionImageView;
    struct CGRect _finalFrame;
}

+ (id)viewControllerNavigationKey;
@property(retain, nonatomic) UIImageView *gifAttributionImageView; // @synthesize gifAttributionImageView=_gifAttributionImageView;
@property(retain, nonatomic) UIView *dropDownShadowView; // @synthesize dropDownShadowView=_dropDownShadowView;
@property(nonatomic) struct CGRect finalFrame; // @synthesize finalFrame=_finalFrame;
@property(retain, nonatomic) UITapGestureRecognizer *tapGesture; // @synthesize tapGesture=_tapGesture;
@property(retain, nonatomic) UIPanGestureRecognizer *panGesture; // @synthesize panGesture=_panGesture;
@property(retain, nonatomic) UIView *cellBeingPanned; // @synthesize cellBeingPanned=_cellBeingPanned;
@property(nonatomic) long long rowToShow; // @synthesize rowToShow=_rowToShow;
@property(nonatomic) __weak id <TNDRGIFGalleryViewControllerDelegate> delegate; // @synthesize delegate=_delegate;
@property(copy, nonatomic) NSArray *gifMesssages; // @synthesize gifMesssages=_gifMesssages;
@property(retain, nonatomic) UICollectionView *gifCollectionView; // @synthesize gifCollectionView=_gifCollectionView;
@property(retain, nonatomic) TNDRGIFPreviewViewerAnimationController *animationController; // @synthesize animationController=_animationController;
- (void).cxx_destruct;
- (id)currentlyVisibleCell;
- (void)animateAttribution:(_Bool)arg1;
@property(readonly, nonatomic) struct CGRect animatedImageFinalFrame;
- (id)animationControllerForDismissedController:(id)arg1;
- (id)animationControllerForPresentedController:(id)arg1 presentingController:(id)arg2 sourceController:(id)arg3;
- (id)indexPathFromCellIndex:(long long)arg1;
- (long long)currentlyViewdCellIndexFromContentOffset:(struct CGPoint)arg1;
- (void)notifyDelegateOfCurrentlyViewedGIFWithContentOffset:(struct CGPoint)arg1;
- (void)scrollViewDidEndDecelerating:(id)arg1;
- (void)scrollViewWillEndDragging:(id)arg1 withVelocity:(struct CGPoint)arg2 targetContentOffset:(inout struct CGPoint *)arg3;
- (_Bool)shouldDismissFromTouchPoint:(struct CGPoint)arg1;
- (void)animateGIFCollectionViewUnderTouchPoint:(struct CGPoint)arg1 clearBackground:(_Bool)arg2;
- (void)dismiss;
- (void)handleExit:(struct CGPoint)arg1;
- (void)handleTap;
- (void)handlePanning:(id)arg1;
- (void)configureCell:(id)arg1 forItemAtIndexPath:(id)arg2;
- (id)collectionView:(id)arg1 cellForItemAtIndexPath:(id)arg2;
- (long long)collectionView:(id)arg1 numberOfItemsInSection:(long long)arg2;
- (void)didReceiveMemoryWarning;
- (void)setupCollectionView;
- (void)viewWillDisappear:(_Bool)arg1;
- (void)viewDidLayoutSubviews;
- (void)viewWillAppear:(_Bool)arg1;
- (void)viewDidLoad;
- (long long)preferredStatusBarStyle;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

