//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UICollectionViewCell.h>

@class NSAttributedString, NSString;

@interface TNDRPlusSubscriptionCollectionViewCell : UICollectionViewCell
{
    // Error parsing type: , name: numberOfMonths
    // Error parsing type: , name: discount
    // Error parsing type: , name: flavorText
    // Error parsing type: , name: borderVisibilityInsets
    // Error parsing type: , name: regularPriceForStrikeThrough
    // Error parsing type: , name: selfClass.storage
    // Error parsing type: , name: selectedAttributedString
    // Error parsing type: , name: borderContainerView
    // Error parsing type: , name: roundedPillLabel
    // Error parsing type: , name: numberOfMonthsLabel
    // Error parsing type: , name: pricePerMonthPreDiscountLabel
    // Error parsing type: , name: pricePerMonthLabel
    // Error parsing type: , name: savingsLabel
    // Error parsing type: , name: shrinkTransform
    // Error parsing type: , name: transformForDiscountReveal
    // Error parsing type: , name: transformForDiscountHidden
}

+ (id)selectedColorHex;
+ (id)shadowColor;
+ (id)numberOfMonthsNormalTextColor;
- (CDUnknownBlockType).cxx_destruct;
@property(nonatomic) _Bool selected;
- (_Bool)isSelected;
- (void)prepareForReuse;
- (void)prepareForDiscountPriceAnimation;
- (void)performDiscountAnimation;
- (id)initWithCoder:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;
@property(nonatomic, copy) NSString *regularPriceForStrikeThrough; // @synthesize regularPriceForStrikeThrough;
@property(nonatomic) struct UIEdgeInsets borderVisibilityInsets; // @synthesize borderVisibilityInsets;
@property(nonatomic, copy) NSString *flavorText; // @synthesize flavorText;
@property(nonatomic, copy) NSString *discount; // @synthesize discount;
@property(nonatomic, retain) NSAttributedString *numberOfMonths; // @synthesize numberOfMonths;
@property(nonatomic, copy) NSString *pricePerMonth;

@end

