//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UITableViewCell.h>

@class NSDictionary, TNDRSpotifyTrack, UIImageView, UILabel, UIView;

@interface TNDRSpotifyThemeSongCell : UITableViewCell
{
    TNDRSpotifyTrack *_spotifyTrack;
    UIImageView *_trackAlbumArtView;
    UIImageView *_spotifyLogoImageView;
    UIView *_separatorView;
    UIView *_trackInfoContainerView;
    UILabel *_titleLabel;
    UILabel *_artistLabel;
}

+ (id)reuseIdentifier;
@property(retain, nonatomic) UILabel *artistLabel; // @synthesize artistLabel=_artistLabel;
@property(retain, nonatomic) UILabel *titleLabel; // @synthesize titleLabel=_titleLabel;
@property(retain, nonatomic) UIView *trackInfoContainerView; // @synthesize trackInfoContainerView=_trackInfoContainerView;
@property(retain, nonatomic) UIView *separatorView; // @synthesize separatorView=_separatorView;
@property(retain, nonatomic) UIImageView *spotifyLogoImageView; // @synthesize spotifyLogoImageView=_spotifyLogoImageView;
@property(retain, nonatomic) UIImageView *trackAlbumArtView; // @synthesize trackAlbumArtView=_trackAlbumArtView;
@property(retain, nonatomic) TNDRSpotifyTrack *spotifyTrack; // @synthesize spotifyTrack=_spotifyTrack;
- (void).cxx_destruct;
- (void)prepareForReuse;
@property(readonly, copy, nonatomic) NSDictionary *viewsForAL;
@property(readonly, copy, nonatomic) NSDictionary *metricsForAL;
- (void)setupConstraints;
- (void)setup;
- (id)initWithStyle:(long long)arg1 reuseIdentifier:(id)arg2;

@end

