//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <QuartzCore/CALayer.h>

@class CAGradientLayer, CAShapeLayer, NSArray, NSString;

@interface TNDRGradientShapeLayer : CALayer
{
    CAGradientLayer *_gradientLayer;
    CAShapeLayer *_maskLayer;
    CAShapeLayer *_strokeLayer;
    NSArray *_gradientSubLayers;
}

@property(retain, nonatomic) NSArray *gradientSubLayers; // @synthesize gradientSubLayers=_gradientSubLayers;
@property(retain, nonatomic) CAShapeLayer *strokeLayer; // @synthesize strokeLayer=_strokeLayer;
@property(retain, nonatomic) CAShapeLayer *maskLayer; // @synthesize maskLayer=_maskLayer;
@property(retain, nonatomic) CAGradientLayer *gradientLayer; // @synthesize gradientLayer=_gradientLayer;
- (void).cxx_destruct;
- (id)animatableSublayers;
- (id)animationKeys;
- (void)removeAnimationForKey:(id)arg1;
- (void)removeAllAnimations;
- (id)animationForKey:(id)arg1;
- (void)addAnimation:(id)arg1 forKey:(id)arg2;
@property(copy, nonatomic) NSString *type;
@property(nonatomic) struct CGPoint endPoint;
@property(nonatomic) struct CGPoint startPoint;
@property(copy, nonatomic) NSArray *locations;
@property(copy, nonatomic) NSArray *colors;
@property(copy, nonatomic) NSArray *lineDashPattern;
@property(nonatomic) double lineDashPhase;
@property(copy, nonatomic) NSString *lineJoin;
@property(copy, nonatomic) NSString *lineCap;
@property(nonatomic) double miterLimit;
@property(nonatomic) double lineWidth;
@property(nonatomic) double strokeEnd;
@property(nonatomic) double strokeStart;
@property(nonatomic) struct CGColor *strokeColor;
@property(copy, nonatomic) NSString *fillRule;
@property(nonatomic) const struct CGPath *path;
- (void)setFrame:(struct CGRect)arg1;
- (void)setBounds:(struct CGRect)arg1;
- (void)setupLayers;
- (void)copyCustomPropertiesFromLayer:(id)arg1;
- (id)initWithLayer:(id)arg1;
- (id)init;

@end

