//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIViewController.h>

#import "TNDRActionSheetDelegate-Protocol.h"
#import "TNDRURLNavigableProtocol-Protocol.h"
#import "UITableViewDataSource-Protocol.h"
#import "UITableViewDelegate-Protocol.h"
#import "UITextFieldDelegate-Protocol.h"

@class NSString, TNDRActionSheet, TNDRDescriptionFooterView, UIActivityIndicatorView, UIImageView, UILabel, UITableView, UITableViewCell, UITextField;
@protocol UIViewControllerAnimatedTransitioning;

@interface TNDRWebURLViewController : UIViewController <UITableViewDataSource, UITableViewDelegate, UITextFieldDelegate, TNDRActionSheetDelegate, TNDRURLNavigableProtocol>
{
    _Bool _presentedModally;
    _Bool _dismissingProgrammatically;
    _Bool _confirmationButtonStateEnabled;
    UITableView *_tableView;
    UITableViewCell *_editingProfileURLCell;
    UITableViewCell *_customURLConfirmationCell;
    UITableViewCell *_deleteURLConfirmationCell;
    UITableViewCell *_characterCountingCell;
    UILabel *_customURLLabel;
    UILabel *_deleteURLLabel;
    UITextField *_profileURLTextField;
    NSString *_currentUsername;
    NSString *_initalUsername;
    UILabel *_baseURLabel;
    UILabel *_characterCountLabel;
    UIImageView *_activityIndicator;
    UIActivityIndicatorView *_spinner;
    TNDRDescriptionFooterView *_footerView;
    UILabel *_descriptionLabel;
    double _descriptionLabelMaximumWidth;
    TNDRActionSheet *_deleteURLConfirmationSheet;
}

+ (id)viewControllerNavigationKey;
@property(nonatomic) _Bool confirmationButtonStateEnabled; // @synthesize confirmationButtonStateEnabled=_confirmationButtonStateEnabled;
@property(nonatomic) _Bool dismissingProgrammatically; // @synthesize dismissingProgrammatically=_dismissingProgrammatically;
@property(retain, nonatomic) TNDRActionSheet *deleteURLConfirmationSheet; // @synthesize deleteURLConfirmationSheet=_deleteURLConfirmationSheet;
@property(nonatomic) double descriptionLabelMaximumWidth; // @synthesize descriptionLabelMaximumWidth=_descriptionLabelMaximumWidth;
@property(retain, nonatomic) UILabel *descriptionLabel; // @synthesize descriptionLabel=_descriptionLabel;
@property(retain, nonatomic) TNDRDescriptionFooterView *footerView; // @synthesize footerView=_footerView;
@property(retain, nonatomic) UIActivityIndicatorView *spinner; // @synthesize spinner=_spinner;
@property(retain, nonatomic) UIImageView *activityIndicator; // @synthesize activityIndicator=_activityIndicator;
@property(retain, nonatomic) UILabel *characterCountLabel; // @synthesize characterCountLabel=_characterCountLabel;
@property(retain, nonatomic) UILabel *baseURLabel; // @synthesize baseURLabel=_baseURLabel;
@property(retain, nonatomic) NSString *initalUsername; // @synthesize initalUsername=_initalUsername;
@property(retain, nonatomic) NSString *currentUsername; // @synthesize currentUsername=_currentUsername;
@property(retain, nonatomic) UITextField *profileURLTextField; // @synthesize profileURLTextField=_profileURLTextField;
@property(retain, nonatomic) UILabel *deleteURLLabel; // @synthesize deleteURLLabel=_deleteURLLabel;
@property(retain, nonatomic) UILabel *customURLLabel; // @synthesize customURLLabel=_customURLLabel;
@property(retain, nonatomic) UITableViewCell *characterCountingCell; // @synthesize characterCountingCell=_characterCountingCell;
@property(retain, nonatomic) UITableViewCell *deleteURLConfirmationCell; // @synthesize deleteURLConfirmationCell=_deleteURLConfirmationCell;
@property(retain, nonatomic) UITableViewCell *customURLConfirmationCell; // @synthesize customURLConfirmationCell=_customURLConfirmationCell;
@property(retain, nonatomic) UITableViewCell *editingProfileURLCell; // @synthesize editingProfileURLCell=_editingProfileURLCell;
@property(retain, nonatomic) UITableView *tableView; // @synthesize tableView=_tableView;
@property(nonatomic) _Bool presentedModally; // @synthesize presentedModally=_presentedModally;
- (void).cxx_destruct;
- (id)actionFeasiblilityTinderOrangeColor:(_Bool)arg1;
- (id)baseURLColor;
- (id)cellBorderOutlineColor;
- (struct CGRect)frameForLabelWithSameCenter:(id)arg1;
- (void)showSucessAlertWithMessage:(id)arg1;
- (void)showErrorAlertWithMessage:(id)arg1;
- (void)didTapAccessoryDoneButton;
- (void)actionSheet:(id)arg1 triggeredButtonWithID:(long long)arg2;
- (void)handleURLRemoval;
- (void)dismissViewController;
- (void)saveUsernameAndMoveBackToDiscoveryController;
- (void)handleURLConfirmation;
- (void)setEnabledState:(_Bool)arg1 withActivityType:(unsigned long long)arg2;
- (double)cellWidth;
- (_Bool)textFieldShouldEndEditing:(id)arg1;
- (_Bool)textFieldShouldReturn:(id)arg1;
- (_Bool)textField:(id)arg1 shouldChangeCharactersInRange:(struct _NSRange)arg2 replacementString:(id)arg3;
- (_Bool)textFieldShouldBeginEditing:(id)arg1;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (void)tableView:(id)arg1 willDisplayHeaderView:(id)arg2 forSection:(long long)arg3;
- (double)tableView:(id)arg1 heightForHeaderInSection:(long long)arg2;
- (double)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (long long)numberOfSectionsInTableView:(id)arg1;
- (void)setupDeleteURLConfirmationSheet;
- (void)setupTableView;
- (void)viewDidAppear:(_Bool)arg1;
- (void)didReceiveMemoryWarning;
- (void)setTheFrame;
- (void)viewWillDisappear:(_Bool)arg1;
- (void)viewWillAppear:(_Bool)arg1;
- (void)viewDidLoad;

// Remaining properties
@property(readonly, nonatomic) id <UIViewControllerAnimatedTransitioning> animationController;
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

