//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@interface TNDRMomentAttributes : NSObject
{
}

+ (id)tutorial;
+ (id)textSize;
+ (id)textOriginY;
+ (id)textAlignment;
+ (id)text;
+ (id)progress;
+ (id)photoID;
+ (id)momentID;
+ (id)localURL;
+ (id)liked;
+ (id)likeCount;
+ (id)filter;
+ (id)failedChoice;
+ (id)edits;
+ (id)created;
+ (id)camera;

@end

