//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIViewController.h>

#import "TNDRActionSheetDelegate-Protocol.h"
#import "UIPickerViewDataSource-Protocol.h"
#import "UIPickerViewDelegate-Protocol.h"
#import "UITableViewDataSource-Protocol.h"
#import "UITableViewDelegate-Protocol.h"

@class NSLayoutConstraint, NSNotificationCenter, NSString, TNDRActionSheet, TNDRExperimentCoordinator, TNDRExperimentVariable, UIPickerView, UITableView, UITapGestureRecognizer;

@interface TNDRExperimentViewController : UIViewController <UITableViewDataSource, UITableViewDelegate, UIPickerViewDataSource, UIPickerViewDelegate, TNDRActionSheetDelegate>
{
    UITableView *_tableView;
    UIPickerView *_pickerView;
    NSLayoutConstraint *_pickerViewBottomConstraint;
    UITapGestureRecognizer *_tapGestureRecognizer;
    TNDRExperimentVariable *_selectedExperimentVariable;
    TNDRActionSheet *_clearAllActionSheet;
}

@property(retain, nonatomic) TNDRActionSheet *clearAllActionSheet; // @synthesize clearAllActionSheet=_clearAllActionSheet;
@property(retain, nonatomic) TNDRExperimentVariable *selectedExperimentVariable; // @synthesize selectedExperimentVariable=_selectedExperimentVariable;
@property(retain, nonatomic) UITapGestureRecognizer *tapGestureRecognizer; // @synthesize tapGestureRecognizer=_tapGestureRecognizer;
@property(retain, nonatomic) NSLayoutConstraint *pickerViewBottomConstraint; // @synthesize pickerViewBottomConstraint=_pickerViewBottomConstraint;
@property(retain, nonatomic) UIPickerView *pickerView; // @synthesize pickerView=_pickerView;
@property(retain, nonatomic) UITableView *tableView; // @synthesize tableView=_tableView;
- (void).cxx_destruct;
- (void)actionSheet:(id)arg1 triggeredButtonWithID:(long long)arg2;
- (void)pickerView:(id)arg1 didSelectRow:(long long)arg2 inComponent:(long long)arg3;
- (id)pickerView:(id)arg1 titleForRow:(long long)arg2 forComponent:(long long)arg3;
- (long long)pickerView:(id)arg1 numberOfRowsInComponent:(long long)arg2;
- (long long)numberOfComponentsInPickerView:(id)arg1;
- (void)hidePicker;
- (void)showPicker;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 titleForHeaderInSection:(long long)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (long long)numberOfSectionsInTableView:(id)arg1;
- (void)didTapClearAllButton:(id)arg1;
- (void)didTapDoneButton:(id)arg1;
- (void)didReceiveExperimentUpdateNotification:(id)arg1;
- (void)dealloc;
- (void)registerForNotifications;
- (void)viewWillAppear:(_Bool)arg1;
- (void)setupConstraints;
- (void)addSubviews;
- (void)setup;
- (void)viewDidLoad;
@property(readonly, nonatomic) NSNotificationCenter *notificationCenter;
@property(readonly, nonatomic) TNDRExperimentCoordinator *experimentCoordinator;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

