//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

@class UIImageView;

@interface TNDRIntroToSpotifyDialogHeader : UIView
{
    UIImageView *_spotifyLogoImageView;
    UIImageView *_spotifyBackgroundView;
}

+ (_Bool)requiresConstraintBasedLayout;
@property(retain, nonatomic) UIImageView *spotifyBackgroundView; // @synthesize spotifyBackgroundView=_spotifyBackgroundView;
@property(retain, nonatomic) UIImageView *spotifyLogoImageView; // @synthesize spotifyLogoImageView=_spotifyLogoImageView;
- (void).cxx_destruct;
- (struct CGSize)intrinsicContentSize;
- (void)setupConstraints;
- (void)setup;
- (id)initWithFrame:(struct CGRect)arg1;

@end

