//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIViewController.h>

#import "TNDRDialogViewControllerDelegate-Protocol.h"
#import "TNDRNotificationWindowDelegate-Protocol.h"
#import "UIPageViewControllerDataSource-Protocol.h"
#import "UIPageViewControllerDelegate-Protocol.h"
#import "UITextViewDelegate-Protocol.h"
#import "UIViewControllerTransitioningDelegate-Protocol.h"

@class FXPageControl, NSArray, NSLayoutConstraint, NSNotificationCenter, NSString, TNDRAccessoryButton, TNDRAnalyticsTracker, TNDRAuthIntroPrivacyViewController, TNDRAuthIntroSlideViewController, TNDRExperimentCoordinator, TNDRGradientButton, TNDRLeanplumTracker, UIButton, UIGestureRecognizer, UIPageViewController, UITextView;
@protocol TNDRAuthIntroViewControllerDelegate;

@interface TNDRAuthIntroViewController : UIViewController <UIPageViewControllerDataSource, UIPageViewControllerDelegate, UITextViewDelegate, UIViewControllerTransitioningDelegate, TNDRDialogViewControllerDelegate, TNDRNotificationWindowDelegate>
{
    _Bool _hasCompletedVerification;
    _Bool _hasCompletedAnimation;
    _Bool _hasPresentedVerification;
    id <TNDRAuthIntroViewControllerDelegate> _delegate;
    UIPageViewController *_slidePageViewController;
    NSArray *_slideViewControllers;
    FXPageControl *_pageControl;
    TNDRGradientButton *_facebookButton;
    TNDRGradientButton *_smsButton;
    TNDRAccessoryButton *_privacyButton;
    UITextView *_termsTextView;
    UIButton *_closePrivacyButton;
    TNDRAuthIntroPrivacyViewController *_privacyViewController;
    NSLayoutConstraint *_privacyViewControllerBottomConstraint;
    UIGestureRecognizer *_fiveTapGestureRecognizer;
    long long _numberOfTaps;
    NSLayoutConstraint *_smsButtonHeightConstraint;
    NSLayoutConstraint *_smsButtonTopConstraint;
}

@property(retain, nonatomic) NSLayoutConstraint *smsButtonTopConstraint; // @synthesize smsButtonTopConstraint=_smsButtonTopConstraint;
@property(retain, nonatomic) NSLayoutConstraint *smsButtonHeightConstraint; // @synthesize smsButtonHeightConstraint=_smsButtonHeightConstraint;
@property(nonatomic) _Bool hasPresentedVerification; // @synthesize hasPresentedVerification=_hasPresentedVerification;
@property(nonatomic) long long numberOfTaps; // @synthesize numberOfTaps=_numberOfTaps;
@property(retain, nonatomic) UIGestureRecognizer *fiveTapGestureRecognizer; // @synthesize fiveTapGestureRecognizer=_fiveTapGestureRecognizer;
@property(retain, nonatomic) NSLayoutConstraint *privacyViewControllerBottomConstraint; // @synthesize privacyViewControllerBottomConstraint=_privacyViewControllerBottomConstraint;
@property(retain, nonatomic) TNDRAuthIntroPrivacyViewController *privacyViewController; // @synthesize privacyViewController=_privacyViewController;
@property(retain, nonatomic) UIButton *closePrivacyButton; // @synthesize closePrivacyButton=_closePrivacyButton;
@property(retain, nonatomic) UITextView *termsTextView; // @synthesize termsTextView=_termsTextView;
@property(retain, nonatomic) TNDRAccessoryButton *privacyButton; // @synthesize privacyButton=_privacyButton;
@property(retain, nonatomic) TNDRGradientButton *smsButton; // @synthesize smsButton=_smsButton;
@property(retain, nonatomic) TNDRGradientButton *facebookButton; // @synthesize facebookButton=_facebookButton;
@property(retain, nonatomic) FXPageControl *pageControl; // @synthesize pageControl=_pageControl;
@property(copy, nonatomic) NSArray *slideViewControllers; // @synthesize slideViewControllers=_slideViewControllers;
@property(retain, nonatomic) UIPageViewController *slidePageViewController; // @synthesize slidePageViewController=_slidePageViewController;
@property(nonatomic) _Bool hasCompletedAnimation; // @synthesize hasCompletedAnimation=_hasCompletedAnimation;
@property(nonatomic) _Bool hasCompletedVerification; // @synthesize hasCompletedVerification=_hasCompletedVerification;
@property(nonatomic) __weak id <TNDRAuthIntroViewControllerDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (_Bool)notificationWindow:(id)arg1 shouldAllowInteractionForNotification:(id)arg2;
- (void)didTapNotificationWindow:(id)arg1 notification:(id)arg2;
- (_Bool)notificationWindow:(id)arg1 shouldShowNotification:(id)arg2;
- (void)didReceiveExperimentUpdateNotification:(id)arg1;
- (void)dealloc;
- (void)registerForNotifications;
- (void)pageUp:(_Bool)arg1;
- (void)pageDownWithPrivacyViewType:(long long)arg1 animated:(_Bool)arg2;
- (void)didTap5Times:(id)arg1;
- (void)didTapClosePrivacyButton:(id)arg1;
- (void)didTapPrivacyButton:(id)arg1;
- (void)didTapSMSButton:(id)arg1;
- (void)didTapFacebookButton:(id)arg1;
- (void)didTapDoneButton:(id)arg1;
- (void)showURL:(id)arg1 title:(id)arg2;
- (_Bool)textView:(id)arg1 shouldInteractWithURL:(id)arg2 inRange:(struct _NSRange)arg3;
- (_Bool)textViewShouldBeginEditing:(id)arg1;
- (void)pageBackward;
- (void)pageForward;
- (void)pageControlValueChanged:(id)arg1;
- (void)pageViewController:(id)arg1 didFinishAnimating:(_Bool)arg2 previousViewControllers:(id)arg3 transitionCompleted:(_Bool)arg4;
- (id)pageViewController:(id)arg1 viewControllerAfterViewController:(id)arg2;
- (id)pageViewController:(id)arg1 viewControllerBeforeViewController:(id)arg2;
- (void)updateSMSButtonHeightConstraint;
- (long long)preferredStatusBarStyle;
- (void)setupConstraints;
- (void)addSubviews;
- (void)setup;
- (void)performInitialAnimation;
- (void)viewDidAppear:(_Bool)arg1;
- (void)hideAllSubviews;
- (void)prepareForInitialAnimation;
- (void)viewDidDisappear:(_Bool)arg1;
- (void)viewWillAppear:(_Bool)arg1;
- (void)viewDidLoad;
@property(readonly, nonatomic) double textFontSize;
@property(readonly, nonatomic) double buttonFontSize;
@property(readonly, nonatomic) struct CGSize closePrivacyButtonSize;
@property(readonly, nonatomic) double smsButtonTopPadding;
@property(readonly, nonatomic) double smsButtonHeight;
@property(readonly, nonatomic) double facebookButtonHeight;
@property(readonly, nonatomic) struct CGSize pageControlSize;
@property(readonly, nonatomic) TNDRAuthIntroSlideViewController *currentSlideViewController;
@property(readonly, nonatomic) _Bool shouldAnimate;
@property(readonly, nonatomic) NSNotificationCenter *notificationCenter;
@property(readonly, nonatomic) TNDRExperimentCoordinator *experimentCoordinator;
@property(readonly, nonatomic) TNDRLeanplumTracker *leanplumTracker;
@property(readonly, nonatomic) TNDRAnalyticsTracker *analyticsTracker;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

