//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "TNDRUnmatchReasonDialogV2ViewController.h"

@interface TNDRUnmatchReasonDialogV2ViewController (Tinder3)
- (void)didCompleteUnmatch:(id)arg1 success:(_Bool)arg2;
- (void)dialogViewControllerRequestsDismissal:(id)arg1 completion:(CDUnknownBlockType)arg2;
- (void)cancelUnmatchOtherReasonWithMessage:(id)arg1;
- (void)processUnmatchOtherReasonWithMessage:(id)arg1;
@end

