//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "TNDRBaseSlidingPagedController.h"

#import "TNDRChatViewControllerDelegate-Protocol.h"
#import "TNDRDialogViewControllerDelegate-Protocol.h"
#import "TNDRMatchesSearchDelegate-Protocol.h"
#import "TNDRNotificationWindowDelegate-Protocol.h"
#import "TNDRSlidingPagedViewControllerDelegate-Protocol.h"
#import "TNDRURLNavigableProtocol-Protocol.h"
#import "UIScrollViewDelegate-Protocol.h"
#import "UIViewControllerTransitioningDelegate-Protocol.h"

@class NSArray, NSDate, NSMutableArray, NSString, TNDRAnalyticsTracker, TNDRChatTitleButton, TNDRCoreDataService, TNDRCreateGroupViewController, TNDRCurrentUser, TNDRExperimentCoordinator, TNDRHomeViewController, TNDRMatchToChatAnimationController, TNDRMatchesViewController, TNDRPersonTitleButton, TNDRRecommendationViewController, TNDRSlackChatViewController, UIButton, UINavigationBar, UIView, _TtC6Tinder16ChatV2Experiment, _TtC6Tinder18ChatViewController;
@protocol UIViewControllerAnimatedTransitioning;

@interface TNDRSlidingPagedViewController : TNDRBaseSlidingPagedController <TNDRMatchesSearchDelegate, TNDRChatViewControllerDelegate, TNDRNotificationWindowDelegate, UIScrollViewDelegate, UIViewControllerTransitioningDelegate, TNDRDialogViewControllerDelegate, TNDRSlidingPagedViewControllerDelegate, TNDRURLNavigableProtocol>
{
    _Bool _isHandlingLogoutRequest;
    _Bool _showingPressAndHoldTutorial;
    _Bool _shouldShowBoostTooltipOnNextRecsAppearance;
    TNDRHomeViewController *_homeViewController;
    TNDRMatchesViewController *_matchesViewController;
    TNDRRecommendationViewController *_recommendationsViewController;
    long long _defaultIndex;
    TNDRMatchToChatAnimationController *_matchToChatAnimationController;
    TNDRChatTitleButton *_matchesTitleButton;
    TNDRPersonTitleButton *_homeTitleButton;
    double _curNormalizedScrollOffsetX;
    NSArray *_viewControllerKeys;
    TNDRSlackChatViewController *_chatViewController;
    _TtC6Tinder18ChatViewController *_chatV2ViewController;
    NSDate *_startPulseTime;
    id _logoutRequestObserver;
    UIButton *_promptForRatingButton;
    UIButton *_resetRatingButton;
    NSMutableArray *_queuedViewControllersToPresent;
    TNDRCreateGroupViewController *_createGroupVC;
}

+ (id)viewControllerNavigationKey;
+ (void)setupDefaultAppearanceForFonts;
@property(nonatomic) _Bool shouldShowBoostTooltipOnNextRecsAppearance; // @synthesize shouldShowBoostTooltipOnNextRecsAppearance=_shouldShowBoostTooltipOnNextRecsAppearance;
@property(retain, nonatomic) TNDRCreateGroupViewController *createGroupVC; // @synthesize createGroupVC=_createGroupVC;
@property(retain, nonatomic) NSMutableArray *queuedViewControllersToPresent; // @synthesize queuedViewControllersToPresent=_queuedViewControllersToPresent;
@property(nonatomic) _Bool showingPressAndHoldTutorial; // @synthesize showingPressAndHoldTutorial=_showingPressAndHoldTutorial;
@property(retain, nonatomic) UIButton *resetRatingButton; // @synthesize resetRatingButton=_resetRatingButton;
@property(retain, nonatomic) UIButton *promptForRatingButton; // @synthesize promptForRatingButton=_promptForRatingButton;
@property(retain, nonatomic) id logoutRequestObserver; // @synthesize logoutRequestObserver=_logoutRequestObserver;
@property(nonatomic) _Bool isHandlingLogoutRequest; // @synthesize isHandlingLogoutRequest=_isHandlingLogoutRequest;
@property(retain, nonatomic) NSDate *startPulseTime; // @synthesize startPulseTime=_startPulseTime;
@property(retain, nonatomic) _TtC6Tinder18ChatViewController *chatV2ViewController; // @synthesize chatV2ViewController=_chatV2ViewController;
@property(retain, nonatomic) TNDRSlackChatViewController *chatViewController; // @synthesize chatViewController=_chatViewController;
@property(copy, nonatomic) NSArray *viewControllerKeys; // @synthesize viewControllerKeys=_viewControllerKeys;
@property(nonatomic) double curNormalizedScrollOffsetX; // @synthesize curNormalizedScrollOffsetX=_curNormalizedScrollOffsetX;
@property(retain, nonatomic) TNDRPersonTitleButton *homeTitleButton; // @synthesize homeTitleButton=_homeTitleButton;
@property(retain, nonatomic) TNDRChatTitleButton *matchesTitleButton; // @synthesize matchesTitleButton=_matchesTitleButton;
@property(retain, nonatomic) TNDRMatchToChatAnimationController *matchToChatAnimationController; // @synthesize matchToChatAnimationController=_matchToChatAnimationController;
@property(nonatomic) long long defaultIndex; // @synthesize defaultIndex=_defaultIndex;
@property(retain, nonatomic) TNDRRecommendationViewController *recommendationsViewController; // @synthesize recommendationsViewController=_recommendationsViewController;
@property(retain, nonatomic) TNDRMatchesViewController *matchesViewController; // @synthesize matchesViewController=_matchesViewController;
@property(retain, nonatomic) TNDRHomeViewController *homeViewController; // @synthesize homeViewController=_homeViewController;
- (void).cxx_destruct;
- (void)transitionTo:(id)arg1 viewController:(id)arg2 optionsDict:(id)arg3 animated:(_Bool)arg4 completion:(CDUnknownBlockType)arg5;
- (id)interactionControllerForDismissal:(id)arg1;
- (id)animationControllerForDismissedController:(id)arg1;
- (id)animationControllerForPresentedController:(id)arg1 presentingController:(id)arg2 sourceController:(id)arg3;
- (void)createGroupDidRequestDismissalCompletion:(CDUnknownBlockType)arg1;
- (void)didTapChatCloseButton;
- (void)didBlockUser;
- (id)sourceViewForPeekPop;
- (void)didRequestToViewRecommendations;
- (void)didRequestToEnableSearching:(_Bool)arg1 animated:(_Bool)arg2;
- (void)adjustNavbarSeparatorOpacityForScrollOffsetX:(double)arg1 normalizedOffset:(double)arg2;
- (void)restoreSlidingPagedVCNavbar;
- (void)scrollViewDidScroll:(id)arg1;
- (void)handleStatusBarFrameChanged:(id)arg1;
- (id)buildHomeViewController;
- (void)preloadViewControllers;
- (void)presentChatForMatch:(id)arg1 withAvatarImage:(id)arg2 shortcut:(id)arg3 animated:(_Bool)arg4 completion:(CDUnknownBlockType)arg5 pushType:(id)arg6 origin:(unsigned long long)arg7;
- (void)presentChatForMatch:(id)arg1 withAvatarImage:(id)arg2 shortcut:(id)arg3 animated:(_Bool)arg4 completion:(CDUnknownBlockType)arg5;
- (void)dialogViewControllerRequestsDismissal:(id)arg1 completion:(CDUnknownBlockType)arg2;
- (void)checkAndResetHeightOfView;
- (void)checkAndResetPositionOfView;
- (void)showBoostTooltipIfNecessary;
- (void)handleChatBadgeNotification:(id)arg1;
- (void)handleOpenChatNotification:(id)arg1;
- (void)handleRequestedOpenChatNotification:(id)arg1;
- (void)handleSlidingPagedViewControllerDidChange:(id)arg1;
- (void)handleSlidingPagedViewControllerWillChange:(id)arg1;
- (void)handleStatusBarChangeRequest:(id)arg1;
- (void)handleNavigateToMatchesView:(id)arg1;
- (void)handleNavigateToGameView:(id)arg1;
- (void)handleUserDidLogout:(id)arg1;
- (void)handleAppDidBecomeActive:(id)arg1;
- (void)handleAppWillEnterForeground:(id)arg1;
- (void)handleAppDidEnterBackground:(id)arg1;
- (void)handleRequestedShowNavbarSeparator:(id)arg1;
- (void)registerNotifications;
- (void)moveNavigationBarToSlidingVCIfNeeded;
- (void)moveNavigationBarToView:(id)arg1 belowSubview:(id)arg2;
- (id)mainNavbarSnapshot;
@property(readonly, nonatomic) UIView *mainSlidingNavbarSnapshot;
- (void)showStatusBarIfPossible;
- (void)viewDidAppear:(_Bool)arg1;
- (void)viewWillAppear:(_Bool)arg1;
- (void)dealloc;
- (id)initWithDefaultTinderViewControllers;
- (id)initWithDefaultTinderSetup;
- (id)init;
@property(readonly, nonatomic) _TtC6Tinder16ChatV2Experiment *chatV2Experiment;
@property(readonly, nonatomic) TNDRExperimentCoordinator *experimentCoordinator;
@property(readonly, nonatomic) TNDRCoreDataService *dataService;
@property(readonly, nonatomic) TNDRAnalyticsTracker *analyticsTracker;
@property(readonly, nonatomic) TNDRCurrentUser *currentUser;
- (id)configureTinderGenericVC:(id)arg1;
- (void)showBoostTooltip;
- (void)handleQueueBoostTooltipNotification:(id)arg1;
- (void)handleBoostSummaryNotification:(id)arg1;
- (id)recsViewController;
- (void)handleShowFastMatchIntroNotification:(id)arg1;
- (void)handleUserDidLogoutNotification:(id)arg1;
- (void)handleShowToolTipNotification:(id)arg1;
- (void)handleHomeViewControllerRequestedHideBadgeNotification:(id)arg1;
- (void)handleGroupExpiredNotification:(id)arg1;
- (void)removeTooltipFromQueueIfNeeded;
- (void)handleCreateGroupFromRecs:(id)arg1;
- (void)handlePresentingCreateGroup:(id)arg1;
- (void)handleShowAddedToGroupNotification:(id)arg1;
- (void)handleShowNowOnTinderSocialDialogNotification:(id)arg1;
- (void)handleGroupStatusEndedEditing:(id)arg1;
- (void)handleGroupStatusBeganEditing:(id)arg1;
- (void)handleShowConnectSpotifyNotification:(id)arg1;
- (void)handleShowWhatsNewNotification:(id)arg1;
- (void)handleShowSelectWelcomeScreenNotification:(id)arg1;
- (_Bool)currentVCIsRecsVC;
- (_Bool)currentVCIsTopLevelVC;
- (void)presentQueuedVCIfPossible;
- (void)addVCToPresenterQueue:(id)arg1;
- (void)queueVCToPresent:(id)arg1;
- (void)registerTinderDialogNotifications;

// Remaining properties
@property(readonly, nonatomic) id <UIViewControllerAnimatedTransitioning> animationController;
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly, nonatomic) UINavigationBar *navigationBar;
@property(readonly) Class superclass;

@end

