//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIViewController.h>

#import "TNDRURLNavigableProtocol-Protocol.h"

@class NSString, UITextView;
@protocol UIViewControllerAnimatedTransitioning;

@interface TNDROSSLicenseDetailVC : UIViewController <TNDRURLNavigableProtocol>
{
    UITextView *_textView;
    NSString *_licenseTitle;
    NSString *_licenseText;
}

+ (id)viewControllerNavigationKey;
@property(copy, nonatomic) NSString *licenseText; // @synthesize licenseText=_licenseText;
@property(copy, nonatomic) NSString *licenseTitle; // @synthesize licenseTitle=_licenseTitle;
@property(retain, nonatomic) UITextView *textView; // @synthesize textView=_textView;
- (void).cxx_destruct;
- (void)setupConstraints;
- (void)viewDidLoad;

// Remaining properties
@property(readonly, nonatomic) id <UIViewControllerAnimatedTransitioning> animationController;
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

