//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UITableViewCell.h>

#import "UITextFieldDelegate-Protocol.h"

@class NSString, UIDatePicker, UITextField, UIToolbar;

@interface TNDRAgeVerificationTableViewCell : UITableViewCell <UITextFieldDelegate>
{
    UITextField *_dateTextField;
    UIDatePicker *_datePicker;
    UIToolbar *_datePickerAccessoryView;
}

@property(retain, nonatomic) UIToolbar *datePickerAccessoryView; // @synthesize datePickerAccessoryView=_datePickerAccessoryView;
@property(retain, nonatomic) UIDatePicker *datePicker; // @synthesize datePicker=_datePicker;
@property(retain, nonatomic) UITextField *dateTextField; // @synthesize dateTextField=_dateTextField;
- (void).cxx_destruct;
- (void)dateChanged:(id)arg1;
- (void)didTapAccessoryCancelButton:(id)arg1;
- (void)didTapAccessoryDoneButton:(id)arg1;
- (void)setupConstraints;
- (void)setup;
- (id)initWithStyle:(long long)arg1 reuseIdentifier:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

