//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "TNDRDialogViewController.h"

@protocol TNDRActionDialogViewControllerDelegate;

@interface TNDRNowOnTinderSocialDialogVC : TNDRDialogViewController
{
    id <TNDRActionDialogViewControllerDelegate> _actionDelegate;
}

@property(retain, nonatomic) id <TNDRActionDialogViewControllerDelegate> actionDelegate; // @synthesize actionDelegate=_actionDelegate;
- (void).cxx_destruct;
- (void)didTapConfirmation:(id)arg1;
- (void)didTapCancel:(id)arg1;
- (void)setupFooter;
- (void)setupHeader;
- (void)viewDidLoad;

@end

