//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <TTTAttributedLabel/TTTAttributedLabel.h>

@class TTTAttributedLabelLink, UILongPressGestureRecognizer;

@interface TNDRAttributedLabel : TTTAttributedLabel
{
    TTTAttributedLabelLink *_linkToCopy;
    UILongPressGestureRecognizer *_linkTapLongPressGR;
    UILongPressGestureRecognizer *_longPressCopyGR;
}

@property(retain, nonatomic) UILongPressGestureRecognizer *longPressCopyGR; // @synthesize longPressCopyGR=_longPressCopyGR;
@property(retain, nonatomic) UILongPressGestureRecognizer *linkTapLongPressGR; // @synthesize linkTapLongPressGR=_linkTapLongPressGR;
@property(retain, nonatomic) TTTAttributedLabelLink *linkToCopy; // @synthesize linkToCopy=_linkToCopy;
- (void).cxx_destruct;
- (_Bool)gestureRecognizer:(id)arg1 shouldRecognizeSimultaneouslyWithGestureRecognizer:(id)arg2;
- (_Bool)gestureRecognizer:(id)arg1 shouldReceiveTouch:(id)arg2;
- (void)copyLink:(id)arg1;
- (void)copy:(id)arg1;
- (_Bool)shouldBecomeFirstResponder;
- (_Bool)canPerformAction:(SEL)arg1 withSender:(id)arg2;
- (_Bool)canBecomeFirstResponder;
- (void)handleLongPressForCopy:(id)arg1;
- (id)linkAtPoint:(struct CGPoint)arg1;
- (id)additionalMenuItems;
- (void)commonInit;

@end

