//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UICollectionViewLayout.h>

@class NSMutableArray;

@interface TNDRLinearRowLayout : UICollectionViewLayout
{
    double _interItemPadding;
    double _outerItemPadding;
    long long _itemsPerPage;
    NSMutableArray *_layoutAttributes;
    double _totalContentWidth;
}

@property(nonatomic) double totalContentWidth; // @synthesize totalContentWidth=_totalContentWidth;
@property(retain, nonatomic) NSMutableArray *layoutAttributes; // @synthesize layoutAttributes=_layoutAttributes;
@property(nonatomic) long long itemsPerPage; // @synthesize itemsPerPage=_itemsPerPage;
@property(nonatomic) double outerItemPadding; // @synthesize outerItemPadding=_outerItemPadding;
@property(nonatomic) double interItemPadding; // @synthesize interItemPadding=_interItemPadding;
- (void).cxx_destruct;
- (_Bool)shouldInvalidateLayoutForBoundsChange:(struct CGRect)arg1;
- (id)layoutAttributesForItemAtIndexPath:(id)arg1;
- (id)layoutAttributesForElementsInRect:(struct CGRect)arg1;
- (struct CGSize)collectionViewContentSize;
- (void)prepareLayout;

@end

