//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "NSObject-Protocol.h"

@class NSString, TNDRBasePaywallViewController, TNDRPaywallManager, UIWindow;

@protocol TNDRPaywallManagerDelegate <NSObject>
- (void)dismissAndRepresentPaywallWithCompletion:(void (^)(TNDRBasePaywallViewController *))arg1;
- (TNDRBasePaywallViewController *)reloadPaywall;
- (UIWindow *)windowForHUD;
- (void)paywallPurchaseNotAllowed;
- (void)paywallPurchaseFailed;
- (void)paywallPurchaseSucceeded;
- (void)paywallPurchaseCancelled;

@optional
- (void)paywallManagerRequiresPurchaseConfirmation:(TNDRPaywallManager *)arg1 productIdentifier:(NSString *)arg2 newQuantity:(long long)arg3 confirmation:(void (^)(_Bool))arg4;
@end

