//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "TNDRWhatsNewDialogHeader.h"

#import "UICollectionViewDataSource-Protocol.h"
#import "UICollectionViewDelegate-Protocol.h"

@class CAGradientLayer, NSArray, NSString, TNDRWhatsNewIntrinsicHeightCalculatorCollectionView, UILabel;
@protocol TNDRWhatsNewGradientHeaderDelegate;

@interface TNDRWhatsNewGradientHeader : TNDRWhatsNewDialogHeader <UICollectionViewDelegate, UICollectionViewDataSource>
{
    id <TNDRWhatsNewGradientHeaderDelegate> _headerDelegate;
    TNDRWhatsNewIntrinsicHeightCalculatorCollectionView *_collectionView;
    CAGradientLayer *_backgroundHeaderGradient;
    UILabel *_headerLabel;
    NSArray *_whatsNewItems;
}

@property(copy, nonatomic) NSArray *whatsNewItems; // @synthesize whatsNewItems=_whatsNewItems;
@property(retain, nonatomic) UILabel *headerLabel; // @synthesize headerLabel=_headerLabel;
@property(retain, nonatomic) CAGradientLayer *backgroundHeaderGradient; // @synthesize backgroundHeaderGradient=_backgroundHeaderGradient;
@property(retain, nonatomic) TNDRWhatsNewIntrinsicHeightCalculatorCollectionView *collectionView; // @synthesize collectionView=_collectionView;
@property(nonatomic) __weak id <TNDRWhatsNewGradientHeaderDelegate> headerDelegate; // @synthesize headerDelegate=_headerDelegate;
- (void).cxx_destruct;
- (void)scrollViewDidScroll:(id)arg1;
- (long long)collectionView:(id)arg1 numberOfItemsInSection:(long long)arg2;
- (id)collectionView:(id)arg1 cellForItemAtIndexPath:(id)arg2;
- (void)adjustTextLabels;
- (void)layoutSubviews;
- (void)setupViews;
- (void)setupWhatsNewItemsWithItems:(id)arg1;
- (void)addHeaderGradient;
- (id)initWithFrame:(struct CGRect)arg1 items:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

