//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "TNDRCardStackViewController.h"

@interface TNDRCardStackViewController (Tinder4)
- (void)reloadRecommendations;
- (void)endUpdateRecommendations;
- (void)removeRecommendationAt:(long long)arg1;
- (void)insertRecommendationAt:(long long)arg1;
- (void)beginUpdateRecommendations;
@end

