//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "TNDRWebViewController.h"

@class NSString, NSURL;
@protocol TNDRAuthFacebookWebviewControllerDelegate;

@interface TNDRAuthFacebookWebviewController : TNDRWebViewController
{
    id <TNDRAuthFacebookWebviewControllerDelegate> _delegate;
}

@property(nonatomic) __weak id <TNDRAuthFacebookWebviewControllerDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)didTapCancelButton:(id)arg1;
- (void)webView:(id)arg1 didFailProvisionalNavigation:(id)arg2 withError:(id)arg3;
- (void)webView:(id)arg1 didFinishNavigation:(id)arg2;
- (void)webView:(id)arg1 decidePolicyForNavigationAction:(id)arg2 decisionHandler:(CDUnknownBlockType)arg3;
- (_Bool)htmlString:(id)arg1 hasStringContainedIn:(id)arg2;
- (_Bool)didEncounterUserCancellationInHTMLString:(id)arg1;
- (_Bool)didEncounterErrorInHTMLString:(id)arg1;
- (id)tokenStringFromURLString:(id)arg1;
- (_Bool)isPermittedURLString:(id)arg1;
- (_Bool)isFacebookAuthStartingURLString:(id)arg1;
- (_Bool)isRedirectURLString:(id)arg1;
- (void)deleteAllCookies;
- (void)viewWillAppear:(_Bool)arg1;
@property(readonly, copy, nonatomic) NSString *redirectURLString;
@property(readonly, nonatomic) NSURL *manualLoginURL;
@property(readonly, copy, nonatomic) NSString *requiredPermissionsCommaSeparatedString;

@end

