//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "AKFUIManager-Protocol.h"

@class NSError, NSString, TNDRAccountKitError, TNDRAnalyticsTracker;
@protocol AKFActionController, TNDRAccountKitUIManagerDelegate;

@interface TNDRAccountKitUIManager : NSObject <AKFUIManager>
{
    id <TNDRAccountKitUIManagerDelegate> _delegate;
    TNDRAccountKitError *_accountKitError;
    NSError *_error;
    id <AKFActionController> _actionController;
}

@property(retain, nonatomic) id <AKFActionController> actionController; // @synthesize actionController=_actionController;
@property(copy, nonatomic) NSError *error; // @synthesize error=_error;
@property(retain, nonatomic) TNDRAccountKitError *accountKitError; // @synthesize accountKitError=_accountKitError;
@property __weak id <TNDRAccountKitUIManagerDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (id)bodyViewForState:(unsigned long long)arg1;
- (id)headerViewForState:(unsigned long long)arg1;
- (id)theme;
@property(readonly, nonatomic) TNDRAnalyticsTracker *analyticsTracker;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

