//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

@class TNDRGradientShapeLayer, UIBezierPath, UILabel;

@interface TNDRGradientLabel : UIView
{
    UIBezierPath *_maskingPath;
    TNDRGradientShapeLayer *_gradientLayer;
    UILabel *_textLabel;
}

@property(retain, nonatomic) UILabel *textLabel; // @synthesize textLabel=_textLabel;
@property(retain, nonatomic) TNDRGradientShapeLayer *gradientLayer; // @synthesize gradientLayer=_gradientLayer;
@property(copy, nonatomic) UIBezierPath *maskingPath; // @synthesize maskingPath=_maskingPath;
- (void).cxx_destruct;
- (void)layoutSubviews;
- (id)initWithFrame:(struct CGRect)arg1;

@end

