//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

#import "UIGestureRecognizerDelegate-Protocol.h"

@class CAGradientLayer, NSString, UILabel, UITapGestureRecognizer;

@interface TNDRBubbleView : UIView <UIGestureRecognizerDelegate>
{
    _Bool _tapToDismiss;
    _Bool _tailAnchorsToBubble;
    _Bool _isAnimating;
    UILabel *_contentLabel;
    UIView *_anchorView;
    double _maxWidth;
    unsigned long long _justification;
    unsigned long long _innnerCircleDirection;
    unsigned long long _contentPosition;
    unsigned long long _pinDirection;
    unsigned long long _biggerCirclePosition;
    double _tailXOffset;
    double _originYOffset;
    UIView *_rectangleView;
    UIView *_biggerCircleView;
    UIView *_innerCircleView;
    CAGradientLayer *_statusGradient;
    double _gap;
    double _rectangleRadius;
    UITapGestureRecognizer *_tapGestureRecognizer;
    struct CGSize _contentViewSize;
    struct CGRect _contenViewRect;
}

@property(retain, nonatomic) UITapGestureRecognizer *tapGestureRecognizer; // @synthesize tapGestureRecognizer=_tapGestureRecognizer;
@property(nonatomic) _Bool isAnimating; // @synthesize isAnimating=_isAnimating;
@property(nonatomic) double rectangleRadius; // @synthesize rectangleRadius=_rectangleRadius;
@property(nonatomic) double gap; // @synthesize gap=_gap;
@property(nonatomic) struct CGRect contenViewRect; // @synthesize contenViewRect=_contenViewRect;
@property(nonatomic) struct CGSize contentViewSize; // @synthesize contentViewSize=_contentViewSize;
@property(retain, nonatomic) CAGradientLayer *statusGradient; // @synthesize statusGradient=_statusGradient;
@property(retain, nonatomic) UIView *innerCircleView; // @synthesize innerCircleView=_innerCircleView;
@property(retain, nonatomic) UIView *biggerCircleView; // @synthesize biggerCircleView=_biggerCircleView;
@property(retain, nonatomic) UIView *rectangleView; // @synthesize rectangleView=_rectangleView;
@property(nonatomic) _Bool tailAnchorsToBubble; // @synthesize tailAnchorsToBubble=_tailAnchorsToBubble;
@property(nonatomic) double originYOffset; // @synthesize originYOffset=_originYOffset;
@property(nonatomic) double tailXOffset; // @synthesize tailXOffset=_tailXOffset;
@property(nonatomic) unsigned long long biggerCirclePosition; // @synthesize biggerCirclePosition=_biggerCirclePosition;
@property(nonatomic) unsigned long long pinDirection; // @synthesize pinDirection=_pinDirection;
@property(nonatomic) unsigned long long contentPosition; // @synthesize contentPosition=_contentPosition;
@property(nonatomic) unsigned long long innnerCircleDirection; // @synthesize innnerCircleDirection=_innnerCircleDirection;
@property(nonatomic) unsigned long long justification; // @synthesize justification=_justification;
@property(nonatomic) _Bool tapToDismiss; // @synthesize tapToDismiss=_tapToDismiss;
@property(nonatomic) double maxWidth; // @synthesize maxWidth=_maxWidth;
@property(retain, nonatomic) UIView *anchorView; // @synthesize anchorView=_anchorView;
@property(retain, nonatomic) UILabel *contentLabel; // @synthesize contentLabel=_contentLabel;
- (void).cxx_destruct;
- (long long)languageDirection;
- (unsigned long long)localeAdjustedJustification:(unsigned long long)arg1;
- (unsigned long long)localeAdjustedBigCirclePosition:(unsigned long long)arg1;
- (unsigned long long)localeAdjustedInnerCirclePosition:(unsigned long long)arg1;
- (void)relayout;
- (void)setText:(id)arg1 animated:(_Bool)arg2;
- (void)setText:(id)arg1;
- (void)didTapBubble:(id)arg1;
- (void)setupGestureRecgonizer;
- (void)addShadowToView:(id)arg1;
@property(readonly, nonatomic) struct CGPoint RBRP;
@property(readonly, nonatomic) struct CGPoint RBLP;
@property(readonly, nonatomic) struct CGPoint RTRP;
@property(readonly, nonatomic) struct CGPoint RTLP;
- (void)animateOut;
- (void)animateIn;
- (void)animateInOut;
- (void)animateBiggerCircleWithPercent:(double)arg1;
- (void)animateInnerCircleWithPercent:(double)arg1;
- (void)pulse;
- (void)doneAnimating;
- (void)hiddenWithPercent:(double)arg1;
- (void)animateWithPercent:(double)arg1;
- (void)prepareForAnimation;
- (void)layoutShadows;
- (void)layoutSmallCircle;
- (void)handleLayoutOfBigCircleForCenterJustification;
- (void)layoutBigCircle;
- (void)layoutRectangle;
- (void)layoutContent;
- (void)layoutMe;
- (struct CGSize)sizeThatFits:(struct CGSize)arg1;
- (void)layoutSubviews;
- (void)setupViews;
- (id)initWithAnchorView:(id)arg1 justification:(unsigned long long)arg2 biggerCirclePosition:(unsigned long long)arg3 innerCellDirection:(unsigned long long)arg4 contentPosition:(unsigned long long)arg5 pinDirection:(unsigned long long)arg6 contentLabel:(id)arg7;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

