//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "NSObject-Protocol.h"

@class NSIndexPath, TNDRGetTinderPlusHeader;

@protocol TNDRPlusControlDelegate <NSObject>
@property(copy, nonatomic) CDUnknownBlockType actionAfterTinderPlus;

@optional
@property(nonatomic) __weak TNDRGetTinderPlusHeader *headerView;
- (void)didScroll;
- (void)openPassportViewController;
- (void)openBoostPaywall;
- (void)openSuperlikeALCPaywall;
- (void)openTinderPlusPaywallForIndexPath:(NSIndexPath *)arg1;
@end

