//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSArray, SPKHTTPClient, TNDREnvironmentModel, TNDRHTTPClient, TNDRHTTPContentClient, TNDRHTTPMediaClient, TNDRHTTPRequestClient;

@interface TNDREnvironmentHelper : NSObject
{
    NSArray *_environments;
    TNDRHTTPClient *_currentHTTPClient;
    TNDRHTTPRequestClient *_currentHTTPRequestClient;
    TNDRHTTPMediaClient *_currentHTTPMediaClient;
    TNDRHTTPContentClient *_currentHTTPContentClient;
    SPKHTTPClient *_currentSparksClient;
    TNDREnvironmentModel *_currentEnvironment;
    long long _currentEnvironmentIndex;
}

+ (id)sharedInstance;
@property(nonatomic) long long currentEnvironmentIndex; // @synthesize currentEnvironmentIndex=_currentEnvironmentIndex;
@property(retain, nonatomic) TNDREnvironmentModel *currentEnvironment; // @synthesize currentEnvironment=_currentEnvironment;
@property(retain, nonatomic) SPKHTTPClient *currentSparksClient; // @synthesize currentSparksClient=_currentSparksClient;
@property(retain, nonatomic) TNDRHTTPContentClient *currentHTTPContentClient; // @synthesize currentHTTPContentClient=_currentHTTPContentClient;
@property(retain, nonatomic) TNDRHTTPMediaClient *currentHTTPMediaClient; // @synthesize currentHTTPMediaClient=_currentHTTPMediaClient;
@property(retain, nonatomic) TNDRHTTPRequestClient *currentHTTPRequestClient; // @synthesize currentHTTPRequestClient=_currentHTTPRequestClient;
@property(retain, nonatomic) TNDRHTTPClient *currentHTTPClient; // @synthesize currentHTTPClient=_currentHTTPClient;
@property(copy, nonatomic) NSArray *environments; // @synthesize environments=_environments;
- (void).cxx_destruct;
- (void)updateAllAuthorizationHeadersWithAPIToken:(id)arg1;
- (void)clearAllAuthorizationHeaders;

@end

