//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "TNDRDialogViewControllerDelegate-Protocol.h"

@class NSString;

@protocol TNDRReportDialogViewControllerDelegate <TNDRDialogViewControllerDelegate>
- (void)requestDismissReportDialogCancelled;
- (void)requestDismissReportDialogReportSucceeded;

@optional
- (void)reportOtherReportTapped:(NSString *)arg1;
- (void)reportOtherCancelTapped:(NSString *)arg1;
- (void)reportReasonSelected:(unsigned long long)arg1 index:(long long)arg2;
- (void)reportCancelTapped;
@end

