//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UICollectionViewCell.h>

#import "TNDRChatCellNotificationViewDelegate-Protocol.h"
#import "TTTAttributedLabelDelegate-Protocol.h"

@class NSDate, NSIndexPath, NSLayoutConstraint, NSMutableArray, NSString, TNDRChatCellNotificationView, TNDRMessage, TNDRUser, UIButton, UIImageView, UILabel, UITapGestureRecognizer, UIView;
@protocol TNDRChatCellDelegate, TNDRChatContentViewProtocol, TTTAttributedLabelDelegate;

@interface TNDRChatCell : UICollectionViewCell <TNDRChatCellNotificationViewDelegate, TTTAttributedLabelDelegate>
{
    _Bool _showsTimestamp;
    _Bool _isLastCell;
    _Bool _showsError;
    _Bool _isBeingInserted;
    _Bool _showsMatchDate;
    _Bool _hasTail;
    _Bool _showsName;
    _Bool _allowLikes;
    _Bool _showsExpiration;
    _Bool _myGroupExpiresFirst;
    _Bool _isInternalGroupChat;
    _Bool _isPreviewingForPeek;
    UIImageView *_avatarImageView;
    TNDRChatCellNotificationView *_notificationView;
    UIButton *_heartView;
    UIView<TNDRChatContentViewProtocol> *_chatContentView;
    NSDate *_timestamp;
    unsigned long long _bubbleType;
    NSIndexPath *_indexPath;
    long long _superLike;
    NSDate *_matchDate;
    NSString *_matchName;
    TNDRMessage *_message;
    TNDRUser *_fromUser;
    NSDate *_expirationDate;
    id <TNDRChatCellDelegate> _delegate;
    id <TTTAttributedLabelDelegate> _textLabelDelegate;
    UILabel *_topTimestampLabel;
    UILabel *_timestampLabel;
    UILabel *_nameLabel;
    NSMutableArray *_leftBubbleConstraints;
    NSMutableArray *_rightBubbleConstraints;
    NSMutableArray *_centerBubbleConstraints;
    NSMutableArray *_topTimestampConstraints;
    NSMutableArray *_timestampConstraints;
    NSMutableArray *_notificationConstraints;
    NSMutableArray *_nameLabelConstraints;
    NSLayoutConstraint *_chatContentLeftEdge;
    NSLayoutConstraint *_rightChatContentRightEdge;
    NSLayoutConstraint *_topChatContentConstraint;
    NSLayoutConstraint *_topNameLabelConstraint;
    UIView *_cellContentView;
    UITapGestureRecognizer *_chatContentTapGestureRecognizer;
    UITapGestureRecognizer *_errorTapGestureRecognizer;
    UIImageView *_maskView;
    UILabel *_numberLikes;
}

+ (double)maxWidth;
+ (id)timeFormatter;
+ (id)matchDateFormatter;
+ (id)createdDateFormatter;
+ (id)dateFormatter;
@property(retain, nonatomic) UILabel *numberLikes; // @synthesize numberLikes=_numberLikes;
@property(retain, nonatomic) UIImageView *maskView; // @synthesize maskView=_maskView;
@property(retain, nonatomic) UITapGestureRecognizer *errorTapGestureRecognizer; // @synthesize errorTapGestureRecognizer=_errorTapGestureRecognizer;
@property(retain, nonatomic) UITapGestureRecognizer *chatContentTapGestureRecognizer; // @synthesize chatContentTapGestureRecognizer=_chatContentTapGestureRecognizer;
@property(retain, nonatomic) UIView *cellContentView; // @synthesize cellContentView=_cellContentView;
@property(retain, nonatomic) NSLayoutConstraint *topNameLabelConstraint; // @synthesize topNameLabelConstraint=_topNameLabelConstraint;
@property(retain, nonatomic) NSLayoutConstraint *topChatContentConstraint; // @synthesize topChatContentConstraint=_topChatContentConstraint;
@property(retain, nonatomic) NSLayoutConstraint *rightChatContentRightEdge; // @synthesize rightChatContentRightEdge=_rightChatContentRightEdge;
@property(retain, nonatomic) NSLayoutConstraint *chatContentLeftEdge; // @synthesize chatContentLeftEdge=_chatContentLeftEdge;
@property(retain, nonatomic) NSMutableArray *nameLabelConstraints; // @synthesize nameLabelConstraints=_nameLabelConstraints;
@property(retain, nonatomic) NSMutableArray *notificationConstraints; // @synthesize notificationConstraints=_notificationConstraints;
@property(retain, nonatomic) NSMutableArray *timestampConstraints; // @synthesize timestampConstraints=_timestampConstraints;
@property(retain, nonatomic) NSMutableArray *topTimestampConstraints; // @synthesize topTimestampConstraints=_topTimestampConstraints;
@property(retain, nonatomic) NSMutableArray *centerBubbleConstraints; // @synthesize centerBubbleConstraints=_centerBubbleConstraints;
@property(retain, nonatomic) NSMutableArray *rightBubbleConstraints; // @synthesize rightBubbleConstraints=_rightBubbleConstraints;
@property(retain, nonatomic) NSMutableArray *leftBubbleConstraints; // @synthesize leftBubbleConstraints=_leftBubbleConstraints;
@property(retain, nonatomic) UILabel *nameLabel; // @synthesize nameLabel=_nameLabel;
@property(retain, nonatomic) UILabel *timestampLabel; // @synthesize timestampLabel=_timestampLabel;
@property(retain, nonatomic) UILabel *topTimestampLabel; // @synthesize topTimestampLabel=_topTimestampLabel;
@property(nonatomic) _Bool isPreviewingForPeek; // @synthesize isPreviewingForPeek=_isPreviewingForPeek;
@property(nonatomic) __weak id <TTTAttributedLabelDelegate> textLabelDelegate; // @synthesize textLabelDelegate=_textLabelDelegate;
@property(nonatomic) __weak id <TNDRChatCellDelegate> delegate; // @synthesize delegate=_delegate;
@property(nonatomic) _Bool isInternalGroupChat; // @synthesize isInternalGroupChat=_isInternalGroupChat;
@property(nonatomic) _Bool myGroupExpiresFirst; // @synthesize myGroupExpiresFirst=_myGroupExpiresFirst;
@property(retain, nonatomic) NSDate *expirationDate; // @synthesize expirationDate=_expirationDate;
@property(nonatomic, getter=shouldShowExpiration) _Bool showsExpiration; // @synthesize showsExpiration=_showsExpiration;
@property(retain, nonatomic) TNDRUser *fromUser; // @synthesize fromUser=_fromUser;
@property(nonatomic) _Bool allowLikes; // @synthesize allowLikes=_allowLikes;
@property(retain, nonatomic) TNDRMessage *message; // @synthesize message=_message;
@property(nonatomic, getter=shouldShowName) _Bool showsName; // @synthesize showsName=_showsName;
@property(nonatomic) _Bool hasTail; // @synthesize hasTail=_hasTail;
@property(copy, nonatomic) NSString *matchName; // @synthesize matchName=_matchName;
@property(retain, nonatomic) NSDate *matchDate; // @synthesize matchDate=_matchDate;
@property(nonatomic, getter=shouldShowMatchDate) _Bool showsMatchDate; // @synthesize showsMatchDate=_showsMatchDate;
@property(nonatomic) long long superLike; // @synthesize superLike=_superLike;
@property(retain, nonatomic) NSIndexPath *indexPath; // @synthesize indexPath=_indexPath;
@property(nonatomic) _Bool isBeingInserted; // @synthesize isBeingInserted=_isBeingInserted;
@property(nonatomic, getter=shouldShowError) _Bool showsError; // @synthesize showsError=_showsError;
@property(nonatomic) _Bool isLastCell; // @synthesize isLastCell=_isLastCell;
@property(nonatomic) unsigned long long bubbleType; // @synthesize bubbleType=_bubbleType;
@property(retain, nonatomic) NSDate *timestamp; // @synthesize timestamp=_timestamp;
@property(nonatomic, getter=shouldShowTimestamp) _Bool showsTimestamp; // @synthesize showsTimestamp=_showsTimestamp;
@property(retain, nonatomic) UIView<TNDRChatContentViewProtocol> *chatContentView; // @synthesize chatContentView=_chatContentView;
@property(retain, nonatomic) UIButton *heartView; // @synthesize heartView=_heartView;
@property(retain, nonatomic) TNDRChatCellNotificationView *notificationView; // @synthesize notificationView=_notificationView;
@property(retain, nonatomic) UIImageView *avatarImageView; // @synthesize avatarImageView=_avatarImageView;
- (void).cxx_destruct;
- (void)attributedLabel:(id)arg1 didSelectLinkWithPhoneNumber:(id)arg2;
- (void)attributedLabel:(id)arg1 didSelectLinkWithAddress:(id)arg2;
- (void)attributedLabel:(id)arg1 didSelectLinkWithURL:(id)arg2;
- (void)prepareForReuse;
- (void)heartTapped:(id)arg1;
- (void)tappedContent;
- (void)didTapAvatar:(id)arg1;
- (void)restoreDefaultCellPosition;
- (void)restoreCellPosition;
- (void)translateToShowTimeWithTranslation:(double)arg1;
- (double)maxWidthChatCell;
- (void)setupTopNameLabelConstraints;
- (void)setupTopChatContentConstraints;
- (void)controlRightBubble;
- (void)controlConstraints;
- (_Bool)shouldInsetChatContentView;
- (id)maskForCell;
- (_Bool)cellNeedsMask;
- (void)setupCellWithMessage:(id)arg1 inContext:(id)arg2;
- (void)controlHeartVisibility;
- (void)setupNotificationConstraints;
- (void)setupNameLabelConstraints;
- (void)setupTopTimestampConstraints;
- (void)setupTimestampConstraints;
- (void)setupRightBubbleConstraints;
- (void)setupLeftBubbleConstraints;
- (void)setupChatContentViewVerticalConstraints;
- (void)setupContentViewConstraints;
- (void)setupConstraints;
- (void)layoutSubviews;
- (void)notificationViewDidFinishAnimating:(id)arg1;
- (void)setupNotificationView;
- (void)setupHeartView;
- (void)setupNameView;
- (void)setupTimestampLabels;
- (void)setupAvatarView;
- (void)setUpMasks;
- (void)setup;
- (id)initWithFrame:(struct CGRect)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

