//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "UICountingLabel.h"

@class TNDRCurrentUser;
@protocol TNDRCountingLabelDelegate;

@interface TNDRCountingLabel : UICountingLabel
{
    double _varianceAmount;
    double _varianceDelay;
    id <TNDRCountingLabelDelegate> _delegate;
    double _lastVarianceUpdate;
}

+ (double)variedNumberForValue:(double)arg1 variance:(double)arg2 capMaxValue:(double)arg3;
@property(nonatomic) double lastVarianceUpdate; // @synthesize lastVarianceUpdate=_lastVarianceUpdate;
@property(nonatomic) __weak id <TNDRCountingLabelDelegate> delegate; // @synthesize delegate=_delegate;
@property(nonatomic) double varianceDelay; // @synthesize varianceDelay=_varianceDelay;
@property(nonatomic) double varianceAmount; // @synthesize varianceAmount=_varianceAmount;
- (void).cxx_destruct;
- (void)setTextValue:(double)arg1;
@property(readonly, nonatomic) TNDRCurrentUser *currentUser;

@end

