//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "TNDRDialogViewControllerDelegate-Protocol.h"
#import "TNDRUnmatchReasonDialogViewControllerDelegate-Protocol.h"
#import "UIViewControllerTransitioningDelegate-Protocol.h"

@class NSString, TNDRBlockMatchInteractor, TNDRDialogViewController, TNDRErrorDialogVC, TNDRMatch, TNDRReportMatchInteractor, TNDRReportingV2Experiment, TNDRUnmatchGroupConfirmationDialogVC, TNDRUnmatchReasonDialogV2ViewController, TNDRUnmatchReasonDialogViewController;
@protocol TNDRBlockMatchDialogDelegate, TNDRBlockMatchTapEventDelegate, TNDRUnmatchAnalyticsClient;

@interface TNDRBlockMatch : NSObject <TNDRUnmatchReasonDialogViewControllerDelegate, UIViewControllerTransitioningDelegate, TNDRDialogViewControllerDelegate>
{
    TNDRUnmatchGroupConfirmationDialogVC *_unmatchGroupDialogViewController;
    TNDRDialogViewController *_unmatchViewController;
    id <TNDRBlockMatchDialogDelegate> _unmatchDialogDelegate;
    TNDRMatch *_match;
    CDUnknownBlockType _completion;
    TNDRErrorDialogVC *_errorDialogVC;
    id <TNDRBlockMatchTapEventDelegate> _tapEventDelegate;
    id <TNDRUnmatchAnalyticsClient> _analyticsClient;
    TNDRUnmatchReasonDialogViewController *_unmatchReasonsDialogViewController;
    TNDRUnmatchReasonDialogV2ViewController *_unmatchReasonsExperimentDialogVC;
    TNDRReportMatchInteractor *_reportMatchInteractor;
    TNDRBlockMatchInteractor *_blockMatchInteractor;
}

@property(retain, nonatomic) TNDRBlockMatchInteractor *blockMatchInteractor; // @synthesize blockMatchInteractor=_blockMatchInteractor;
@property(retain, nonatomic) TNDRReportMatchInteractor *reportMatchInteractor; // @synthesize reportMatchInteractor=_reportMatchInteractor;
@property(retain, nonatomic) TNDRUnmatchReasonDialogV2ViewController *unmatchReasonsExperimentDialogVC; // @synthesize unmatchReasonsExperimentDialogVC=_unmatchReasonsExperimentDialogVC;
@property(retain, nonatomic) TNDRUnmatchReasonDialogViewController *unmatchReasonsDialogViewController; // @synthesize unmatchReasonsDialogViewController=_unmatchReasonsDialogViewController;
@property(nonatomic) __weak id <TNDRUnmatchAnalyticsClient> analyticsClient; // @synthesize analyticsClient=_analyticsClient;
@property(nonatomic) __weak id <TNDRBlockMatchTapEventDelegate> tapEventDelegate; // @synthesize tapEventDelegate=_tapEventDelegate;
@property(retain, nonatomic) TNDRErrorDialogVC *errorDialogVC; // @synthesize errorDialogVC=_errorDialogVC;
@property(copy) CDUnknownBlockType completion; // @synthesize completion=_completion;
@property(retain, nonatomic) TNDRMatch *match; // @synthesize match=_match;
@property(nonatomic) __weak id <TNDRBlockMatchDialogDelegate> unmatchDialogDelegate; // @synthesize unmatchDialogDelegate=_unmatchDialogDelegate;
@property(retain, nonatomic) TNDRDialogViewController *unmatchViewController; // @synthesize unmatchViewController=_unmatchViewController;
@property(retain, nonatomic) TNDRUnmatchGroupConfirmationDialogVC *unmatchGroupDialogViewController; // @synthesize unmatchGroupDialogViewController=_unmatchGroupDialogViewController;
- (void).cxx_destruct;
- (id)animationControllerForDismissedController:(id)arg1;
- (id)animationControllerForPresentedController:(id)arg1 presentingController:(id)arg2 sourceController:(id)arg3;
- (void)requestErrorDialog;
- (id)errorDetailText;
- (id)errorTitleText;
- (void)showBlockAndReportFailed;
- (void)reportWithBlockAnalytics:(id)arg1 user:(id)arg2 reason:(id)arg3 message:(id)arg4;
- (void)completeBlockAndReport:(_Bool)arg1 reason:(unsigned long long)arg2;
- (void)showBlockAndReportInProgress;
- (void)didCompleteUnmatch:(_Bool)arg1;
- (void)dialogViewControllerRequestsDismissal:(id)arg1 completion:(CDUnknownBlockType)arg2;
- (void)requestDismissUnmatchCancelled;
- (void)requestDismissUnmatchDialogForReason:(unsigned long long)arg1 message:(id)arg2;
- (void)dialogViewController:(id)arg1 cancelTappedWithReason:(unsigned long long)arg2;
- (void)dialogViewController:(id)arg1 unmatchTappedWithReason:(unsigned long long)arg2;
- (void)dialogViewController:(id)arg1 reasonTapped:(unsigned long long)arg2;
- (id)prepareUnmatchGroupVC;
- (id)viewControllerForUserUnmatch;
- (id)blockMatchWithReasons:(id)arg1 tapEventDelegate:(id)arg2 analyticsClient:(id)arg3 completion:(CDUnknownBlockType)arg4;
@property(readonly, nonatomic) TNDRReportingV2Experiment *reportingExperiment;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

