//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "NSObject-Protocol.h"

@class TNDRGIFModel, TNDRGIFStripDataSource;

@protocol TNDRGIFStripDataSourceDelegate <NSObject>
- (void)GIFStrip:(TNDRGIFStripDataSource *)arg1 didSelectGIF:(TNDRGIFModel *)arg2 inPosition:(long long)arg3;

@optional
- (void)GIFStrip:(TNDRGIFStripDataSource *)arg1 willDisplayGIF:(TNDRGIFModel *)arg2 inPosition:(long long)arg3;
@end

