//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

@class CALayer, NSNotificationCenter, NSTimer, TNDRCoreDataService, TNDRCurrentUser, TNDRMessageStandardsExperiment, UIImageView, UILabel;

@interface TNDRNoRecommendationsView : UIView
{
    _Bool _nobodyAvailable;
    _Bool _noGroupsAvailable;
    _Bool _messageStandardsVisible;
    _Bool _avatarLoaded;
    long long _cardStackType;
    UILabel *_messageStandardsLabel;
    UILabel *_nobodyLabel;
    UILabel *_noGroupsLabel;
    NSTimer *_timer;
    CALayer *_containerLayer;
    UIImageView *_avatarImageView;
}

@property(nonatomic) _Bool avatarLoaded; // @synthesize avatarLoaded=_avatarLoaded;
@property(retain, nonatomic) UIImageView *avatarImageView; // @synthesize avatarImageView=_avatarImageView;
@property(retain, nonatomic) CALayer *containerLayer; // @synthesize containerLayer=_containerLayer;
@property(retain, nonatomic) NSTimer *timer; // @synthesize timer=_timer;
@property(nonatomic, getter=areMessageStandardsVisible) _Bool messageStandardsVisible; // @synthesize messageStandardsVisible=_messageStandardsVisible;
@property(nonatomic, getter=areNoGroupsAvailable) _Bool noGroupsAvailable; // @synthesize noGroupsAvailable=_noGroupsAvailable;
@property(nonatomic, getter=isNobodyAvailable) _Bool nobodyAvailable; // @synthesize nobodyAvailable=_nobodyAvailable;
@property(retain, nonatomic) UILabel *noGroupsLabel; // @synthesize noGroupsLabel=_noGroupsLabel;
@property(retain, nonatomic) UILabel *nobodyLabel; // @synthesize nobodyLabel=_nobodyLabel;
@property(retain, nonatomic) UILabel *messageStandardsLabel; // @synthesize messageStandardsLabel=_messageStandardsLabel;
@property(nonatomic) long long cardStackType; // @synthesize cardStackType=_cardStackType;
- (void).cxx_destruct;
- (id)messageStandardsAttributedText;
- (void)handleApplicationDidEnterBackgroundNotification:(id)arg1;
- (void)handleNoGroupsNearbyNotification:(id)arg1;
- (void)handleNobodyNearbyNotification:(id)arg1;
- (void)animateMessageStandardsLabelVisible:(_Bool)arg1;
- (void)animateShowNoOneAvailableStackType:(long long)arg1 completion:(CDUnknownBlockType)arg2;
- (void)animateHideNoOneAvailableStackType:(long long)arg1 completion:(CDUnknownBlockType)arg2;
- (void)toggleMessageStandardsVisible;
- (void)setNoGroupsAvailable:(_Bool)arg1 completion:(CDUnknownBlockType)arg2;
- (void)setNobodyAvailable:(_Bool)arg1 completion:(CDUnknownBlockType)arg2;
- (void)animateOut:(CDUnknownBlockType)arg1;
- (void)animateIn:(CDUnknownBlockType)arg1;
- (void)ping:(id)arg1;
- (void)loadAvatarURL:(id)arg1;
- (void)updateAvatar:(id)arg1;
- (void)resetAvatar:(id)arg1;
- (void)handleSwitchToTinderCoreButtonTapped:(id)arg1;
- (void)handleTap:(id)arg1;
- (void)showLogoInPulse;
- (void)stopPingTimer;
- (void)startPingTimer;
- (void)setupNotifications;
- (id)hitTest:(struct CGPoint)arg1 withEvent:(id)arg2;
- (void)layoutSubviews;
- (void)setup;
- (id)initWithFrame:(struct CGRect)arg1;
- (void)dealloc;
- (id)nobodyString;
@property(readonly) TNDRCurrentUser *currentUser;
@property(readonly) TNDRCoreDataService *dataService;
@property(readonly, nonatomic) NSNotificationCenter *notificationCenter;
@property(readonly, nonatomic) TNDRMessageStandardsExperiment *messageStandardsExperiment;

@end

