//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "TNDRWhatsNewDialogViewController.h"

#import "TNDRURLNavigableProtocol-Protocol.h"

@class NSNotificationCenter, NSString, TNDRCurrentUser, TNDRDataManager, TNDRHTTPClient, TNDRIntroToSpotifyDialogFooter, TNDRIntroToSpotifyDialogHeader, TNDRLeanplumUserAttributeTracker, TNDRNotificationWindow, TNDRSpotifyAuthenticator, TNDRURLManager;
@protocol UIViewControllerAnimatedTransitioning;

@interface TNDRIntroducingSpotifyDialogVC : TNDRWhatsNewDialogViewController <TNDRURLNavigableProtocol>
{
}

+ (id)viewControllerNavigationKey;
- (void)processCurrentUserSync:(id)arg1;
- (void)showExternalServiceConnectedbannerView;
- (void)showErrorNotificationBannerView;
- (void)markSpotifyWhatsNewDialogAsViewed;
- (void)cancelButtonPressed:(id)arg1;
- (void)processSuccessfulProfileSyncWithResponse:(id)arg1;
- (void)processSuccessfulSpotifyAuthenticationWithAuthCode:(id)arg1;
- (void)actionButtonPressed:(id)arg1;
@property(readonly, nonatomic) TNDRHTTPClient *httpClient;
@property(readonly, nonatomic) TNDRCurrentUser *currentUser;
@property(readonly, nonatomic) TNDRDataManager *sharedDataManager;
@property(readonly, nonatomic) TNDRSpotifyAuthenticator *authenticator;
@property(readonly, nonatomic) TNDRURLManager *urlManager;
@property(readonly, nonatomic) TNDRNotificationWindow *notificationWindow;
@property(readonly, nonatomic) NSNotificationCenter *notificationCenter;
- (void)setupFooterView;
- (void)setupHeaderView;
- (void)viewDidAppear:(_Bool)arg1;
- (void)viewDidLoad;
@property(readonly, nonatomic) TNDRLeanplumUserAttributeTracker *leanplumAttributeTracker;

// Remaining properties
@property(readonly, nonatomic) id <UIViewControllerAnimatedTransitioning> animationController;
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(retain, nonatomic) TNDRIntroToSpotifyDialogFooter *footerView; // @dynamic footerView;
@property(readonly) unsigned long long hash;
@property(retain, nonatomic) TNDRIntroToSpotifyDialogHeader *headerView; // @dynamic headerView;
@property(readonly) Class superclass;

@end

