//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "NSObject-Protocol.h"

@class NSDictionary;

@protocol TNDRAppServiceLevelDelegate <NSObject>
- (void)loadGUIServicesWithOptions:(NSDictionary *)arg1;
- (void)loadAPIServicesWithOptions:(NSDictionary *)arg1;
- (void)loadNetworkServicesWithOptions:(NSDictionary *)arg1;
- (void)loadBasicServicesWithOptions:(NSDictionary *)arg1;
@end

