//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "NSFetchedResultsControllerDelegate-Protocol.h"
#import "UICollectionViewDataSource-Protocol.h"

@class NSFetchedResultsController, NSMutableArray, NSNotificationCenter, NSString, TNDRCoreDataService, TNDRMatchesGoingOutExperiment, TNDRUser, UICollectionView;
@protocol TNDRMatchesGoingOutViewModelDelegate;

@interface TNDRMatchesGoingOutViewModel : NSObject <UICollectionViewDataSource, NSFetchedResultsControllerDelegate>
{
    _Bool _animateInCurrentUserStatus;
    id <TNDRMatchesGoingOutViewModelDelegate> _delegate;
    long long _numberOfMatchesInGoingOut;
    NSFetchedResultsController *_fetchedResultsController;
    UICollectionView *_collectionView;
    NSMutableArray *_fetchResultsControllerChanges;
    TNDRUser *_currentUser;
}

@property(nonatomic, getter=isAnimatingInCurrentUserStatus) _Bool animateInCurrentUserStatus; // @synthesize animateInCurrentUserStatus=_animateInCurrentUserStatus;
@property(retain, nonatomic) TNDRUser *currentUser; // @synthesize currentUser=_currentUser;
@property(retain, nonatomic) NSMutableArray *fetchResultsControllerChanges; // @synthesize fetchResultsControllerChanges=_fetchResultsControllerChanges;
@property(retain, nonatomic) UICollectionView *collectionView; // @synthesize collectionView=_collectionView;
@property(retain, nonatomic) NSFetchedResultsController *fetchedResultsController; // @synthesize fetchedResultsController=_fetchedResultsController;
@property(nonatomic) long long numberOfMatchesInGoingOut; // @synthesize numberOfMatchesInGoingOut=_numberOfMatchesInGoingOut;
@property(nonatomic) __weak id <TNDRMatchesGoingOutViewModelDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (_Bool)hasRelevantGoingOutStatus;
- (void)dealloc;
- (void)handleClearNotification;
- (void)setupClearInfoNotification;
- (void)notifyDelegateWhereYesterdaysStatusBegins;
- (void)notifyDelegateWithNumberOfMatchStatuses:(long long)arg1;
- (void)refreshCurrentUserStatusAnimated:(_Bool)arg1;
- (void)refreshExpirationClocks;
- (id)matchForIndexPath:(id)arg1;
- (id)adjustIndexPath:(id)arg1 itemOffset:(long long)arg2;
- (id)goingOutStatusForIndexPath:(id)arg1;
- (void)controllerDidChangeContent:(id)arg1;
- (void)controller:(id)arg1 didChangeObject:(id)arg2 atIndexPath:(id)arg3 forChangeType:(unsigned long long)arg4 newIndexPath:(id)arg5;
- (void)controllerWillChangeContent:(id)arg1;
- (void)configureV2Cell:(id)arg1 forItemAtIndexPath:(id)arg2;
- (void)configureCell:(id)arg1 forItemAtIndexPath:(id)arg2;
- (id)collectionView:(id)arg1 cellForItemAtIndexPath:(id)arg2;
- (long long)collectionView:(id)arg1 numberOfItemsInSection:(long long)arg2;
- (id)initWithCollectionView:(id)arg1;
@property(readonly, nonatomic) NSNotificationCenter *defaultNotificationCenter;
@property(readonly, nonatomic) TNDRCoreDataService *dataService;
@property(readonly, nonatomic) TNDRMatchesGoingOutExperiment *goingOutExperiment;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

