//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSArray, NSAttributedString, NSDate, NSString, NSURL, TNDRCoreDataService, TNDRCurrentUser, TNDRJobViewModel, TNDRSchoolViewModel, UIImage;

@interface TNDRHomeViewModel : NSObject
{
    double _timeIntervalTilExpiration;
    TNDRCurrentUser *_currentUser;
    TNDRJobViewModel *_jobVM;
    TNDRSchoolViewModel *_schoolVM;
}

@property(retain, nonatomic) TNDRSchoolViewModel *schoolVM; // @synthesize schoolVM=_schoolVM;
@property(retain, nonatomic) TNDRJobViewModel *jobVM; // @synthesize jobVM=_jobVM;
@property(retain, nonatomic) TNDRCurrentUser *currentUser; // @synthesize currentUser=_currentUser;
@property(readonly, nonatomic) double timeIntervalTilExpiration; // @synthesize timeIntervalTilExpiration=_timeIntervalTilExpiration;
- (void).cxx_destruct;
- (id)attributedStringForLocationText:(id)arg1 traveling:(_Bool)arg2;
- (id)locationForCurrentUser:(id)arg1;
- (void)updateCurrentStatus:(id)arg1;
@property(readonly, nonatomic, getter=isCurrentUserTinderPlusSubscriber) _Bool subscriber;
- (id)userAvatarImageURLForPhotoID:(id)arg1;
@property(readonly, nonatomic) NSURL *userAvatarImageURL;
- (id)userAvatarImageURLForSize:(double)arg1;
@property(readonly, nonatomic) _Bool isCurrentUserSelectMember;
@property(readonly, nonatomic) UIImage *mainBadge;
@property(readonly, nonatomic) NSString *bio;
@property(readonly, nonatomic) NSString *schoolTitle;
@property(readonly, nonatomic) NSString *jobTitle;
@property(readonly, nonatomic) NSAttributedString *currentPassportLocation;
@property(readonly, nonatomic, getter=isCurrentUserTraveling) _Bool currentUserTraveling;
@property(readonly, nonatomic) NSString *ageString;
@property(readonly, nonatomic) NSString *firstName;
@property(readonly, nonatomic) NSString *groupId;
@property(readonly, nonatomic) _Bool groupAlmostExpired;
@property(readonly, nonatomic) NSString *groupStatus;
@property(readonly, nonatomic) NSDate *groupExpirationDate;
- (id)groupTitleFromMembersArray:(id)arg1;
- (id)sortedArrayWithMeInFront:(id)arg1;
@property(readonly, nonatomic) NSArray *groupMembersWithOwner;
@property(readonly, nonatomic) NSArray *groupMembersWithoutMe;
@property(readonly, nonatomic, getter=isGroupExpired) _Bool groupExpired;
@property(readonly, nonatomic, getter=isCurrentUserOwnerOfGroup) _Bool currentUserIsOwnerOfGroup;
@property(readonly, nonatomic, getter=isCurrentUserMemberOfGroup) _Bool currentUserIsMemberOfGroup;
- (_Bool)groupsDiscoverable;
@property(readonly, nonatomic) _Bool isCurrentUserOptedIntoGroups;
@property(readonly, nonatomic) _Bool groupsEnabled;
@property(readonly, nonatomic) _Bool isProfileV2Enabled;
@property(readonly, nonatomic) TNDRCoreDataService *dataService;

@end

