//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSDictionary;
@protocol TNDRAppServiceLevelDelegate;

@interface TNDRAppServiceLevel : NSObject
{
    id <TNDRAppServiceLevelDelegate> _delegate;
    NSDictionary *_launchOptions;
    long long _serviceLevel;
}

+ (id)sharedServiceLevel;
@property(nonatomic) long long serviceLevel; // @synthesize serviceLevel=_serviceLevel;
@property(copy, nonatomic) NSDictionary *launchOptions; // @synthesize launchOptions=_launchOptions;
@property(nonatomic) __weak id <TNDRAppServiceLevelDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
@property(readonly, nonatomic) _Bool isGUIOrHigher;
@property(readonly, nonatomic) _Bool isAPIOrHigher;
- (void)updateToServiceLevel:(long long)arg1;
- (_Bool)attemptUpdateToServiceLevel:(long long)arg1 withLaunchOptions:(id)arg2;

@end

