//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UICollectionViewCell.h>

@class NSString, TNDRPlusRowModel, TNDRTitleSubtitleView, UIImageView, UISwitch, UIView;
@protocol TNDRPlusCellDelegate;

@interface TNDRPlusOptionCell : UICollectionViewCell
{
    id <TNDRPlusCellDelegate> _delegate;
    TNDRTitleSubtitleView *_titleSubtitleContainer;
    TNDRPlusRowModel *_model;
    UIView *_rightContainerView;
    UISwitch *_onOffSwitch;
    UIImageView *_checkMarkView;
    UIView *_passportContainer;
    TNDRTitleSubtitleView *_passportLabel;
    UIView *_topBorder;
}

@property(retain, nonatomic) UIView *topBorder; // @synthesize topBorder=_topBorder;
@property(retain, nonatomic) TNDRTitleSubtitleView *passportLabel; // @synthesize passportLabel=_passportLabel;
@property(retain, nonatomic) UIView *passportContainer; // @synthesize passportContainer=_passportContainer;
@property(retain, nonatomic) UIImageView *checkMarkView; // @synthesize checkMarkView=_checkMarkView;
@property(retain, nonatomic) UISwitch *onOffSwitch; // @synthesize onOffSwitch=_onOffSwitch;
@property(retain, nonatomic) UIView *rightContainerView; // @synthesize rightContainerView=_rightContainerView;
@property(retain, nonatomic) TNDRPlusRowModel *model; // @synthesize model=_model;
@property(readonly, nonatomic) TNDRTitleSubtitleView *titleSubtitleContainer; // @synthesize titleSubtitleContainer=_titleSubtitleContainer;
@property(nonatomic) __weak id <TNDRPlusCellDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
@property(copy, nonatomic) NSString *subtitle;
@property(copy, nonatomic) NSString *title;
- (void)setSelected:(_Bool)arg1;
- (void)switchChanged:(id)arg1;
- (void)setupForType:(unsigned long long)arg1 data:(id)arg2;
- (void)setupLabelWithData:(id)arg1 shouldCreateViews:(_Bool)arg2;
- (void)setupSwitchWithData:(id)arg1 shouldCreateViews:(_Bool)arg2;
- (void)setupPassportWithData:(id)arg1 shouldCreateViews:(_Bool)arg2;
- (void)setupCheckmarkWidthData:(id)arg1 shouldCreateViews:(_Bool)arg2;
- (id)viewForType:(unsigned long long)arg1;
- (id)initWithFrame:(struct CGRect)arg1;

@end

