//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "TNDRPaywallViewModel.h"

@interface TNDRBoostPaywallViewModel : TNDRPaywallViewModel
{
}

+ (id)youHaveConsumablesLeftForQuantity:(long long)arg1;
+ (id)buyStringForQuantity:(long long)arg1;
+ (id)pluralConsumablesLeft;
+ (id)singularConsumablesLeft;
+ (id)pluralBuyString;
+ (id)singularBuyString;
+ (id)perUnitDenominatorStringFormat;
+ (id)unitPluralString;
+ (id)unitSingularString;
- (void)trackBoostPaywallSelectWithIndexPath:(id)arg1 encounteredFrom:(unsigned long long)arg2;

@end

