//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "_TNDRLocation.h"

#import "TNDRParsable-Protocol.h"

@class CLLocation, MKPlacemark, NSString;

@interface TNDRLocation : _TNDRLocation <TNDRParsable>
{
}

+ (id)safeValueForPlacemarkValue:(id)arg1;
+ (id)createLocationFromLocation:(id)arg1 placemark:(id)arg2 inContext:(id)arg3;
@property(readonly, nonatomic) MKPlacemark *placemark;
@property(readonly, nonatomic) struct CLLocationCoordinate2D coordinate;
@property(readonly, nonatomic) NSString *shortLocationName;
@property(readonly, nonatomic) NSString *niceLocationName;
- (void)setCoordinate:(struct CLLocationCoordinate2D)arg1;
@property(readonly, nonatomic) CLLocation *location;
- (void)updateFromDictionary:(id)arg1;
- (_Bool)isCoordinate:(struct CLLocationCoordinate2D)arg1 equivalentToCoordinate:(struct CLLocationCoordinate2D)arg2 maximumDelta:(double)arg3;
- (_Bool)isEqualToLocation:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

