//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSOperation.h>

@class NSDictionary, TNDRCoreDataService;

@interface TNDRGroupMergeOperation : NSOperation
{
    _Bool _isExecuting;
    _Bool _isFinished;
    NSDictionary *_groupDict;
}

@property(copy, nonatomic) NSDictionary *groupDict; // @synthesize groupDict=_groupDict;
- (void).cxx_destruct;
- (void)mergeGroup;
- (void)start;
- (_Bool)isAsynchronous;
- (_Bool)isFinished;
- (_Bool)isExecuting;
@property(readonly, nonatomic) TNDRCoreDataService *dataService;
- (void)setFinished:(_Bool)arg1;
- (void)setExecuting:(_Bool)arg1;
- (id)initWithGroupToMerge:(id)arg1;

@end

