//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "TNDRPurchaseLogger.h"

@interface TNDRPurchaseLogger (Tinder1)
- (void)trackWithError:(id)arg1 productIdentifier:(id)arg2;
@end

