//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "TNDROptionsTableViewControllerDelegate-Protocol.h"

@class NSArray, NSMutableArray, NSString, TNDRAllSettingsItem, TNDRCoreDataService, TNDRCurrentUser, TNDRExperimentCoordinator, TNDRGenderFilterSettingsViewModel, TNDRSettingsAnalyticsClient;

@interface TNDRAllSettingsMenuVM : NSObject <TNDROptionsTableViewControllerDelegate>
{
    NSMutableArray *_sections;
    NSArray *_discoverySettings;
    NSArray *_groupSettings;
    NSArray *_webProfileSettings;
    NSArray *_notificationSettings;
    NSArray *_legalSettings;
    NSArray *_communitySettings;
    TNDRAllSettingsItem *_hideMe;
    TNDRAllSettingsItem *_recsBlend;
    TNDRAllSettingsItem *_webProfileUsername;
    TNDRAllSettingsItem *_shareTinder;
    TNDRAllSettingsItem *_helpAndSupport;
    TNDRAllSettingsItem *_safetyTips;
    TNDRAllSettingsItem *_communityGuidelines;
    TNDRAllSettingsItem *_rateUs;
    TNDRAllSettingsItem *_logout;
    TNDRAllSettingsItem *_deleteAccount;
    long long _currentSelectedBlend;
    TNDRGenderFilterSettingsViewModel *_genderFilterViewModel;
    TNDRSettingsAnalyticsClient *_analyticsClient;
    TNDRCurrentUser *_currentUser;
}

@property(readonly, nonatomic) TNDRCurrentUser *currentUser; // @synthesize currentUser=_currentUser;
@property(retain, nonatomic) TNDRSettingsAnalyticsClient *analyticsClient; // @synthesize analyticsClient=_analyticsClient;
@property(retain, nonatomic) TNDRGenderFilterSettingsViewModel *genderFilterViewModel; // @synthesize genderFilterViewModel=_genderFilterViewModel;
@property(nonatomic) long long currentSelectedBlend; // @synthesize currentSelectedBlend=_currentSelectedBlend;
@property(retain, nonatomic) TNDRAllSettingsItem *deleteAccount; // @synthesize deleteAccount=_deleteAccount;
@property(retain, nonatomic) TNDRAllSettingsItem *logout; // @synthesize logout=_logout;
@property(retain, nonatomic) TNDRAllSettingsItem *rateUs; // @synthesize rateUs=_rateUs;
@property(retain, nonatomic) TNDRAllSettingsItem *communityGuidelines; // @synthesize communityGuidelines=_communityGuidelines;
@property(retain, nonatomic) TNDRAllSettingsItem *safetyTips; // @synthesize safetyTips=_safetyTips;
@property(retain, nonatomic) TNDRAllSettingsItem *helpAndSupport; // @synthesize helpAndSupport=_helpAndSupport;
@property(retain, nonatomic) TNDRAllSettingsItem *shareTinder; // @synthesize shareTinder=_shareTinder;
@property(retain, nonatomic) TNDRAllSettingsItem *webProfileUsername; // @synthesize webProfileUsername=_webProfileUsername;
@property(retain, nonatomic) TNDRAllSettingsItem *recsBlend; // @synthesize recsBlend=_recsBlend;
@property(retain, nonatomic) TNDRAllSettingsItem *hideMe; // @synthesize hideMe=_hideMe;
@property(copy, nonatomic) NSArray *communitySettings; // @synthesize communitySettings=_communitySettings;
@property(copy, nonatomic) NSArray *legalSettings; // @synthesize legalSettings=_legalSettings;
@property(copy, nonatomic) NSArray *notificationSettings; // @synthesize notificationSettings=_notificationSettings;
@property(copy, nonatomic) NSArray *webProfileSettings; // @synthesize webProfileSettings=_webProfileSettings;
@property(copy, nonatomic) NSArray *groupSettings; // @synthesize groupSettings=_groupSettings;
@property(copy, nonatomic) NSArray *discoverySettings; // @synthesize discoverySettings=_discoverySettings;
@property(retain, nonatomic) NSMutableArray *sections; // @synthesize sections=_sections;
- (void).cxx_destruct;
- (void)currentUserPlacemarkDidUpdate:(id)arg1;
- (long long)currentSelectedGender;
- (void)didSelectOptionWithIndex:(long long)arg1;
- (long long)indexForGenderFilter:(long long)arg1;
- (long long)genderFilterTypeForIndex:(long long)arg1;
- (id)attributedStringForLocationText:(id)arg1 traveling:(_Bool)arg2;
- (void)updateLocationForCurrentUser:(id)arg1;
- (id)textForFooterInSection:(long long)arg1;
- (_Bool)isShareTinder:(id)arg1;
- (_Bool)isShareWebProfileRow:(id)arg1;
- (_Bool)isDeleteAccountSection:(long long)arg1;
- (_Bool)isLogoutSection:(long long)arg1;
- (id)titleForHeaderInSection:(long long)arg1;
- (id)viewControllerToPresentForIndexPath:(id)arg1;
@property(readonly, nonatomic) long long sectionCount;
- (long long)numberOfRowsInSection:(long long)arg1;
- (long long)discoverWhereSectionAdjustedRow:(long long)arg1;
- (id)itemForIndexPath:(id)arg1;
- (id)didChangeSlider:(long long)arg1 start:(id)arg2 end:(id)arg3;
- (void)saveDiscoverSettings;
- (void)updateSelectionCellState:(id)arg1 tableView:(id)arg2;
- (id)notificationSwitchIndexPath:(long long)arg1;
- (id)newLikesOptionsIndexPaths;
- (void)updateSwitchState:(long long)arg1 isOn:(_Bool)arg2 tableView:(id)arg3 completionBlock:(CDUnknownBlockType)arg4;
- (void)updateServerWithNewPushNotificationSettings;
- (void)saveSwitches;
- (_Bool)saveFastMatchSettings;
- (void)saveAllSettings;
- (void)updateForCurrentUser;
- (void)currentUserDidSynchronize;
- (void)setupLogoutDelete;
- (void)setupLegalSection;
- (void)setupCommunitySection;
- (void)setupHelpAndSupportSection;
- (void)setupSingleRowSections;
- (id)setupFastMatchNotificationOptionItems;
- (void)setupNotificationSection;
- (void)setupWebProfileSection;
- (void)setupGroupSection;
- (id)setupAgeItem;
- (id)setupGenderItem;
- (void)configureDistanceItemForStandardMeasurement:(id)arg1;
- (void)configureDistanceItemForMetricMeasurement:(id)arg1;
- (id)setupDistanceItem;
- (id)setupLocationItem;
- (void)setupDiscoverySection;
- (void)setupSections;
- (void)setup;
- (void)dealloc;
- (id)initWithCurrentUser:(id)arg1;
@property(readonly) TNDRExperimentCoordinator *experimentCoordinator;
@property(readonly, nonatomic) TNDRCoreDataService *dataService;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

