//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "UICollectionViewDataSource-Protocol.h"

@class NSFetchedResultsController, NSMutableDictionary, NSMutableSet, NSString, TNDRCoreDataService, TNDRCurrentUser, TNDRMatch, TNDRMatchImage, UICollectionViewFlowLayout, UIImage;
@protocol NSFetchedResultsControllerDelegate><TNDRChatMessagesViewModelDelegate><TNDRChatCellDelegate><TTTAttributedLabelDelegate;

@interface TNDRChatMessagesViewModel : NSObject <UICollectionViewDataSource>
{
    _Bool _isPreviewingForPeek;
    NSFetchedResultsController *_fetchedResultsController;
    long long _offsetIntoMessages;
    unsigned long long _totalCountMessages;
    long long _numberOfIllegalMessages;
    long long _lastNumberOfMessagesBeforeUpdates;
    TNDRMatch *_match;
    UICollectionViewFlowLayout *_flowLayout;
    unsigned long long _currentNumMessagesToRetrieve;
    id <NSFetchedResultsControllerDelegate><TNDRChatMessagesViewModelDelegate><TNDRChatCellDelegate><TTTAttributedLabelDelegate> _delegate;
    NSMutableDictionary *_calculatedHeightsDictionary;
    NSMutableSet *_insertedItems;
    UIImage *_cachedAvatarImage;
    TNDRMatchImage *_matchImageObject;
    TNDRCurrentUser *_currentUser;
}

@property(readonly, nonatomic) TNDRCurrentUser *currentUser; // @synthesize currentUser=_currentUser;
@property(retain, nonatomic) TNDRMatchImage *matchImageObject; // @synthesize matchImageObject=_matchImageObject;
@property(retain, nonatomic) UIImage *cachedAvatarImage; // @synthesize cachedAvatarImage=_cachedAvatarImage;
@property(retain, nonatomic) NSMutableSet *insertedItems; // @synthesize insertedItems=_insertedItems;
@property(retain, nonatomic) NSMutableDictionary *calculatedHeightsDictionary; // @synthesize calculatedHeightsDictionary=_calculatedHeightsDictionary;
@property(nonatomic) __weak id <NSFetchedResultsControllerDelegate><TNDRChatMessagesViewModelDelegate><TNDRChatCellDelegate><TTTAttributedLabelDelegate> delegate; // @synthesize delegate=_delegate;
@property(nonatomic) unsigned long long currentNumMessagesToRetrieve; // @synthesize currentNumMessagesToRetrieve=_currentNumMessagesToRetrieve;
@property(retain, nonatomic) UICollectionViewFlowLayout *flowLayout; // @synthesize flowLayout=_flowLayout;
@property(retain, nonatomic) TNDRMatch *match; // @synthesize match=_match;
@property(nonatomic) long long lastNumberOfMessagesBeforeUpdates; // @synthesize lastNumberOfMessagesBeforeUpdates=_lastNumberOfMessagesBeforeUpdates;
@property(nonatomic) long long numberOfIllegalMessages; // @synthesize numberOfIllegalMessages=_numberOfIllegalMessages;
@property(nonatomic) _Bool isPreviewingForPeek; // @synthesize isPreviewingForPeek=_isPreviewingForPeek;
@property(nonatomic) unsigned long long totalCountMessages; // @synthesize totalCountMessages=_totalCountMessages;
@property(nonatomic) long long offsetIntoMessages; // @synthesize offsetIntoMessages=_offsetIntoMessages;
@property(retain, nonatomic) NSFetchedResultsController *fetchedResultsController; // @synthesize fetchedResultsController=_fetchedResultsController;
- (void).cxx_destruct;
- (id)filterGIFMessages:(id)arg1;
- (id)messagesWithCurrentlySelectedGIFIndexPath:(id)arg1 gifControllerToUpdate:(id)arg2;
- (void)preventDuplicateOfString:(id)arg1;
- (id)initialSaying;
- (id)youMatchedText;
- (double)heightForTextAtIndexPath:(id)arg1 hasTail:(_Bool)arg2 leftMessage:(_Bool)arg3;
- (double)heightForMessageAtIndexPath:(id)arg1 collectionView:(id)arg2;
- (struct CGSize)collectionView:(id)arg1 layout:(id)arg2 sizeForItemAtIndexPath:(id)arg3;
- (_Bool)hasTailAtIndexPath:(id)arg1;
- (_Bool)isLastMessageAtIndexPath:(id)arg1;
- (_Bool)shouldShowNameAtIndexPath:(id)arg1;
- (_Bool)shouldShowExpirationDateForIndexPath:(id)arg1;
- (_Bool)shouldShowMatchDateForIndexPath:(id)arg1;
- (_Bool)shouldShowTimestampForIndexPath:(id)arg1;
- (void)setupCell:(id)arg1 forIndexPath:(id)arg2 andMessage:(id)arg3;
- (id)collectionView:(id)arg1 cellForItemAtIndexPath:(id)arg2;
- (long long)collectionView:(id)arg1 numberOfItemsInSection:(long long)arg2;
- (long long)numberOfMessagesInViewInSection:(long long)arg1;
- (void)unmarkIndexPathForInsertion:(id)arg1;
- (void)markMessageItemForInsertion:(long long)arg1;
@property(readonly, nonatomic) _Bool hasLoadedAllAvailableMessages;
- (void)markAllMessagesForReloading;
- (void)markMessageItemForUpdating:(long long)arg1;
- (void)markMessageItemsForUpdating:(id)arg1;
@property(readonly, nonatomic) long long superLikeType;
- (id)messageAtIndexPath:(id)arg1;
- (id)predicateForMatch:(id)arg1;
- (id)fetchRequestForAllMessagesOfMatch:(id)arg1;
- (unsigned long long)messageIndexForMessage:(id)arg1;
- (unsigned long long)totalNumberOfMessages;
- (id)fetchRequestForPreviousSetOfMessages;
- (void)updateModelWithPreviousSetOfMessages;
- (void)updateFetchOffsetLimitAndLoadPrevious:(_Bool)arg1;
- (void)initializeFetchOffsetAndLimit;
- (void)setupMessagesData;
- (id)initWithMatch:(id)arg1 cachedAvatarImage:(id)arg2 chatDelegate:(id)arg3 flowLayout:(id)arg4 currentUser:(id)arg5;
@property(readonly, nonatomic) TNDRCoreDataService *dataService;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

