//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "TNDROnboardingCoordinator.h"

@interface TNDROnboardingCoordinator (Tinder2)
- (void)onboardingStepShouldRemoveCustomGenderField:(id)arg1;
- (void)onboardingStepRequestedCancel:(id)arg1 shouldResetServerData:(_Bool)arg2;
@end

