//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "_TNDRGroup.h"

#import "TNDRUserGroupProtocol-Protocol.h"

@class NSString, TNDRCoreDataService, TNDRMatch, TNDRUser, UIColor;

@interface TNDRGroup : _TNDRGroup <TNDRUserGroupProtocol>
{
    _Bool _profileViewed;
}

+ (id)formattedNameForMembers:(id)arg1 owner:(id)arg2 currentUserID:(id)arg3;
+ (void)clearAllCurrentGroupsExcept:(id)arg1 inContext:(id)arg2;
+ (void)clearAllCurrentGroupsInContext:(id)arg1;
+ (id)rewindableGroup;
+ (id)insertWith:(id)arg1 in:(id)arg2;
@property(nonatomic, getter=isProfileViewed) _Bool profileViewed; // @synthesize profileViewed=_profileViewed;
- (void)refreshStatusWithCompletion:(CDUnknownBlockType)arg1;
- (void)trackRewindFromPaywall:(_Bool)arg1 isUserTraveling:(_Bool)arg2;
- (void)deleteCurrentMembers;
- (_Bool)isVerified;
@property(readonly, nonatomic) NSString *commonName;
@property(readonly, nonatomic) NSString *entityID;
- (void)resetForRewind;
- (id)memberUserIDsForAnalytics;
@property(readonly, nonatomic) NSString *groupNameWithoutMe;
@property(readonly, nonatomic) NSString *groupName;
@property(readonly, nonatomic) NSString *groupTitle;
- (id)groupMatchDescription;
- (id)membersWithoutPlaceholders;
- (id)membersWithoutOwner;
- (id)membersWithOwnerFirst;
- (void)trackRecsPhotoView;
- (void)trackRecsViewInContext:(id)arg1;
@property(readonly, nonatomic) UIColor *mainBadgeColor;
@property(readonly, nonatomic) NSString *mainBadgeDescription;
@property(readonly, nonatomic) NSString *mainBadgeType;
@property(readonly, nonatomic, getter=isGroupAlmostExpired) _Bool groupAlmostExpired;
@property(readonly, nonatomic) double timeIntervalTilExpiration;
@property(readonly, nonatomic) TNDRUser *owner;
@property(readonly, nonatomic) _Bool currentGroupDidSuperLikeGroup;
- (void)setIsCurrentGroupAndClearOthersInContext:(id)arg1;
- (long long)previousSwipe;
- (void)rewindGroupRecommendation:(CDUnknownBlockType)arg1;
- (void)rewindSuperLikedRecommendation:(CDUnknownBlockType)arg1;
@property(readonly, nonatomic) _Bool didSuperLikeCurrentGroup;
- (id)ownerInContext:(id)arg1;
- (_Bool)setUpGroupFromDictionary:(id)arg1;
@property(readonly, nonatomic) TNDRCoreDataService *dataService;
- (void)updateWith:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly, nonatomic) _Bool likedValue;
@property(readonly, nonatomic) TNDRMatch *match;
@property(readonly, nonatomic) _Bool superLikedValue;
@property(readonly) Class superclass;

@end

