//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "TNDRCardStackViewController.h"

@interface TNDRCardStackViewController (Tinder5)
- (void)rewindToLastCardWithCompletion:(CDUnknownBlockType)arg1;
- (void)pass:(id)arg1 source:(long long)arg2 profileOpen:(unsigned long long)arg3 animateCard:(_Bool)arg4 completion:(CDUnknownBlockType)arg5;
- (void)superLike:(id)arg1 source:(long long)arg2 profileOpen:(unsigned long long)arg3 animateCard:(_Bool)arg4 completion:(CDUnknownBlockType)arg5;
- (void)like:(id)arg1 source:(long long)arg2 profileOpen:(unsigned long long)arg3 animateCard:(_Bool)arg4 completion:(CDUnknownBlockType)arg5;
@end

