//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIDevice.h>

@interface UIDevice (model)
+ (id)carrierName;
+ (id)manufacturerName;
+ (id)deviceModelAlternate;
+ (id)deviceModel;
+ (_Bool)isAtLeastiOS10;
+ (_Bool)isAtLeastiOS9;
+ (_Bool)isAtLeastiOS8;
+ (_Bool)isiPad;
+ (_Bool)isiPhone4;
+ (_Bool)isiPhone4or4S;
+ (_Bool)isAtLeastiPhone5;
+ (_Bool)isiPhone5;
+ (_Bool)isiPhone5or5S;
+ (_Bool)isiPhone6;
+ (_Bool)isiPhone6Plus;
+ (_Bool)isLessThaniPhone6;
+ (_Bool)isLessthaniPhone5;
+ (_Bool)deviceSupportsScreenshots;
@end

