//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIFont.h>

@interface UIFont (TNDRFonts)
+ (id)tinderSuperBoldFontWithPointSize:(double)arg1;
+ (id)tinderBoldFontWithPointSize:(double)arg1;
+ (id)tinderItalicFontWithPointSize:(double)arg1;
+ (id)tinderLightItalicFontWithPointSize:(double)arg1;
+ (id)tinderLightFontWithPointSize:(double)arg1;
+ (id)tinderMediumFontWithPointSize:(double)arg1;
+ (id)tinderBaseFontWithPointSize:(double)arg1;
+ (id)tinderSuperBoldFontName;
+ (id)tinderBoldFontName;
+ (id)tinderItalicFontName;
+ (id)tinderLightItalicFontName;
+ (id)tinderLightFontName;
+ (id)tinderMediumFontName;
+ (id)tinderBaseFontName;
+ (double)pointSizeForRegularFontOfSize:(double)arg1;
+ (id)titleTextAttributesForBarButtonItemType:(long long)arg1;
+ (id)tinderStatusSuggestionLeftButtonLabelFont;
+ (id)tinderWhatsNewHeaderLabelFont;
+ (id)tinderWebURLCellLabelFont;
+ (id)tinderUserCardTeaserLabelFontIPhone4;
+ (id)tinderUserCardTeaserLabelFont;
+ (id)tinderMomentCardTimeLabelFont;
+ (id)tinderMomentCardNameLabelFont;
+ (id)tinderUnmatchReasonDialogFont;
+ (id)tinderMenuInfoCellFont;
+ (id)tinderMenuTitleCellFont;
+ (id)tinderProfileHorizontalCVCellFont;
+ (id)tinderMatchCellMessageFont;
+ (id)tinderMatchCellNameFont;
+ (id)tinderIntroPrivacyHeaderFont;
+ (id)tinderIntroDescriptionFontWithSize:(double)arg1;
+ (id)tinderFilterViewControllerNavbarFont;
+ (id)tinderFacebookCropperTitleFont;
+ (id)tinderChatMomentLikeCellLabelFont;
+ (id)tinderChatPendingMatchmakerFont;
+ (id)tinderMiniCardRelativeTimeFont;
+ (id)tinderMiniCardLabelFont;
+ (id)tinderDiscoverSettingsCellFont;
+ (id)tinderDiscoverShowMeCellFont;
+ (id)tinderDiscoverOffDescriptionLabelFont;
+ (id)tinderDiscoverOffTitleLabelFont;
+ (id)tinderDialogCellDetailFont;
+ (id)tinderDialogCellFont;
+ (id)tinderDescriptionFooterLabelFont;
+ (id)tinderCommonConnectionSuperscriptFont;
+ (id)tinderCommonConnectionNumberFont;
+ (id)tinderCommonConnectionNameFont;
+ (id)tinderNoMessagesInChatSayingFont;
+ (id)tinderNoMessagesInChatTimeLabelFont;
+ (id)tinderNoMessagesInChatNameFont;
+ (id)tinderNoMessagesInChatTitleFont;
+ (id)tinderChatNavbarTitleFont;
+ (id)tinderAppSettingsLogoutTitleFont;
+ (id)tinderAppSettingsLogoutButtonFont;
+ (id)tinderAppSettingsSubtextFont;
+ (id)tinderAppSettingsVersionFont;
+ (id)tinderAgeAndGenderVerificationTextFieldFont;
+ (id)tinderAdFooterSubtitleFont;
+ (id)tinderAdFooterFont;
+ (id)tinderActionSheetFont;
+ (id)tinderReportingDialogHeaderDetailTextFont;
+ (id)tinderSuperLikeDialogHeaderDetailTextFont;
+ (id)tinderSuperLikeDialogHeaderTitleTextFont;
+ (id)tinderReportingDialogHeaderTitleTextFont;
+ (id)tinderRateLimitWarningDialogHeaderDetailTextFont;
+ (id)tinderRateLimitWarningDialogHeaderTitleFont;
+ (id)tinderUnmatchDialogHeaderDetailTextFont;
+ (id)tinderUnmatchDialogHeaderTitleTextFont;
+ (id)tinderPhotoCropperFont;
+ (id)tinderDialogFilledCustomTextFooterFont;
+ (id)tinderDialogHeaderDetailTextFont;
+ (id)tinderDialogHeaderTitleTextFont;
+ (id)tinderSettingsNavBarEditFont;
+ (id)tinderSettingsDefaultFontBold;
+ (id)tinderSettingsDefaultFont;
+ (id)tinderSettingsHeaderValueFont;
+ (id)tinderSettingsHeaderTitleFont;
+ (id)tinderGameCardSuperLikeFont;
+ (id)tinderGameCardLightFont;
+ (id)tinderGameCardRegularFont;
+ (id)tinderGameGroupCardBoldFont;
+ (id)tinderGameCardBoldFont;
+ (id)tinderProfilePreviewCollectionTitleFont;
+ (id)tinderIntroPrivacyListMediumFont;
+ (id)tinderIntroInfoButtonFont;
@end

