//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIImage.h>

@interface UIImage (CircleImage)
+ (id)tndr_circleImagePlaceHolderForSize:(struct CGSize)arg1 fillColor:(id)arg2 borderWidth:(double)arg3 borderColor:(id)arg4 dropShadow:(_Bool)arg5;
+ (id)tndr_circleImagePlaceHolderForSize:(struct CGSize)arg1 borderWidth:(double)arg2 borderColor:(id)arg3 dropShadow:(_Bool)arg4;
+ (id)tndr_circleImagePlaceHolderForSize:(struct CGSize)arg1;
- (id)tndr_pixellatedImageWithSize:(double)arg1;
- (id)tndr_imageWithRoundedCornersRadius:(float)arg1;
- (id)tndr_circleImageForSize:(struct CGSize)arg1 borderWidth:(double)arg2 borderColor:(id)arg3 dropShadow:(_Bool)arg4 resizeCropMethod:(int)arg5;
- (id)tndr_circleImageForSize:(struct CGSize)arg1 borderWidth:(double)arg2 borderColor:(id)arg3 dropShadow:(_Bool)arg4;
- (id)tndr_circleImageForSize:(struct CGSize)arg1;
@end

