//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIImage.h>

@interface UIImage (TNDRImageUtility)
+ (id)tndr_clusterViewWithImages:(id)arg1 size:(struct CGSize)arg2;
- (id)tndr_imageClippedByCircleForSize:(struct CGSize)arg1;
- (id)tndr_imageByApplyingAlpha:(double)arg1;
- (id)tndr_fixOrientation;
@end

