//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UINavigationController.h>

#import "TNDRURLNavigableProtocol-Protocol.h"

@class NSString;
@protocol UIViewControllerAnimatedTransitioning;

@interface UINavigationController (URLNavigable) <TNDRURLNavigableProtocol>
+ (id)viewControllerNavigationKey;

// Remaining properties
@property(readonly, nonatomic) id <UIViewControllerAnimatedTransitioning> animationController;
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;
@end

