//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

@interface UIView (Tinder6)
- (id)tndr_constrainEdge:(long long)arg1 toSuperviewEdge:(long long)arg2 constant:(double)arg3;
- (id)tndr_constrainEdgeToSuperviewEdge:(long long)arg1 constant:(double)arg2;
- (id)tndr_constrainEdgesToSuperviewEdgesWithInsets:(struct UIEdgeInsets)arg1;
- (id)tndr_constrainEdgeToSuperviewEdge:(long long)arg1;
- (id)tndr_constrainAttribute:(long long)arg1 toSameAttributeOfView:(id)arg2;
- (id)tndr_constrainToSuperviewEdges:(struct UIEdgeInsets)arg1;
- (id)constrainWithEdge:(long long)arg1 toSuperviewEdge:(long long)arg2 constant:(double)arg3;
- (id)constrainEdgeToSuperviewEdge:(long long)arg1 constant:(double)arg2;
@end

